# -*- coding: utf-8 -*-
"""Wycieczki za miasto, partia 2 (06.10.2026): Gołuchów, Śmiełów, Dziekanowice, Wolsztyn.
Godziny i ceny ze stron obiektów (sprawdzone 06.10.2026), historia streszczona z Wikipedii.
Pułapki: godziny Wielkopolskiego Parku Etnograficznego są tylko na grafice muzeum (m-WPE.jpg);
cennik Parowozowni Wolsztyn obowiązuje od 1.01.2025 (nowszego nie ma na stronie);
poznan.pl i inne serwisy podają dla tych obiektów nieaktualne godziny."""

TRIPS2 = [
    dict(
        slug="zamek-goluchow", cat="wycieczki", name="Zamek w Gołuchowie",
        img="zamek-goluchow", img_alt="Zamek w Gołuchowie z basztami i dachami łupkowymi",
        short="Renesansowy zamek przebudowany dla Izabelli Czartoryskiej, z wnętrzami i zbiorami sztuki. We wtorki wstęp wolny.",
        badge="Wt–nd",
        status=None,
        lead="Zamek w Gołuchowie zbudowano w latach 1550–1560 dla Rafała Leszczyńskiego. W XIX wieku odbudowała go Izabella z Czartoryskich Działyńska i urządziła w nim muzeum. Dziś mieści się tu oddział Muzeum Narodowego w Poznaniu, a wokół rozciąga się park z arboretum.",
        sections=[
            ("Historia", [
                "Wczesnorenesansowy zamek z wieżami w narożach zbudowano w latach 1550–1560. W początkach XVII wieku, za Wacława Leszczyńskiego, dostał rezydencjonalne skrzydła i arkadowe loggie. W 1695 roku Leszczyńscy sprzedali Gołuchów Suskim, a kolejni właściciele doprowadzili zamek do ruiny.",
                "Ruiny kupił w 1856 roku Tytus Działyński (część źródeł podaje 1853) jako prezent ślubny dla syna Jana Kantego i Izabelli z Czartoryskich. Izabella odbudowała zamek w latach 1875–1885, częściowo według szkiców Eugène'a Viollet-le-Duca. Projekt końcowy przygotował francuski architekt Maurycy Auguste Ouradou.",
                "Od 1951 roku w zamku działa oddział Muzeum Narodowego w Poznaniu.",
            ]),
            ("Co zobaczyć", [
                "Zabytkowe wnętrza z włoskimi, francuskimi i hiszpańskimi kominkami, obramieniami okien i mozaikami.",
                "Zbiory sztuki zgromadzone przez Izabellę Czartoryską, m.in. „Ostatnią wieczerzę” Fransa Florisa z XVI wieku oraz kolekcję waz greckich.",
                "Park-arboretum o powierzchni 158 ha z rzadkimi drzewami oraz kaplicę-mauzoleum z 1892 roku, w której spoczywa Izabella.",
            ]),
            ("Warto wiedzieć", [
                "Wejścia odbywają się co pół godziny, w grupach do 30 osób. Ostatnie wejście jesienią i zimą (wt–pt) jest o 15:00, a w lipcu i sierpniu o 16:00.",
                "Zwiedzanie z przewodnikiem jest możliwe tylko po wcześniejszej rezerwacji telefonicznej lub mailowej. Budynek ma trzy kondygnacje i nie ma windy, a przy wejściu głównym są schody.",
            ]),
        ],
        address="ul. Działyńskich 2, 63-322 Gołuchów",
        hours=[
            ("Wt–nd, 1.01–30.06 i 1.09–31.12", "9:00–16:00"),
            ("Wt–pt, 1.07–31.08", "9:00–16:00"),
            ("Sb–nd, 1.07–31.08", "10:00–17:00"),
            ("Poniedziałek", "nieczynne"),
        ],
        tickets=[
            ("Normalny", "20 zł"), ("Ulgowy", "13 zł"), ("Wiek 8–26 lat", "1 zł"),
            ("Dzieci do 7 lat", "bezpłatnie"), ("Przewodnik (do 30 osób)", "150 zł plus bilety"),
            ("Wtorek", "bezpłatnie"),
        ],
        phone="+48 62 761 50 94", www=("mnp.art.pl", "https://mnp.art.pl/profile/wizyta-muzeum-zamek-w-goluchowie"),
        credit="zamek-goluchow",
        trip=dict(lat=51.852639, lon=17.933336, getting=[
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Muzeum Narodowe w Poznaniu: wizyta w Muzeum Zamek w Gołuchowie (godziny, ceny 2026)", "https://mnp.art.pl/profile/wizyta-muzeum-zamek-w-goluchowie"),
                 ("Wikipedia: Zamek w Gołuchowie", "https://pl.wikipedia.org/wiki/Zamek_w_Gołuchowie")],
    ),
    dict(
        slug="palac-smielow", cat="wycieczki", name="Pałac w Śmiełowie (Muzeum Mickiewicza)",
        img="palac-smielow", img_alt="Klasycystyczny pałac w Śmiełowie z jońskim portykiem",
        short="Klasycystyczny pałac z końca XVIII wieku, w którym w 1831 roku mieszkał Mickiewicz. Muzeum i park. We wtorki wstęp wolny.",
        badge="Wt–nd",
        status=None,
        lead="Pałac w Śmiełowie to klasycystyczna rezydencja z końca XVIII wieku, zaprojektowana przez Stanisława Zawadzkiego. W sierpniu 1831 roku zatrzymał się w niej Adam Mickiewicz. Od 1970 roku pałac należy do Muzeum Narodowego w Poznaniu i jest muzeum poety.",
        sections=[
            ("Pałac i park", [
                "Budynek ma monumentalny portyk joński i neopalladiańskie galerie arkadowe. Do pałacu dochodzą charakterystyczne oficyny z dachami mansardowymi.",
                "Wokół rozciąga się około 14 hektarów parku w stylu angielskim. Podobno Mickiewicz posadził tu w 1831 roku dąb, symbol odrodzenia Polski.",
            ]),
            ("Muzeum", [
                "Muzeum łączy pamiątki związane z Mickiewiczem z historią samego pałacu i jego dawnych właścicieli.",
            ]),
            ("Warto wiedzieć", [
                "Kasa zamyka się 30 minut przed zamknięciem muzeum. Budynek nie ma windy, przy wejściu głównym są schody, a toaleta nie jest dostosowana do osób z niepełnosprawnościami.",
                "Muzeum jest nieczynne m.in. 1 stycznia, w Wielkanoc, w Boże Ciało, 1 listopada oraz 24–26 i 31 grudnia. W dni 6 stycznia, 1 maja, 3 maja, 15 sierpnia i 11 listopada obowiązują godziny niedzielne.",
            ]),
        ],
        address="Śmiełów 1, 63-210 Żerków",
        hours=[
            ("Wt–pt", "9:00–16:00"), ("Sb–nd", "10:00–16:00"), ("Poniedziałek", "nieczynne"),
        ],
        tickets=[
            ("Normalny", "15 zł"), ("Ulgowy", "10 zł"), ("Wiek 8–26 lat", "1 zł"), ("Wtorek", "bezpłatnie"),
        ],
        phone="+48 62 740 31 64", www=("mnp.art.pl", "https://mnp.art.pl/profile/wizyta-muzeum-mickiewicza-w-smielowie"),
        credit="palac-smielow",
        trip=dict(lat=52.10645, lon=17.5712, getting=[
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Muzeum Narodowe w Poznaniu: wizyta w Muzeum Mickiewicza w Śmiełowie (godziny, ceny 2026)", "https://mnp.art.pl/profile/wizyta-muzeum-mickiewicza-w-smielowie"),
                 ("Muzeum Narodowe w Poznaniu: Muzeum A. Mickiewicza w Śmiełowie", "https://mnp.art.pl/muzeum-a-mickiewicza-w-smielowie"),
                 ("Wikipedia: Pałac w Śmiełowie", "https://pl.wikipedia.org/wiki/Pałac_w_Śmiełowie")],
    ),
    dict(
        slug="wpe-dziekanowice", cat="wycieczki", name="Wielkopolski Park Etnograficzny w Dziekanowicach",
        img="wpe-dziekanowice", img_alt="Strzechą kryta chata i stodoła w skansenie w Dziekanowicach",
        short="Skansen dawnej wielkopolskiej wsi nad jeziorem Lednica: chaty, kościół, młyn i wiatraki. Czynny od kwietnia do października.",
        badge="Kwiecień–październik",
        status=("warning", "Park jest czynny od 12 kwietnia do 31 października. Od 2 listopada do 11 kwietnia jest zamknięty (wszystkie oddziały muzeum są nieczynne od 21 grudnia do 2 marca)."),
        lead="Wielkopolski Park Etnograficzny w Dziekanowicach to skansen, który pokazuje tradycyjną wieś wielkopolską z przełomu XIX i XX wieku. Należy do Muzeum Pierwszych Piastów na Lednicy i leży nad jeziorem Lednica, niedaleko Ostrowa Lednickiego.",
        sections=[
            ("O skansenie", [
                "Budowę zaczęto 29 września 1975 roku, pierwszą ekspozycję udostępniono 1 czerwca 1982 roku, a status muzeum park uzyskał 25 maja 1993 roku.",
                "W skansenie stoją domy, budynki gospodarcze i stodoły z wyposażeniem. Najstarsze obiekty pochodzą z 1602 roku, a najmłodsze z 1935 roku.",
            ]),
            ("Co zobaczyć", [
                "Zagrody wiejskie, drewniany kościół i kaplicę.",
                "Barokowy dwór z folwarkiem, karczmę, młyn wodny i wiatraki.",
                "Wnętrza zagród z oryginalnym wyposażeniem, pokazujące życie i pracę dawnej wsi.",
            ]),
            ("Warto wiedzieć", [
                "Bilety sprzedaje się do 45 minut przed zamknięciem ekspozycji, a bilety z audioprzewodnikiem do godziny przed zamknięciem. Przerwy w kasie: wt–pt 12:40–13:00, w weekendy i święta 13:40–14:00.",
                "Parking jest bezpłatny. Przewodnika i lekcje muzealne rezerwuje się mailowo (wpe@lednica.pl).",
                "Ostrów Lednicki jest w tym samym muzeum, ma podobne godziny, ale własne bilety.",
            ]),
        ],
        address="Dziekanowice 32, 62-261 Lednogóra",
        hours=[
            ("Wt–pt, 12.04–31.10", "9:00–17:00"),
            ("Sb–nd i święta, 12.04–30.04 i 1.09–31.10", "10:00–17:00"),
            ("Sb–nd i święta, 1.05–31.08", "10:00–18:00"),
            ("Poniedziałek", "nieczynne"),
            ("1.11–11.04", "nieczynne"),
        ],
        tickets=[
            ("Normalny", "25 zł (z audioprzewodnikiem 35 zł)"),
            ("Ulgowy", "17 zł (z audioprzewodnikiem 20 zł)"),
            ("Dzieci do 7 lat", "bezpłatnie"),
            ("Czwartek", "bezpłatnie"),
        ],
        phone="+48 61 427 50 10", www=("lednicamuzeum.pl", "https://lednicamuzeum.pl/strona,wielkopolski-park-etnograficzny-w-dziekanowicach.html"),
        credit="wpe-dziekanowice",
        trip=dict(lat=52.514211, lon=17.38155, getting=[
            ("Samochód", "Parking na terenie parku jest bezpłatny."),
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Muzeum Pierwszych Piastów na Lednicy: godziny otwarcia i bilety 2026", "https://lednicamuzeum.pl/strona,godziny-otwarcia.html"),
                 ("Muzeum Pierwszych Piastów na Lednicy: Wielkopolski Park Etnograficzny", "https://lednicamuzeum.pl/strona,wielkopolski-park-etnograficzny-w-dziekanowicach.html"),
                 ("Muzeum Pierwszych Piastów na Lednicy: godziny WPE (grafika 2026)", "https://lednicamuzeum.pl/files/2026/Godziny%20otwarcia/m-WPE.jpg"),
                 ("Wikipedia: Wielkopolski Park Etnograficzny w Dziekanowicach", "https://pl.wikipedia.org/wiki/Wielkopolski_Park_Etnograficzny_w_Dziekanowicach")],
    ),
    dict(
        slug="parowozownia-wolsztyn", cat="wycieczki", name="Parowozownia Wolsztyn",
        img="parowozownia-wolsztyn", img_alt="Półkolista parowozownia w Wolsztynie z obrotnicą",
        short="Czynna parowozownia z 1907 roku, skąd wyjeżdżają parowozy z pociągami pasażerskimi. Zwiedzanie codziennie 7:00–16:00.",
        badge="Codziennie",
        status=None,
        lead="Parowozownia w Wolsztynie to czynna stacja parowozów, z której do dziś wyjeżdżają pociągi z lokomotywą parową. Halę z wieżą ciśnień zbudowano w 1907 roku. To czynna parowozownia, w której nadal przygotowuje się parowozy do jazdy.",
        sections=[
            ("Historia", [
                "W 1907 roku powstała parowozownia z wieżą wodną. W 1991 roku parowozownię przemianowano na Parowozownię Wolsztyn i zorganizowano pierwszą Paradę Parowozów.",
                "W czerwcu 2016 roku powołano tu instytucję kultury, a na początku 2017 roku otrzymała ona certyfikat przewoźnika kolejowego. Od 2004 roku odbywa się też konkurs Miss Świata Parowozów.",
            ]),
            ("Co zobaczyć", [
                "W zbiorach jest około 30 parowozów (dane PAP z 2018 roku), w tym słynny Pm36-2 „Piękna Helena”. W ruchu planowym jeździ m.in. powojenny parowóz Pt47-65.",
                "Zabytkową obrotnicę, wieżę ciśnień i małe muzeum z dawnymi biletami, sygnalizacją i latarniami kolejarzy oraz makietą fragmentu stacji Wolsztyn.",
                "Co roku na przełomie kwietnia i maja odbywa się Parada Parowozów (jubileuszowa, 30. edycja miała miejsce 2 maja 2026 roku).",
            ]),
            ("Warto wiedzieć", [
                "Strona parowozowni radzi przyjść krótko przed odjazdem lokomotywy, żeby zobaczyć tradycyjne przygotowanie parowozu do drogi.",
                "Pociąg z parowozem w soboty jedzie z Wolsztyna do Poznania Głównego (według rozkładu obowiązującego od 7.03.2026: odjazd z Wolsztyna 10:46, przyjazd 12:50, powrót z Poznania Głównego 15:21). W dni robocze kursuje na trasie Wolsztyn–Zbąszynek, a w niedziele i święta w ruchu planowym nie jeździ. Bilety kupisz na stronie Kolei Wielkopolskich, w kasie na dworcu lub u kierownika pociągu. Przed wyjazdem sprawdź rozkład na stronie parowozowni, bo na czas przeglądów parowóz zastępuje lokomotywa spalinowa.",
                "Cennik na stronie parowozowni obowiązuje od 1 stycznia 2025 roku. Zwiedzanie z przewodnikiem wymaga wcześniejszej rezerwacji.",
            ]),
        ],
        address="ul. Fabryczna 1, 64-200 Wolsztyn",
        hours=[
            ("Codziennie, także w niedziele i święta", "7:00–16:00"),
            ("Ostatnie wejście", "15:00"),
        ],
        tickets=[
            ("Normalny", "20 zł"), ("Ulgowy", "15 zł"), ("Przewodnik (rezerwacja)", "80 zł"),
            ("Dzieci do 7 lat", "bezpłatnie"),
        ],
        phone="+48 506 985 166", www=("parowozowniawolsztyn.pl", "https://parowozowniawolsztyn.pl/"),
        credit="parowozownia-wolsztyn",
        trip=dict(lat=52.106184, lon=16.112819, getting=[
            ("Pociąg", "Z Poznania Głównego do Wolsztyna jeżdżą pociągi Kolei Wielkopolskich. W soboty jeden kurs obsługuje parowóz, ale ten z Poznania (odjazd 15:21) dojeżdża do Wolsztyna o 17:46, czyli po zamknięciu parowozowni. Na zwiedzanie wybierz więc wcześniejszy, zwykły pociąg."),
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Parowozownia Wolsztyn: strona główna (godziny od 1.10.2026)", "https://parowozowniawolsztyn.pl/"),
                 ("Parowozownia Wolsztyn: godziny otwarcia", "https://parowozowniawolsztyn.pl/?page_id=2131"),
                 ("Parowozownia Wolsztyn: ceny biletów (cennik od 1.01.2025)", "https://parowozowniawolsztyn.pl/?page_id=2136"),
                 ("Parowozownia Wolsztyn: rozkład jazdy parowozów", "https://parowozowniawolsztyn.pl/?page_id=2141"),
                 ("PAP/dzieje.pl: Wolsztyn, jubileuszowa XXV Parada Parowozów (28.04.2018, liczba parowozów)", "https://dzieje.pl/rozmaitosci/wolsztyn-w-weekend-jubileuszowa-xxv-parada-parowozow"),
                 ("PAP/dzieje.pl: jubileuszowa 30. Parada Parowozów (19.04.2026)", "https://dzieje.pl/node/168113"),
                 ("Wikipedia: Parowozownia Wolsztyn", "https://pl.wikipedia.org/wiki/Parowozownia_Wolsztyn")],
    ),
    dict(
        slug="zagroda-zwierzat-goluchow", cat="wycieczki", name="Pokazowa Zagroda Zwierząt w Gołuchowie",
        img="zagroda-zwierzat-goluchow", img_alt="Żubr w Pokazowej Zagrodzie Zwierząt w Gołuchowie",
        short="Ponad 20 ha lasu, w którym żyją żubry, koniki polskie, daniele i dziki. Wstęp bezpłatny, czynna od świtu do zmierzchu.",
        badge="Bezpłatnie",
        status=None,
        lead="Pokazowa Zagroda Zwierząt należy do Ośrodka Kultury Leśnej w Gołuchowie, obok zamku i parku-arboretum. Zajmuje ponad 20 hektarów ogrodzonego lasu mieszanego z sosną i dębem. Powstała z myślą o hodowli żubrów. Wstęp jest bezpłatny, a zagroda otwarta przez cały rok.",
        sections=[
            ("Zwierzęta", [
                "Zagrodę założono w kwietniu 1977 roku z myślą o rosnącej liczbie żubrów i rozproszeniu ich hodowli. Do końca 2024 roku hodowano tu 128 żubrów, w tym 114 urodzonych w Gołuchowie.",
                "Oprócz żubrów można zobaczyć koniki polskie, daniele i dziki. Zwierzęta oglądasz z wyznaczonych alejek.",
            ]),
            ("Warto wiedzieć", [
                "Zagroda jest czynna codziennie, od wschodu do zachodu słońca. Wstęp jest bezpłatny. Rocznie odwiedza ją około 120 tysięcy osób.",
                "Przy wejściu trzeba przejść przez maty dezynfekcyjne. Dzieci do 12 lat mogą przebywać na terenie tylko pod opieką dorosłych.",
                "Obowiązuje zakaz karmienia, dotykania i płoszenia zwierząt, fotografowania z lampą błyskową oraz poruszania się poza alejkami. Nie wolno wprowadzać zwierząt domowych (poza psami przewodnikami), a także jeździć rowerem, na rolkach czy hulajnodze.",
                "Obok działa Muzeum Leśnictwa w dawnych zabudowaniach folwarku (wt–nd 10:00–16:00, bilet pełny 25 zł, ulgowy 18 zł) oraz bezpłatny park-arboretum. Zamek w Gołuchowie jest osobnym muzeum.",
            ]),
        ],
        address="ul. Działyńskich 2, 63-322 Gołuchów",
        hours=[
            ("Zagroda, codziennie, cały rok", "od wschodu do zachodu słońca"),
        ],
        tickets=[("Wstęp", "bezpłatnie")],
        phone="+48 62 76 15 045", www=("okl.lasy.gov.pl", "https://www.okl.lasy.gov.pl/pokazowa-zagroda"),
        credit="zagroda-zwierzat-goluchow",
        trip=dict(lat=51.8595602, lon=17.9241702, getting=[
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Ośrodek Kultury Leśnej w Gołuchowie: Pokazowa Zagroda Zwierząt", "https://www.okl.lasy.gov.pl/pokazowa-zagroda"),
                 ("Ośrodek Kultury Leśnej w Gołuchowie: informacja turystyczna", "https://www.okl.lasy.gov.pl/informacja-turystyczna"),
                 ("OKL: regulamin Pokazowej Zagrody Zwierząt (zarządzenie nr 6/2025 z 5.03.2025)", "https://www.okl.lasy.gov.pl/documents/998963/51382627/Regulamin+PZZ/533eea8b-4846-42fe-475f-d01c1ebd3256")],
    ),
    dict(
        slug="muzeum-lesnictwa-goluchow", cat="wycieczki", name="Muzeum Leśnictwa w Gołuchowie",
        img="muzeum-lesnictwa-goluchow", img_alt="Powozownia, jeden z budynków Muzeum Leśnictwa w Gołuchowie",
        short="Cztery zabytkowe budynki dawnego folwarku z wystawami o lesie, leśnictwie i jego technice. Wt–nd 10:00–16:00.",
        badge="Wt–nd",
        status=None,
        lead="Muzeum Leśnictwa działa w Ośrodku Kultury Leśnej w Gołuchowie, w XIX-wiecznych budynkach dawnego folwarku zamkowego Działyńskich. Otwarto je w październiku 1986 roku, a od 1987 roku jest samodzielną jednostką Lasów Państwowych. Obok są zamek, park-arboretum i Pokazowa Zagroda Zwierząt.",
        sections=[
            ("Wystawy", [
                "Oficyna: wystawy „Kulturotwórcza rola lasu” (obrazy, grafiki, rzeźby, ceramika i szkło inspirowane lasem) oraz „Dzieje leśnictwa w Polsce”, od czasów zaborów po PRL, m.in. z modelami dawnych mielerzy, dziegciarni i barci leśnej. Budynek powstał z przebudowy gorzelni.",
                "Powozownia z 1854 roku: „Spotkanie z lasem”, o geografii, ekologii i botanice lasu. Pokazuje m.in. 256 gatunków roślin, grzybów i zwierząt leśnych z Polskiej Czerwonej Księgi oraz XIX-wieczne „księgi drzewne” prof. Carla von Hinterlanga. Jest tu też multimedialna makieta ośrodka.",
                "Owczarnia z 1849 roku (1039 m²): „Technika leśna” z maszynami do produkcji węgla drzewnego, smoły, dziegciu, potażu, terpentyny i sadzy oraz dawnymi przyrządami pomiarowymi. Przeszklony pasaż łączy ją z Powozownią.",
                "Dybul, dawna obora: „Ochrona lasu”, o zagrożeniach naturalnych i cywilizacyjnych dla lasu.",
            ]),
            ("Warto wiedzieć", [
                "Bilet pełny obejmuje wszystkie obiekty, można też kupić bilety do pojedynczych budynków. Honorowana jest Karta Dużej Rodziny ze zniżką 50% biletu normalnego. Zwiedzanie z przewodnikiem rezerwują grupy do 30 osób.",
                "Pokazowa Zagroda Zwierząt z żubrami i park-arboretum są bezpłatne i można je zwiedzić tego samego dnia. Zamek w Gołuchowie to osobne muzeum.",
            ]),
        ],
        address="ul. Działyńskich 2, 63-322 Gołuchów",
        hours=[
            ("Wt–nd", "10:00–16:00"),
            ("Ostatnie wejście", "15:15"),
            ("Poniedziałek", "nieczynne"),
        ],
        tickets=[
            ("Pełny (wszystkie obiekty)", "25 zł"),
            ("Ulgowy", "18 zł"),
            ("Rodzinny (2 dorosłych + do 3 dzieci)", "40 zł"),
            ("Pojedynczy obiekt (Oficyna, Powozownia, Owczarnia)", "15 zł, ulgowy 10 zł"),
            ("Karta Dużej Rodziny", "50% biletu normalnego"),
        ],
        phone="+48 539 330 611", www=("okl.lasy.gov.pl", "https://www.okl.lasy.gov.pl/muzeum-lesnictwa"),
        credit="muzeum-lesnictwa-goluchow",
        trip=dict(lat=51.853157, lon=17.935975, getting=[
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Ośrodek Kultury Leśnej w Gołuchowie: informacja turystyczna (godziny, ceny)", "https://www.okl.lasy.gov.pl/informacja-turystyczna"),
                 ("Ośrodek Kultury Leśnej w Gołuchowie: Muzeum Leśnictwa", "https://www.okl.lasy.gov.pl/muzeum-lesnictwa"),
                 ("Wikipedia: Muzeum Leśnictwa w Gołuchowie", "https://pl.wikipedia.org/wiki/Muzeum_Leśnictwa_w_Gołuchowie")],
    ),
    dict(
        slug="skansen-miniatur-pobiedziska", cat="wycieczki", name="Skansen Miniatur Szlaku Piastowskiego w Pobiedziskach",
        img="skansen-miniatur-pobiedziska", img_alt="Miniatura zabytkowego kościoła w Skansenie Miniatur w Pobiedziskach",
        short="Ponad 30 makiet zabytków Wielkopolski i Szlaku Piastowskiego w skali 1:20, między Poznaniem a Gnieznem. Bilet 12 zł.",
        badge="Cały rok",
        status=None,
        lead="Skansen Miniatur w Pobiedziskach pokazuje makiety ważnych i mniej znanych budowli Szlaku Piastowskiego oraz Wielkopolski w skali 1:20. Leży na trasie z Poznania do Gniezna i jest czynny przez cały rok. W 2026 roku dostał tytuł Rekomendowanej Atrakcji Turystycznej Powiatu Poznańskiego.",
        sections=[
            ("Co zobaczyć", [
                "Ponad 30 miniatur, wśród nich pałac w Rogalinie, katedrę w Gnieźnie, Operę Poznańską i kościół św. Marcina w Poznaniu. To dobry sposób, żeby poznać zabytki regionu przed wyjazdem albo zobaczyć je z dziecięcej perspektywy.",
                "Sto metrów dalej stoi Gród Pobiedziska, więc oba miejsca łatwo połączyć w jednej wizycie.",
            ]),
            ("Warto wiedzieć", [
                "Grupy powyżej 10 osób płacą 10 zł (dorośli) i 8 zł (dzieci), a opiekun na 15 dzieci wchodzi bezpłatnie. Zwiedzanie z przewodnikiem kosztuje 13 zł (dorośli) i 11 zł (dzieci).",
                "Z toalet w skansenie korzystają też odwiedzający Gród Pobiedziska.",
            ]),
        ],
        address="ul. Fabryczna 68, 62-010 Pobiedziska",
        hours=[
            ("Kwiecień–wrzesień", "10:00–18:00"),
            ("Październik–marzec", "9:00–16:00"),
        ],
        tickets=[
            ("Normalny", "12 zł"),
            ("Ulgowy (uczniowie, studenci, emeryci, renciści, nauczyciele, osoby z niepełnosprawnością)", "10 zł"),
            ("Karta Dużej Rodziny", "8 zł"),
            ("Dzieci do 3 lat i przewodnicy", "bezpłatnie"),
        ],
        phone="+48 579 665 665", www=("miniatury.pobiedziska.pl", "https://miniatury.pobiedziska.pl/"),
        credit="skansen-miniatur-pobiedziska",
        trip=dict(lat=52.476277, lon=17.2488436, getting=[
            ("Pociąg", "Pobiedziska leżą na linii Poznań–Gniezno, przy stacji Pobiedziska Letnisko (informacja ze strony Grodu Pobiedziska)."),
            ("Samochód", "Pobiedziska są w połowie drogi między Poznaniem a Gnieznem, przy drodze nr 194. Parking przy gródku jest bezpłatny."),
        ]),
        sources=[("Skansen Miniatur Szlaku Piastowskiego: strona główna (godziny)", "https://miniatury.pobiedziska.pl/"),
                 ("Skansen Miniatur Szlaku Piastowskiego: cennik", "https://miniatury.pobiedziska.pl/cms/263/cennik"),
                 ("Gród Pobiedziska: informacje dla zwiedzających", "https://grodpobiedziska.pl/"),
                 ("poznan.pl: Skansen Miniatur w Pobiedziskach", "https://poznan.pl/mim/turystyka/en/-,p,186.html")],
    ),
    dict(
        slug="grod-pobiedziska", cat="wycieczki", name="Gród Pobiedziska",
        img="grod-pobiedziska", img_alt="Brama i palisada Grodu Pobiedziska z kładką i wieżą",
        short="Rodzinny park z drewnianym grodem z czasów Piastów: szermierka na piankowe miecze, łucznictwo i katapulta. Sezon: maj–wrzesień.",
        badge="Sezonowo",
        status=("warning", "Dla zwiedzających indywidualnych Gród jest czynny od maja do września, w soboty i niedziele oraz w lipcu i sierpniu codziennie. Od października grupy mogą zwiedzać go tylko po wcześniejszej rezerwacji (do końca października)."),
        lead="Gród Pobiedziska to rodzinny park rozrywki, w którym dzieci i dorośli poznają życie we wczesnym średniowieczu. Do dyspozycji są arena walk na piankowe miecze, strzelanie z łuku i kuszy oraz z katapulty, wypożyczalnia strojów średniowiecznych i ognisko ze średniowiecznym gotowaniem.",
        sections=[
            ("Co robić", [
                "Walki na piankowe miecze na specjalnej arenie, strzelanie z łuku, kuszy i katapulty.",
                "Wypożyczalnia strojów średniowiecznych oraz gra w łowienie drewnianych rybek w stawie.",
                "Ognisko z pokazami historycznego gotowania i sklepik z pamiątkami.",
            ]),
            ("Warto wiedzieć", [
                "Na terenie jest zadaszona wiata, a przy złej pogodzie można skorzystać z sali dydaktycznej. Toalety są w sąsiednim Skansenie Miniatur. Parking przy obiekcie jest bezpłatny.",
                "Gród przyjmuje grupy zorganizowane od kwietnia do października po wcześniejszej rezerwacji. Strona gródka honoruje Poznańską Kartę Turystyczną i Kartę Dużej Rodziny.",
                "Strzał z katapulty kosztuje 10 zł, a ognisko 150 zł. Grupy zorganizowane przyjmowane są od kwietnia do października, w godzinach 8:00–20:00, po wcześniejszej rezerwacji (601 377 802 lub biuro@grodpobiedziska.pl).",
            ]),
        ],
        address="ul. Fabryczna 68, 62-010 Pobiedziska",
        hours=[
            ("Weekendy, maj, czerwiec i wrzesień", "10:00–16:00"),
            ("Weekend majowy (1–3.05) i czerwcowy (4–7.06)", "10:00–17:00"),
            ("Lipiec i sierpień, codziennie", "10:00–16:00"),
            ("Poza sezonem", "tylko grupy po rezerwacji"),
        ],
        tickets=[
            ("Normalny", "20 zł"), ("Ulgowy", "15 zł"),
            ("Rodzinny 2+2", "60 zł"), ("Rodzinny 2+3", "65 zł"),
            ("Dzieci do 3 lat", "bezpłatnie"), ("Strzał z katapulty", "10 zł"),
        ],
        phone="+48 601 377 802", www=("grodpobiedziska.pl", "https://grodpobiedziska.pl/bilety/"),
        credit="grod-pobiedziska",
        trip=dict(lat=52.4768209, lon=17.2496887, getting=[
            ("Pociąg", "Pobiedziska leżą na linii Poznań–Gniezno, przy stacji Pobiedziska Letnisko."),
            ("Samochód", "Pobiedziska są w połowie drogi między Poznaniem a Gnieznem, przy drodze nr 194. Parking jest bezpłatny."),
        ]),
        sources=[("Gród Pobiedziska: bilety i godziny otwarcia 2026", "https://grodpobiedziska.pl/bilety/"),
                 ("Gród Pobiedziska: strona główna", "https://grodpobiedziska.pl/")],
    ),
    dict(
        slug="puszcza-zielonka", cat="wycieczki", name="Park Krajobrazowy Puszcza Zielonka",
        img="puszcza-zielonka", img_alt="Leśna ścieżka i droga rowerowa w Puszczy Zielonka",
        short="Duży kompleks leśny kilka kilometrów na północny wschód od Poznania: lasy, jeziora, rezerwaty i szlak 12 drewnianych kościołów.",
        badge="Bezpłatnie",
        status=None,
        lead="Park Krajobrazowy Puszcza Zielonka to jeden z największych kompleksów leśnych środkowej Wielkopolski, położony zaledwie kilka kilometrów na północny wschód od Poznania. Utworzono go w 1993 roku, ma 12 202 hektary, a leśny krajobraz jest tu poprzecinany jeziorami i rzekami.",
        sections=[
            ("Przyroda", [
                "Park chroni jeden z największych kompleksów leśnych środkowej Wielkopolski, w większości pokryty lasem. Na jego terenie jest pięć rezerwatów przyrody: Jezioro Czarne, Jezioro Pławno, Klasztorne Modrzewie koło Dąbrówki Kościelnej, Las mieszany w Nadleśnictwie Łopuchówko oraz Żywiec dziewięciolistny.",
                "W parku leży siedem jezior (m.in. Czarne, Pławno i Bolechowskie) oraz płyną Warta, Trojanka i Struga Wierzenicka. Żyją tu jelenie, dziki, bobry, żurawie i ptaki drapieżne.",
            ]),
            ("Co zobaczyć", [
                "Dziewiczą Górę (143 m n.p.m.), najwyższe wzniesienie w okolicach Poznania, z dostrzegalnią pożarową, z której widać puszczę i miasto.",
                "Szlak Kościołów Drewnianych wokół Puszczy Zielonka: 12 zabytkowych świątyń w Kicinie, Wierzenicy, Uzarzewie, Węglewie, Sławnie, Łagiewnikach Kościelnych, Kiszkowie, Jabłkowie, Raczkowie, Skokach, Rejowcu i Długiej Goślinie. Perłą szlaku jest kościół św. Mikołaja w Wierzenicy, jeden z najstarszych w Wielkopolsce. Między Kicinem a Wierzenicą stoją też rzeźbione kapliczki Tajemnic Różańca.",
                "Arboretum Leśne w Zielonce, ośrodek dydaktyczny uczelni przyrodniczej, oraz ścieżki dydaktyczne wokół Zielonki.",
            ]),
            ("Warto wiedzieć", [
                "Teren parku jest ogólnodostępny, a wstęp bezpłatny. W parku są oznakowane trasy rowerowe.",
                "Kościoły na szlaku to czynne świątynie. Przed wejściem do wnętrza sprawdź, czy nie trwa nabożeństwo, albo umów się z parafią.",
                "Informacji udziela Zespół Parków Krajobrazowych Województwa Wielkopolskiego (tel. 61 65 54 650).",
            ]),
        ],
        address="Puszcza Zielonka, na północny wschód od Poznania",
        hours=[("Teren parku", "ogólnodostępny")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone="+48 61 65 54 650", www=("zpkww.pl", "https://zpkww.pl/parki/park-krajobrazowy-puszcza-zielonka/informacje-ogolne/"),
        credit="puszcza-zielonka",
        trip=dict(lat=52.553333, lon=17.113333, getting=[
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("ZPKWW: Park Krajobrazowy Puszcza Zielonka", "https://zpkww.pl/parki/park-krajobrazowy-puszcza-zielonka/informacje-ogolne/"),
                 ("Wikipedia: Park Krajobrazowy Puszcza Zielonka", "https://pl.wikipedia.org/wiki/Park_Krajobrazowy_Puszcza_Zielonka"),
                 ("Region Wielkopolska: Park Krajobrazowy Puszcza Zielonka", "https://regionwielkopolska.pl/en/katalog-obiektow/the-puszcza-zielonka-landscape-park/"),
                 ("Visit Poznań: Szlak Kościołów Drewnianych wokół Puszczy Zielonki (lista 12 kościołów)", "https://visitpoznan.pl/szlak-kosciolow-drewnianych-wokol-puszczy-zielonki"),
                 ("Wielkopolska Ciekawie: kościoły drewniane Puszczy Zielonki (Droga Różańcowa)", "https://wielkopolskaciekawie.pl/wycieczki/puszcza-zielonka-atrakcje-koscioly-drewniane/")],
    ),
    dict(
        slug="czmoniec-bobrowy-szlak", cat="wycieczki", name="Wieża widokowa i Bobrowy Szlak w Czmońcu",
        img="czmoniec-bobrowy-szlak", img_alt="Drewniana wieża widokowa na Bobrowym Szlaku w Czmońcu",
        short="Drewniana wieża widokowa nad łąkami i starorzeczami Warty oraz krótka ścieżka przyrodnicza. Bez biletów, w gminie Kórnik.",
        badge="Bezpłatnie",
        status=None,
        lead="W Czmońcu, w gminie Kórnik, na skraju rozległych łąk w dolinie Warty stoi drewniana wieża widokowa. Stoi na Bobrowym Szlaku, ścieżce przyrodniczej prowadzącej przez starorzecza Warty.",
        sections=[
            ("Co zobaczyć", [
                "Drewnianą wieżę widokową o wysokości około 14 m, otwartą w 2010 roku. Zbudowano ją z inicjatywy sołtysa Czmońca, a platforma na szczycie mieści jednocześnie do 20 osób. Widać z niej łąki, starorzecza Warty i kępy drzew. Inne źródła podają wysokość wieży 14–15 m.",
                "Bobrowy Szlak, ścieżkę przyrodniczą w dolinie Warty, przez łąki i starorzecza. Można do niej dojść od północy, a ścieżka prowadzi do wieży.",
            ]),
            ("Warto wiedzieć", [
                "Według portalu Visit Poznań do wieży można dojechać samochodem ulicą Malwową (droga gruntowa). Nieoznakowany parking jest kilkaset metrów od wieży. Można też dojść pieszo Bobrowym Szlakiem od północy.",
                "Teren jest otwarty, bez kas i wyznaczonych godzin. Przed wyjazdem sprawdź aktualne zasady dojazdu i parkowania, bo dojazd drogą gruntową może być utrudniony. Informacje o okolicy są też na kornik.travel.",
                "Wycieczkę można połączyć z wizytą w Kórniku lub Rogalinie.",
            ]),
        ],
        address="Czmoniec, ul. Malwowa (wieża na zachód od wsi), gmina Kórnik",
        hours=[("Wieża i szlak", "teren otwarty, bez wyznaczonych godzin")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("visitpoznan.pl", "https://visitpoznan.pl/wieza-widokowa-w-czmoncu"),
        credit="czmoniec-bobrowy-szlak",
        trip=dict(lat=52.178889, lon=17.018611, getting=[
            ("Samochód", "Ulicą Malwową (droga gruntowa) do nieoznakowanego parkingu kilkaset metrów od wieży."),
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Visit Poznań: Wieża widokowa w Czmońcu (dojazd, stan 10.02.2024)", "https://visitpoznan.pl/wieza-widokowa-w-czmoncu"),
                 ("Wikipedia: Czmoniec (wieża widokowa, 2010)", "https://pl.wikipedia.org/wiki/Czmoniec")],
        see_also=[("Punkty widokowe w Poznaniu: wszystkie wieże i tarasy", "punkty-widokowe")],
    ),
]
