# -*- coding: utf-8 -*-
"""Wycieczki za miasto (30.09.2026): Kórnik, Rogalin, Gniezno, Lednica, Biskupin, WPN, Szreniawa, Puszczykowo.
Godziny i ceny wyłącznie ze stron obiektów (sprawdzone 30.09.2026), historia streszczona z Wikipedii.
Pole trip: współrzędne (do odległości od centrum Poznania) i dojazd. Kategoria nie trafia na mapę
przewodnika, bo podkład obejmuje tylko Poznań.
Pułapki wyszukiwarki: Rogalin 45/30 zł karnet i bezpłatny WTOREK (nie 15/10 zł i środa), Biskupin 28/19 zł
(45/35 zł to bilety na festyn), Muzeum Fiedlera 9–16 (nie 9–17), MPPP czynne też w poniedziałki."""

TRIPS = [
    dict(
        slug="zamek-kornik", cat="wycieczki", name="Zamek w Kórniku",
        img="zamek-kornik", img_alt="Neogotycki zamek w Kórniku odbijający się w wodzie fosy",
        short="Neogotycki zamek Działyńskich z legendą o Białej Damie i jedną z najstarszych bibliotek w Polsce.",
        badge="Wt–nd",
        status=("warning", "Sezon zwiedzania trwa do 30 listopada 2026. Od 1 grudnia do 13 lutego zamek jest zamknięty dla zwiedzających."),
        lead="Zamek w Kórniku stoi na dawnej wyspie, otoczony wodą. Ma średniowieczne początki, ale wygląd baśniowej, neogotyckiej rezydencji nadał mu w XIX wieku Tytus Działyński. Dziś mieści Bibliotekę Kórnicką Polskiej Akademii Nauk i muzeum z historycznymi wnętrzami.",
        sections=[
            ("Historia", [
                "Najstarsza wzmianka o zamku pochodzi z 1426 roku. Przez stulecia należał do wielkich wielkopolskich rodów: Górków, Czarnkowskich, Grudzińskich, Działyńskich i Zamoyskich. W 1574 roku gościł tu Henryk Walezy, który jechał na koronację do Krakowa.",
                "W XVIII wieku mieszkała tu Teofila z Działyńskich Szołdrska-Potulicka. Jej portret w białej sukni, który wciąż wisi w zamku, dał początek legendzie o Białej Damie, jednym z najsłynniejszych polskich zamkowych duchów.",
                "W XIX wieku Tytus Działyński przebudował zamek w stylu neogotyku angielskiego. W 1826 roku założył Bibliotekę Kórnicką, która w 1953 roku weszła w skład Polskiej Akademii Nauk. Od 2011 roku zespół zamkowo-parkowy jest Pomnikiem Historii.",
            ]),
            ("Co zobaczyć", [
                "Wnętrza zamku z meblami, obrazami i pamiątkami po dawnych właścicielach, w tym portret Białej Damy.",
                "Zbiory biblioteki należą do najstarszych i najbogatszych w Polsce. Są w nich m.in. rękopisy Chopina, Mickiewicza i Napoleona Bonapartego.",
                "Tuż obok zamku jest Arboretum Kórnickie, które warto zobaczyć przy tej samej wizycie. Obowiązują w nim osobne bilety.",
            ]),
            ("Warto wiedzieć", [
                "Po zamku można chodzić z bezpłatną aplikacją „Zamek w Kórniku” (trzeba mieć własne słuchawki) albo z audioprzewodnikiem wypożyczonym w kasie za 15 zł. W kasie jest też bezpłatna gra terenowa dla dzieci, w której przewodnikiem jest sam Tytus Działyński.",
                "Do zamku nie można wjechać wózkiem dziecięcym, a na miejscu nie ma gdzie go zostawić. Jest winda dla osób z niepełnosprawnością.",
                "Zdjęcia do celów prywatnych można robić bezpłatnie, bez lampy błyskowej i statywu.",
            ]),
        ],
        address="ul. Zamkowa 5, 62-035 Kórnik",
        hours=[("Wt–nd, 14.02–30.04 i 1.10–30.11", "10:00–16:00, ostatnie wejście 15:15"),
               ("Wt–nd, 1.05–30.09", "10:00–17:00, ostatnie wejście 16:15"),
               ("Czwartki w maju i czerwcu", "10:00–20:00"),
               ("Poniedziałek", "nieczynne"), ("1.12–13.02", "nieczynne")],
        tickets=[("Normalny", "40 zł"), ("Ulgowy (m.in. dzieci, młodzież, emeryci)", "20 zł"),
                 ("Audioprzewodnik", "15 zł"), ("Przewodnik po polsku (grupa)", "150 zł")],
        phone=None, www=("bkpan.poznan.pl", "https://www.bkpan.poznan.pl/zamek-w-korniku/"),
        credit="zamek-kornik",
        trip=dict(lat=52.243889, lon=17.090556, getting=[
            ("Autobus", "Autobusy linii 501 i 560 oraz przewoźników podmiejskich, przystanek Kórnik/Pl. Niepodległości, 5 minut pieszo. Zamek poleca też autobusy z Dworca Autobusowego przy dworcu Poznań Główny i z przystanku Rondo Rataje."),
            ("Pociąg", "Zamek odradza pociąg: stacja Kórnik jest ok. 5 km od centrum miasta."),
            ("Samochód", "Płatny parking przy zamku (ok. 30 miejsc) i bezpłatny na Prowencie, ok. 400 m od zamku."),
        ]),
        sources=[("PAN Biblioteka Kórnicka: Zamek w Kórniku (godziny, cennik, dojazd)", "https://www.bkpan.poznan.pl/zamek-w-korniku/"),
                 ("Instytut Dendrologii PAN: Arboretum (dojazd autobusem)", "https://www.idpan.poznan.pl/pl/edukacja-i-turystyka/formy-zwiedzania?view=category&id=146"),
                 ("Wikipedia: Zamek w Kórniku", "https://pl.wikipedia.org/wiki/Zamek_w_K%C3%B3rniku")],
    ),
    dict(
        slug="arboretum-kornik", cat="wycieczki", name="Arboretum Kórnickie",
        img="arboretum-kornik", img_alt="Zielona polana i drzewa w Arboretum Kórnickim",
        short="Park z ok. 3500 gatunkami i odmianami drzew i krzewów, tuż obok zamku. Wiosną słynie z kwitnących magnolii.",
        badge="Codziennie",
        status=None,
        lead="Arboretum Kórnickie to najstarsze arboretum w Polsce. Na ponad 50 hektarach wokół zamku w Kórniku rośnie ok. 3500 gatunków i odmian drzew i krzewów, głównie z Azji i Ameryki Północnej. Należy do Instytutu Dendrologii Polskiej Akademii Nauk.",
        sections=[
            ("Historia", [
                "W XVIII wieku Teofila Szołdrska-Potulicka urządziła przy zamku ogród francuski. W 1826 roku Tytus Działyński zamienił go w romantyczny park, od którego liczy się historię arboretum. Kolekcję rozwijali jego syn Jan i wnuk Władysław Zamoyski, który przekazał dobra kórnickie Fundacji Zakłady Kórnickie.",
                "W 2026 roku arboretum obchodzi 200-lecie, a zamek 600-lecie.",
            ]),
            ("Co zobaczyć", [
                "Kilkusetletnie lipy, buki i dęby oraz ponad stuletnie egzotyczne magnolie, jodły greckie i cypryśniki błotne.",
                "Ścieżkę „Drzewa Świata” (3,5 km) z tablicami o 25 gatunkach drzew z Ameryki Północnej, Azji i Europy.",
                "Ścieżki edukacyjne, polanę piknikową i plac zabaw.",
            ]),
            ("Warto wiedzieć", [
                "Bilet kupuje się w kasie przed wejściem, kartą albo gotówką. Sprzedaż kończy się pół godziny przed zamknięciem. Zamek jest osobną instytucją z własnymi biletami.",
                "Na terenie arboretum nie ma gastronomii. Od maja do września działa bezpłatna toaleta, a przy wejściu jest płatna.",
                "Parking: płatny na podzamczu (tylko samochody osobowe) albo bezpłatny na Prowencie, 5 minut pieszo.",
            ]),
        ],
        address="ul. Zamkowa 5, 62-035 Kórnik",
        hours=[("Maj–czerwiec", "10:00–19:00"), ("Kwiecień, lipiec–wrzesień", "10:00–18:00"),
               ("Październik", "10:00–17:00"), ("Listopad–marzec", "10:00–16:00")],
        tickets=[("Normalny", "15 zł"), ("Ulgowy (uczniowie, studenci, emeryci)", "10 zł"),
                 ("Rodzinny (2 dorosłych i do 5 dzieci)", "40 zł"), ("Dzieci poniżej 5 lat", "bezpłatnie")],
        phone=None, www=("idpan.poznan.pl", "https://www.idpan.poznan.pl/pl/edukacja-i-turystyka/formy-zwiedzania?view=category&id=146"),
        credit="arboretum-kornik",
        trip=dict(lat=52.244167, lon=17.090833, getting=[
            ("Autobus", "Linie 501 i 560 oraz przewoźnicy podmiejscy, przystanek Kórnik/Pl. Niepodległości, 5 minut pieszo do wejścia."),
            ("Samochód", "Ok. kwadransa jazdy z Poznania drogą krajową nr 11."),
        ]),
        sources=[("Instytut Dendrologii PAN: Arboretum (cennik, dojazd)", "https://www.idpan.poznan.pl/pl/edukacja-i-turystyka/formy-zwiedzania?view=category&id=146"),
                 ("Instytut Dendrologii PAN: godziny otwarcia", "https://www.idpan.poznan.pl/pl/edukacja-i-turystyka/formy-zwiedzania?view=article&id=1551%3Agodziny-otwarcia&catid=147"),
                 ("Wikipedia: Arboretum w Kórniku", "https://pl.wikipedia.org/wiki/Arboretum_w_K%C3%B3rniku")],
    ),
    dict(
        slug="rogalin", cat="wycieczki", name="Pałac w Rogalinie",
        img="rogalin", img_alt="Barokowy pałac Raczyńskich w Rogalinie",
        short="Barokowy pałac Raczyńskich z galerią obrazów Matejki i Malczewskiego oraz parkiem ze słynnymi starymi dębami.",
        badge="Wt–nd",
        status=None,
        lead="Pałac w Rogalinie zbudował w latach 1770–1776 Kazimierz Raczyński. To jedna z najważniejszych polskich rezydencji z XVIII wieku, dziś oddział Muzeum Narodowego w Poznaniu. Pałac z parkiem i kościołem jest Pomnikiem Historii, a w 2020 roku status ten dostał cały dawny majątek, największy Pomnik Historii w Polsce.",
        sections=[
            ("Historia", [
                "Późnobarokowy pałac stoi między dziedzińcem a ogrodem, a z oficynami łączą go półkoliste galerie. Za pałacem jest ogród francuski.",
                "Edward Raczyński w latach 1817–1820 dodał park krajobrazowy i kościół św. Marcelina z mauzoleum rodu, wzorowany na rzymskiej świątyni Maison Carrée w Nîmes. W 1910 roku powstała galeria obrazów, przed wojną uważana za najlepszy zbiór malarstwa współczesnego na ziemiach polskich.",
                "Ostatni dziedzic, Edward Bernard Raczyński, był prezydentem RP na uchodźstwie. W 1990 roku założył Fundację im. Raczyńskich i przekazał jej pałac i park, którymi nadal opiekuje się Muzeum Narodowe.",
            ]),
            ("Co zobaczyć", [
                "Pałac z wnętrzami rodu Raczyńskich.",
                "Galerię malarstwa z ponad 250 obrazami z kolekcji Edwarda Aleksandra Raczyńskiego. Wisi tu największy obraz Jana Matejki, „Dziewica Orleańska”, oraz płótna Jacka Malczewskiego, Juliana Fałata, Olgi Boznańskiej i Leona Wyczółkowskiego.",
                "Gabinet londyński Edwarda Bernarda Raczyńskiego i galerię antenatów w północnym skrzydle oraz powozownię.",
                "Ogród i park z wielowiekowymi dębami. W dolinie Warty wokół Rogalina rośnie największe w Europie skupisko starych dębów szypułkowych.",
                "Kościół św. Marcelina z mauzoleum Raczyńskich, otwarty w soboty 13:00–17:00 i w niedziele 12:30–17:00.",
            ]),
            ("Warto wiedzieć", [
                "Dzienna pula biletów do pałacu jest ograniczona, więc w sezonie może ich zabraknąć. Muzeum radzi kupić bilet online w serwisie ToBilet.",
                "W każdy wtorek wstęp do muzeum, ogrodu i parku jest bezpłatny (darmowy bilet trzeba odebrać w kasie).",
                "Do ogrodu i parku wchodzi się tylko z dziedzińca, z biletem. Bilet na dowolną ekspozycję obejmuje wstęp do parku.",
                "Kasa jest czynna wt–nd 8:30–15:30, a w soboty i niedziele w lipcu i sierpniu 9:30–16:30. Przerwa w kasie: 12:30–12:45.",
            ]),
        ],
        address="ul. Arciszewskiego 2, 62-022 Rogalin",
        hours=[("Muzeum, wt–nd", "9:00–16:00"), ("Poniedziałek", "nieczynne"),
               ("Park, maj–sierpień", "9:00–20:00"), ("Park, marzec, kwiecień, wrzesień, październik", "9:00–18:00 (po zmianie czasu 9:00–17:30)"),
               ("Park, listopad–luty", "9:00–16:30")],
        tickets=[("Karnet na wszystkie ekspozycje", "45 zł, ulgowy 30 zł"), ("Pałac", "20 zł, ulgowy 13 zł"),
                 ("Galeria malarstwa", "20 zł, ulgowy 13 zł"), ("Gabinet londyński / powozownia", "po 8 zł, ulgowy 5 zł"),
                 ("Tylko ogród i park", "5 zł, ulgowy 2 zł"), ("Osoby w wieku 8–26 lat („Muzeum za 1 zł”)", "1 zł"), ("Wtorek", "bezpłatnie")],
        phone="+48 61 813 88 00", www=("mnp.art.pl", "https://mnp.art.pl/profile/wizyta-muzeum-palac-w-rogalinie"),
        credit="rogalin",
        trip=dict(lat=52.234581, lon=16.929689, getting=[
            ("Samochód", "Bezpłatny parking wzdłuż drogi nr 431 i za sklepem spożywczym przy ul. Poznańskiej. Przy alei kasztanowców jest parking płatny."),
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Muzeum Narodowe w Poznaniu: wizyta w Muzeum Pałacu w Rogalinie", "https://mnp.art.pl/profile/wizyta-muzeum-palac-w-rogalinie"),
                 ("MNP: cennik biletów Muzeum Pałacu w Rogalinie (PDF, 2026)", "https://mnp.art.pl/wp-content/uploads/2022/10/Plansza-Rogalin-cennik-i-regulamin_2026.pdf"),
                 ("MNP: bilet do ogrodu i parku w Rogalinie", "https://mnp.art.pl/muzeum-palac-w-rogalinie/bilet-do-ogrodu-i-parku-w-rogalinie"),
                 ("Wikipedia: Pałac w Rogalinie", "https://pl.wikipedia.org/wiki/Pa%C5%82ac_w_Rogalinie"),
                 ("Wikipedia: Rogaliński Park Krajobrazowy", "https://pl.wikipedia.org/wiki/Rogali%C5%84ski_Park_Krajobrazowy")],
    ),
    dict(
        slug="katedra-gniezno", cat="wycieczki", name="Katedra Gnieźnieńska i Drzwi Gnieźnieńskie",
        img="katedra-gniezno", img_alt="Gotycka katedra w Gnieźnie na Wzgórzu Lecha",
        short="Grób św. Wojciecha, miejsce pięciu koronacji królewskich i romańskie Drzwi Gnieźnieńskie z XII wieku.",
        badge="Pn–sb",
        status=None,
        lead="Gotycka katedra na Wzgórzu Lecha w Gnieźnie, pierwszej stolicy Polski, jest od 1000 roku główną świątynią metropolii gnieźnieńskiej. To miejsce pochówku św. Wojciecha, patrona Polski, i pięciu koronacji królewskich oraz siedziba prymasów Polski. Od 1994 roku jest Pomnikiem Historii.",
        sections=[
            ("Historia", [
                "Pierwszy kościół na wzgórzu powstał za Mieszka I, przed 992 rokiem. Jego relikty zachowały się w podziemiach katedry.",
                "W marcu 1000 roku do grobu św. Wojciecha przybył cesarz Otton III. Podczas zjazdu gnieźnieńskiego spotkał się z Bolesławem Chrobrym i utworzono wtedy pierwszą polską metropolię kościelną.",
                "Drzwi Gnieźnieńskie to romańskie drzwi z brązu, wykonane prawdopodobnie między 1175 a 1200 rokiem, za księcia Mieszka III Starego. Płaskorzeźby opowiadają życie i męczeństwo św. Wojciecha.",
            ]),
            ("Co zobaczyć", [
                "Drzwi Gnieźnieńskie. Wejście do nich jest z przewodnikiem w cenie biletu.",
                "Podziemia katedry z reliktami najstarszych kościołów, też z przewodnikiem w cenie biletu.",
                "Taras widokowy na wieży (od maja do października).",
                "Muzeum Archidiecezji Gnieźnieńskiej ze skarbcem katedralnym. Najcenniejszy zabytek to złoty kielich z X wieku, zwany kielichem św. Wojciecha.",
            ]),
            ("Warto wiedzieć", [
                "W niedziele katedra, muzeum i taras widokowy są niedostępne dla zwiedzających.",
                "Kasa zamyka się 30 minut przed zamknięciem obiektów. Karnet obejmuje Drzwi, podziemia, wieżę, muzeum i wnętrze katedry z audioprzewodnikiem.",
                "Ok. 700 m od katedry (w linii prostej) jest Muzeum Początków Państwa Polskiego. Oba miejsca łatwo zobaczyć jednego dnia.",
            ]),
        ],
        address="ul. Kolegiaty 2, 62-200 Gniezno",
        hours=[("Pn–sb, 1.05–31.10", "9:00–17:00"), ("Pn–sb, 1.11–30.04", "9:00–16:00 (taras widokowy nieczynny)"),
               ("Niedziela", "niedostępne dla zwiedzających")],
        tickets=[("Karnet na wszystko", "48 zł, ulgowy 42 zł"), ("Drzwi Gnieźnieńskie", "16 zł, ulgowy 14 zł"),
                 ("Podziemia", "14 zł, ulgowy 12 zł"), ("Taras widokowy", "12 zł, ulgowy 10 zł"),
                 ("Muzeum Archidiecezji", "18 zł, ulgowy 16 zł"), ("Karnet rodzinny", "138 zł")],
        phone="+48 602 708 231", www=("wzgorzelecha.pl", "https://wzgorzelecha.pl/cennik/"),
        credit="katedra-gniezno",
        trip=dict(lat=52.53681, lon=17.59258, getting=[
            ("Pociąg", "Gniezno ma bezpośrednie połączenia kolejowe z dworcem Poznań Główny."),
            ("Samochód", "Drogą ekspresową S5 z Poznania."),
        ]),
        sources=[("Wzgórze Lecha: cennik i godziny zwiedzania (od 1.01.2026)", "https://wzgorzelecha.pl/cennik/"),
                 ("Wzgórze Lecha: strona główna", "https://wzgorzelecha.pl/"),
                 ("Wikipedia: Bazylika Prymasowska w Gnieźnie", "https://pl.wikipedia.org/wiki/Bazylika_Prymasowska_Wniebowzi%C4%99cia_Naj%C5%9Bwi%C4%99tszej_Maryi_Panny_w_Gnie%C5%BAnie"),
                 ("Wikipedia: Drzwi Gnieźnieńskie", "https://pl.wikipedia.org/wiki/Drzwi_Gnie%C5%BAnie%C5%84skie")],
    ),
    dict(
        slug="mppp-gniezno", cat="wycieczki", name="Muzeum Początków Państwa Polskiego w Gnieźnie",
        img="mppp-gniezno", img_alt="Budynek Muzeum Początków Państwa Polskiego w Gnieźnie",
        short="Muzeum o narodzinach państwa Piastów w pierwszej stolicy Polski. W niedziele wstęp bezpłatny.",
        badge="Codziennie",
        status=None,
        lead="Muzeum w Gnieźnie opowiada o początkach państwa polskiego, wczesnym średniowieczu i historii miasta. Powstało w 1973 roku, a wystawę stałą w obecnym gmachu otwarto w 1983 roku. Zwiedzanie całego muzeum zajmuje ok. półtorej godziny.",
        sections=[
            ("O muzeum", [
                "Muzeum wyrosło z badań archeologicznych prowadzonych w Gnieźnie od 1948 roku. Gmach przy ulicy Kostrzewskiego zbudowano jako część kompleksu upamiętniającego Mieszka I i Bolesława Chrobrego.",
            ]),
            ("Wystawy", [
                "Wystawa główna „Początki państwa polskiego” o pierwszych Piastach i Polsce wczesnego średniowiecza.",
                "Pięć wystaw stałych: ceramika gnieźnieńska (jedna z największych kolekcji płytek i kafli piecowych w Europie), „Piastów malowane dzieje” z XIX-wiecznymi obrazami, „Gniezno. Stąd do przeszłości”, sztuka romańska w Polsce i motywy słowiańskie w sztuce.",
                "W 2026 roku wystawy czasowe: „Truso. Legenda Bałtyku” oraz „Re: Średniowiecze. 1000 lat 1000 wersji”.",
            ]),
            ("Warto wiedzieć", [
                "W niedziele wstęp jest bezpłatny. Bilety kupuje się w sklepie muzealnym, a sprzedaż kończy się kwadrans przed zamknięciem.",
                "Muzeum ma mobilnego przewodnika, a zwiedzać można także ze zwierzęciem.",
                "Naprzeciw muzeum jest bezpłatny parking, a przed wejściem stacja gnieźnieńskiego roweru miejskiego. Katedra jest ok. 700 m dalej.",
            ]),
        ],
        address="ul. Kostrzewskiego 1, 62-200 Gniezno",
        hours=[("Codziennie, maj–wrzesień", "9:00–18:00"), ("Codziennie, październik–kwiecień", "9:00–16:00")],
        tickets=[("Normalny", "20 zł"), ("Ulgowy", "16 zł"), ("Rodzinny (2+2)", "60 zł"),
                 ("Dzieci do 7 lat, osoby powyżej 70 lat", "bezpłatnie"), ("Niedziela", "bezpłatnie")],
        phone="+48 61 426 46 41", www=("muzeumgniezno.pl", "https://www.muzeumgniezno.pl/strona,12,zwiedzanie-i-cennik.html"),
        credit="mppp-gniezno",
        trip=dict(lat=52.533708, lon=17.583186, getting=[
            ("Pociąg", "Gniezno ma bezpośrednie połączenia kolejowe z dworcem Poznań Główny."),
            ("Samochód", "Z drogi S5 zjazd na węźle Gniezno-Południe. Bezpłatny parking naprzeciw muzeum."),
        ]),
        sources=[("MPPP: zwiedzanie i cennik", "https://www.muzeumgniezno.pl/strona,12,zwiedzanie-i-cennik.html"),
                 ("MPPP: dojazd i godziny otwarcia", "https://www.muzeumgniezno.pl/strona,11,dojazd-i-godziny-otwarcia.html"),
                 ("Wikipedia: Muzeum Początków Państwa Polskiego w Gnieźnie", "https://pl.wikipedia.org/wiki/Muzeum_Pocz%C4%85tk%C3%B3w_Pa%C5%84stwa_Polskiego_w_Gnie%C5%BAnie")],
    ),
    dict(
        slug="ostrow-lednicki", cat="wycieczki", name="Ostrów Lednicki",
        img="ostrow-lednicki", img_alt="Prom płynący na wyspę Ostrów Lednicki",
        short="Wyspa z ruinami pałacu Mieszka I, prawdopodobne miejsce chrztu Polski. Na wyspę płynie się promem.",
        badge="Wt–nd",
        status=("warning", "Wyspa jest otwarta dla zwiedzających od 12 kwietnia do 31 października 2026. Od listopada do początku kwietnia jest zamknięta."),
        lead="Ostrów Lednicki to największa z pięciu wysp na jeziorze Lednica, między Poznaniem a Gnieznem. Za Mieszka I i Bolesława Chrobrego był tu jeden z głównych grodów państwa. Zachowały się ruiny kamiennego pałacu z kaplicą i basenami do chrztu, dlatego wyspę uważa się za prawdopodobne miejsce chrztu Polski w 966 roku.",
        sections=[
            ("Historia", [
                "Tuż przed 966 rokiem Mieszko I wzniósł na wyspie kamienny pałac (palatium) połączony z kaplicą oraz osobny kościół. Pod koniec lat 80. XX wieku archeolodzy odsłonili w ruinach misy basenów chrzcielnych.",
                "Wyspę łączyły z lądem drewniane mosty na trakcie z Poznania do Gniezna. W 1038 roku gród zniszczył najazd czeskiego księcia Brzetysława I. Później otoczono go nowym wałem, który zachował się do dziś i ma do 9 metrów wysokości.",
                "Od 1969 roku działa tu Muzeum Pierwszych Piastów na Lednicy, a od 1994 roku wyspa jest Pomnikiem Historii. W tym miejscu toczy się akcja „Starej baśni” Józefa Ignacego Kraszewskiego.",
            ]),
            ("Co zobaczyć", [
                "Ruiny palatium z kaplicą i kościoła grodowego oraz wały dawnego grodu.",
                "Tuż obok, w Dziekanowicach, jest Wielkopolski Park Etnograficzny, czyli skansen z dawną wiejską zabudową. Należy do tego samego muzeum, ma te same godziny i osobne bilety.",
            ]),
            ("Warto wiedzieć", [
                "Na wyspę płynie się promem, który kursuje co pół godziny w godzinach otwarcia. Ostatni prom na wyspę odpływa 40 minut przed zamknięciem.",
                "Bilety sprzedawane są do 45 minut przed zamknięciem, a bilety z audioprzewodnikiem do godziny przed zamknięciem. Przerwy w kasie: wt–pt 12:30–12:50, w weekendy i święta 13:30–13:50.",
                "W środy wstęp jest bezpłatny. Parking jest bezpłatny.",
            ]),
        ],
        address="Dziekanowice 34, 62-261 Lednogóra",
        hours=[("Wt–pt, 12.04–31.10", "9:00–17:00"), ("Sb–nd i święta, 12.04–30.04 i 1.09–31.10", "10:00–17:00"),
               ("Sb–nd i święta, 1.05–31.08", "10:00–18:00"), ("Poniedziałek", "nieczynne"), ("1.11–11.04", "nieczynne")],
        tickets=[("Normalny", "25 zł (z audioprzewodnikiem 35 zł)"), ("Ulgowy", "17 zł (z audioprzewodnikiem 20 zł)"),
                 ("Dzieci do 7 lat", "bezpłatnie"), ("Środa", "bezpłatnie")],
        phone="+48 61 427 50 10", www=("lednicamuzeum.pl", "https://lednicamuzeum.pl/strona,godziny-otwarcia.html"),
        credit="ostrow-lednicki",
        trip=dict(lat=52.527222, lon=17.377778, getting=[
            ("Samochód", "Parking przy muzeum jest bezpłatny."),
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Muzeum Pierwszych Piastów na Lednicy: godziny otwarcia i ceny biletów 2026", "https://lednicamuzeum.pl/strona,godziny-otwarcia.html"),
                 ("Muzeum Pierwszych Piastów na Lednicy: kontakt", "https://lednicamuzeum.pl/strona,kontakt.html"),
                 ("Wikipedia: Ostrów Lednicki", "https://pl.wikipedia.org/wiki/Ostr%C3%B3w_Lednicki"),
                 ("Wikipedia: Muzeum Pierwszych Piastów na Lednicy", "https://pl.wikipedia.org/wiki/Muzeum_Pierwszych_Piast%C3%B3w_na_Lednicy")],
    ),
    dict(
        slug="biskupin", cat="wycieczki", name="Rezerwat archeologiczny w Biskupinie",
        img="biskupin", img_alt="Zrekonstruowana brama i wał osady w Biskupinie",
        short="Osada obronna sprzed ponad 2700 lat z odtworzonym wałem, bramą i drewnianymi domami nad jeziorem.",
        badge="Codziennie",
        status=None,
        lead="Biskupin to jedno z najsłynniejszych stanowisk archeologicznych w Europie. Na półwyspie Jeziora Biskupińskiego stała osada obronna z wczesnej epoki żelaza. Drewno na jej budowę ścięto w 748 roku p.n.e., kilkanaście stuleci przed pierwszymi grodami Piastów. Muzeum leży w województwie kujawsko-pomorskim, to najdalsza z wycieczek w przewodniku.",
        sections=[
            ("Odkrycie", [
                "W 1933 roku, po obniżeniu poziomu wody w jeziorze, z wody wyłoniły się drewniane pale. Nauczyciel Walenty Szwajcer powiadomił o nich profesora Józefa Kostrzewskiego z Poznania. Wykopaliska ruszyły w 1934 roku i były prowadzone na najwyższym ówczesnym poziomie naukowym.",
            ]),
            ("Osada", [
                "Gród stał na podmokłej wyspie. Miał 11 równoległych ulic wyłożonych drewnem, ulicę okrężną i potężny wał. Mieściło się w nim ok. 106 domów, w których mogło mieszkać 800–1000 osób.",
                "Dziś oglądać można pełnowymiarowe rekonstrukcje wału, falochronu, bramy, ulic i domów oraz pawilon muzealny z wystawami. W Biskupinie kręcono sceny do filmów „Ogniem i mieczem” i „Stara baśń”.",
            ]),
            ("Warto wiedzieć", [
                "Od maja do września w rezerwacie pracują edukatorzy i odtwórcy dawnego rękodzieła. W Biskupinie nie ma bankomatu, więc na wyroby rzemieślników warto mieć gotówkę. Bilety w kasie można kupić kartą.",
                "We wrześniu odbywa się Festyn Archeologiczny, pierwszy taki festyn w Polsce. W czasie festynu obowiązują inne ceny biletów.",
                "Pies może wejść na teren rezerwatu na smyczy i w kagańcu, ale nie do pawilonu i budynków. Parking jest bezpłatny.",
            ]),
        ],
        address="Biskupin 3, 88-410 Gąsawa",
        hours=[("Maj–wrzesień", "9:00–18:00"), ("Kwiecień, październik", "9:00–17:00"), ("Listopad–marzec", "9:00–16:00"),
               ("Nieczynne", "1.01, Niedziela Wielkanocna, 1.11, 25.12")],
        tickets=[("Normalny", "28 zł"), ("Ulgowy (uczniowie, studenci, emeryci)", "19 zł"), ("Rodzinny (2+2)", "75 zł"),
                 ("Dzieci do 7 lat", "bezpłatnie")],
        phone="+48 453 071 403", www=("biskupin.pl", "https://biskupin.pl/zwiedzanie/"),
        credit="biskupin",
        trip=dict(lat=52.788333, lon=17.744444, getting=[
            ("Samochód", "Najwygodniej samochodem. Parking muzealny jest bezpłatny."),
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Muzeum Archeologiczne w Biskupinie: zwiedzanie (godziny, ceny)", "https://biskupin.pl/zwiedzanie/"),
                 ("Muzeum Archeologiczne w Biskupinie: kontakt", "https://biskupin.pl/kontakt/"),
                 ("Wikipedia: Gród w Biskupinie", "https://pl.wikipedia.org/wiki/Biskupin")],
    ),
    dict(
        slug="wpn", cat="wycieczki", name="Wielkopolski Park Narodowy",
        img="wpn", img_alt="Jezioro Góreckie w Wielkopolskim Parku Narodowym",
        short="Lasy, jeziora i polodowcowe wzgórza tuż za Poznaniem, z ruinami zameczku na wyspie Jeziora Góreckiego. Wstęp bezpłatny.",
        badge="Bezpłatnie",
        status=None,
        lead="Wielkopolski Park Narodowy powstał 16 kwietnia 1957 roku na południe od Poznania, między Luboniem, Stęszewem a Mosiną. Ma ok. 7584 hektarów (75,84 km²). Jego inicjator, prof. Adam Wodziczko, nazwał ten teren muzeum form polodowcowych i żywym muzeum przyrody.",
        sections=[
            ("Przyroda", [
                "Park chroni krajobraz ukształtowany przez lądolód: moreny, ozy, wydmy i jeziora rynnowe. Oz Bukowsko-Mosiński ma 37 km długości, najwięcej w Polsce. W 18 obszarach ochrony ścisłej przyroda rozwija się bez ingerencji człowieka.",
            ]),
            ("Co zobaczyć", [
                "Jezioro Góreckie z Wyspą Zamkową. Stoją na niej ruiny zameczku, który Tytus Działyński zbudował w latach 1824–1825 dla siostry, Klaudyny Potockiej.",
                "Osową Górę, najwyższe wzniesienie parku, i ścieżkę edukacyjną „Osowa Góra – Jeziory” (5,5 km, ok. 3 godziny w jedną stronę).",
                "Głaz Leśników przy parkingu na węźle Komorniki–Jeziory: głaz narzutowy o wysokości 4 m i masie ok. 20 ton, jeden z największych w okolicach Poznania.",
                "Muzeum Przyrodnicze w Jeziorach, przy siedzibie parku.",
            ]),
            ("Warto wiedzieć", [
                "Za wejście na teren parku nie pobiera się opłat. Płatne jest tylko Muzeum Przyrodnicze.",
                "W parku jest 9 parkingów. Osiem jest płatnych (parkometr lub aplikacja), a bezpłatny jest parking przy Trzcielińskim Bagnie.",
            ]),
        ],
        address="Jeziory, 62-050 Mosina (siedziba parku i Muzeum Przyrodnicze)",
        hours=[("Teren parku", "bez biletów"), ("Muzeum Przyrodnicze, pn–pt", "8:00–14:00"),
               ("Muzeum, niedziele 1.04–30.09", "11:00–18:00"), ("Muzeum, soboty i niedziele zimą", "nieczynne")],
        tickets=[("Wstęp do parku", "bezpłatnie"), ("Muzeum Przyrodnicze", "10 zł, ulgowy 5 zł")],
        phone=None, www=("wpn.gov.pl", "https://wpn.gov.pl/"),
        credit="wpn",
        trip=dict(lat=52.26984, lon=16.79714, getting=[
            ("Pociąg", "Najbliżej siedziby parku jest stacja Puszczykówko na linii Poznań–Wrocław. Z dworca idzie się ulicą Dworcową w stronę Jezior."),
            ("Samochód", "Do Jezior drogą powiatową nr 2495 (Komorniki – Jeziory – Puszczykowo)."),
        ]),
        sources=[("WPN: informacje o biletach (wstęp bezpłatny)", "https://wpn.gov.pl/informacje-o-biletach"),
                 ("WPN: Muzeum Przyrodnicze (godziny, ceny)", "https://wpn.gov.pl/muzeum-przyrodnicze-wpn"),
                 ("WPN: dojazd do siedziby", "https://wpn.gov.pl/dojazd"),
                 ("WPN: atrakcje turystyczne", "https://wpn.gov.pl/atrakcje-turystyczne"),
                 ("WPN: ścieżki edukacyjne", "https://wpn.gov.pl/sciezki-edukacyjne"),
                 ("WPN: parkingi", "https://wpn.gov.pl/parkingi"),
                 ("Wikipedia: Wielkopolski Park Narodowy", "https://pl.wikipedia.org/wiki/Wielkopolski_Park_Narodowy")],
    ),
    dict(
        slug="szreniawa", cat="wycieczki", name="Muzeum Rolnictwa w Szreniawie",
        img="szreniawa", img_alt="Dawne maszyny rolnicze przed pawilonami muzeum w Szreniawie",
        short="Narodowe muzeum dawnej wsi: maszyny, pałac i zwierzęta w oborze. W soboty wstęp bezpłatny.",
        badge="Wt–nd",
        status=("warning", "Wieża-mauzoleum Bierbaumów (punkt widokowy) jest nieczynna z powodu remontu od 14 lipca 2026. Od 1 grudnia do 15 lutego muzeum przyjmuje tylko zgłoszone wcześniej grupy."),
        lead="Muzeum Narodowe Rolnictwa i Przemysłu Rolno-Spożywczego w Szreniawie powstało w 1964 roku, a status muzeum narodowego ma od 1975 roku. Zgromadziło ponad 20 tysięcy obiektów o dziejach polskiej wsi i rolnictwa. To jedyne muzeum rolnictwa tej rangi w Polsce.",
        sections=[
            ("Co zobaczyć", [
                "Pawilony z ekspozycjami o dawnym rolnictwie, maszynach i przetwórstwie żywności.",
                "Pałac z ekspozycją oraz oborę ze zwierzętami.",
            ]),
            ("Warto wiedzieć", [
                "W soboty wstęp jest bezpłatny, z wyjątkiem dni biletowanych imprez.",
                "Bilet spacerowy (7 zł) pozwala wejść na teren muzeum, ale nie do pawilonów, pałacu i obory. Nie jest sprzedawany w dni festynów.",
                "Muzeum jest partnerem Poznańskiej Karty Turystycznej. W kasie można płacić kartą, a ostatnie wejście jest pół godziny przed zamknięciem.",
            ]),
        ],
        address="ul. Dworcowa 5, 62-052 Komorniki",
        hours=[("Wt–pt, 1.04–26.10", "9:00–17:00"), ("Sb–nd, 1.04–26.10", "10:00–18:00"),
               ("Wt–nd, 28.10–30.11 i 16.02–31.03", "9:00–15:00"), ("1.12–15.02", "tylko zgłoszone grupy"),
               ("Poniedziałek", "nieczynne")],
        tickets=[("Normalny", "25 zł"), ("Ulgowy", "20 zł"), ("Rodzinny (2 dorosłych + dzieci)", "50 zł"),
                 ("Spacerowy (bez ekspozycji)", "7 zł"), ("Dzieci do 7 lat", "bezpłatnie"), ("Sobota", "bezpłatnie, poza dniami imprez biletowanych")], checked="01.10.2026",
        phone="+48 61 810 76 29", www=("muzeum-szreniawa.pl", "https://muzeum-szreniawa.pl/bilety/"),
        credit="szreniawa",
        trip=dict(lat=52.31613, lon=16.79779, getting=[
            ("Samochód", "Szreniawa leży przy granicy Wielkopolskiego Parku Narodowego. Muzeum łatwo połączyć ze spacerem po parku."),
            ("Komunikacja", "Połączenie z Poznania sprawdź w wyszukiwarce tras (link powyżej)."),
        ]),
        sources=[("Muzeum w Szreniawie: godziny otwarcia", "https://muzeum-szreniawa.pl/godziny-otwarcia/"),
                 ("Muzeum w Szreniawie: bilety", "https://muzeum-szreniawa.pl/bilety/"),
                 ("Muzeum w Szreniawie: kontakt", "https://muzeum-szreniawa.pl/kontakt/"),
                 ("Wikipedia: Muzeum Narodowe Rolnictwa w Szreniawie", "https://pl.wikipedia.org/wiki/Muzeum_Narodowe_Rolnictwa_i_Przemys%C5%82u_Rolno-Spo%C5%BCywczego_w_Szreniawie")],
    ),
    dict(
        slug="fiedler", cat="wycieczki", name="Muzeum Arkadego Fiedlera w Puszczykowie",
        img="fiedler", img_alt="Kopia karaweli Santa Maria w ogrodzie Muzeum Arkadego Fiedlera",
        short="Dom pisarza-podróżnika z pamiątkami z wypraw, kopią karaweli Santa Maria i ogrodem z replikami posągów z całego świata.",
        badge="Wt–nd",
        status=None,
        lead="Arkady Fiedler (1894–1985) był pisarzem i podróżnikiem, autorem m.in. „Dywizjonu 303”. Muzeum działa od 1 stycznia 1974 roku w jego rodzinnej willi w Puszczykowie, którą kupił w 1946 roku po powrocie z emigracji. Do końca 2000 roku odwiedziło je ponad milion osób.",
        sections=[
            ("Co zobaczyć", [
                "Pamiątki z wypraw Fiedlera: maski i rzeźby obrzędowe, łuki i dmuchawki, tropikalne motyle, pająki i skorpiony, a także pamiątki z II wojny światowej i Dywizjonu 303.",
                "Ekspozycję „Tajemniczy Świat Indian”, otwartą w 2003 roku w osobnym budynku.",
                "Ogród Tolerancji wokół willi z modelami rzeźb i budowli ważnych dla różnych cywilizacji, m.in. 6,5-metrowym posągiem Buddy z Bamian, Bramą Słońca z Tiahuanaco i głową olmecką z Meksyku.",
                "Kopię karaweli Santa Maria w ogrodzie.",
            ]),
            ("Warto wiedzieć", [
                "Od 1991 roku muzeum utrzymuje się samo, bez dotacji miasta.",
                "Najbliższa stacja kolejowa, Puszczykówko, jest 400 m od muzeum. Blisko jest też Wielkopolski Park Narodowy.",
            ]),
        ],
        address="ul. Słowackiego 1, 62-040 Puszczykowo",
        hours=[("Wt–nd, wiosna i lato", "9:00–16:00"), ("Wt–nd, jesień i zima", "10:00–15:00"), ("Poniedziałek", "nieczynne")],
        tickets=[("Normalny", "18 zł"), ("Ulgowy", "16 zł"), ("Przewodnik po muzeum", "150 zł")],
        phone=None, www=("fiedler.pl", "http://www.fiedler.pl/"),
        credit="fiedler",
        trip=dict(lat=52.275556, lon=16.8675, getting=[
            ("Pociąg", "Stacja Puszczykówko, 400 m od muzeum."),
        ]),
        sources=[("Muzeum Arkadego Fiedlera: ceny biletów", "http://www.fiedler.pl/sub,pl,ceny-biletow.html"),
                 ("Muzeum Arkadego Fiedlera: godziny otwarcia", "http://www.fiedler.pl/sub,pl,godziny-otwarcia.html"),
                 ("Wikipedia: Muzeum – Pracownia Literacka Arkadego Fiedlera", "https://pl.wikipedia.org/wiki/Muzeum_%E2%80%93_Pracownia_Literacka_Arkadego_Fiedlera_w_Puszczykowie")],
    ),
]
