# -*- coding: utf-8 -*-
"""Zabytkowe kościoły Poznania (partia 4, 29.09.2026).
Źródło opisów: portal miasta poznan.pl, kategoria „Kościoły zabytkowe”
(opisy streszczone własnymi słowami). Katedra, Fara, NMP in Summo i kościół
św. Wojciecha mają osobne wpisy w innych plikach."""

POI = "https://www.poznan.pl/mim/wortals/wortal,2024/koscioly-zabytkowe,poi,2471/-,{}.html"


def church(slug, name, poi_id, address, short, lead, history, see, img_alt,
           extra=None, phone=None, www=None, badge="Wstęp wolny"):
    """Wpis kościoła: wstęp wolny, zwiedzanie poza nabożeństwami, źródło z poznan.pl."""
    sections = [("Historia", history), ("Co zobaczyć", see)]
    sections.append(("Warto wiedzieć", (extra or []) + [
        "To czynny kościół. Nie zwiedza się go w czasie mszy i nabożeństw, obowiązuje stosowny strój i cisza.",
    ]))
    src = POI.format(poi_id)
    return dict(
        slug=slug, cat="koscioly", name=name, img=slug, img_alt=img_alt,
        short=short, badge=badge, status=None, lead=lead, sections=sections,
        address=address,
        hours=[("Zwiedzanie", "poza nabożeństwami"), ("Godziny mszy", "w ogłoszeniach parafii")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=phone, www=www or ("poznan.pl", src), credit=slug,
        sources=[("poznan.pl: " + name, src)],
    )


CHURCHES = [
    church(
        "kosciol-sw-antoniego", "Kościół św. Antoniego z Padwy (Franciszkanów)", 39371,
        "ul. Franciszkańska 2, 61-768 Poznań",
        "Barokowy kościół franciszkanów na Wzgórzu Przemysła, z malowidłami braci Swachów.",
        "Kościół franciszkanów konwentualnych stoi na Wzgórzu Przemysła, obok Zamku Królewskiego. Budowano go w latach 1674–1757. Wnętrze należy do najbogatszych barokowych wnętrz w mieście.",
        ["Franciszkanie osiedlili się w Poznaniu w XVII wieku. Klasztor powstał w latach 1672–1749, ale po kasacie w 1834 roku częściowo go rozebrano.",
         "W XIX wieku władze pruskie przekazały kościół katolikom niemieckim. Franciszkanie wrócili tu w 1921 roku. Po zniszczeniach wojennych kościół odbudowano w 1945 roku."],
        ["Stiuki i polichromię z około 1702 roku, dzieło franciszkanina Adama Swacha, ze scenami z życia św. Antoniego, św. Franciszka i Matki Bożej.",
         "Ołtarz główny z około 1690 roku, dzieło Antoniego Swacha, z obrazem „Wizja św. Antoniego” jego brata Adama.",
         "Rzeźbione i intarsjowane stalle z początku XVIII wieku.",
         "Kaplicę Matki Bożej z obrazem czczonym jako Matka Boża w Cudy Wielmożna, Pani Poznania."],
        "Barokowy kościół św. Antoniego z Padwy",
        extra=["W podziemiach kościoła, z wejściem od ulicy Ludgardy, działają Makiety Dawnego Poznania."]),
    church(
        "kosciol-bozego-ciala", "Kościół Bożego Ciała", 39372,
        "ul. Strzelecka 40, 61-846 Poznań",
        "Gotycki kościół ufundowany przez Władysława Jagiełłę w miejscu związanym z cudem hostii.",
        "Kościół stoi w miejscu związanym z tradycją cudownego odnalezienia hostii w 1399 roku. W 1406 roku król Władysław Jagiełło ufundował tu kościół i klasztor karmelitów.",
        ["Murowany kościół ukończono na przełomie XV i XVI wieku. Około 1570 roku dobudowano kaplicę, którą około 1726 roku przebudował Pompeo Ferrari.",
         "Zniszczony w czasie potopu szwedzkiego, do 1664 roku został odbudowany w stylu barokowym. Po kasacie zakonu w 1823 roku podupadał, uratował go remont z 1856 roku. Od 1899 roku jest kościołem parafialnym."],
        ["Trójnawowe gotyckie wnętrze z gwiaździstymi sklepieniami z XV wieku w nawach bocznych i malowidłami z XVII wieku w nawie głównej.",
         "Ołtarz główny z około 1740 roku z obrazem „Ostatnia Wieczerza”.",
         "Portrety króla Władysława Jagiełły i św. Jadwigi w prezbiterium oraz tablice herbowe wielkopolskiej szlachty.",
         "Kaplicę Matki Boskiej Szkaplerznej i barokowy chór z XVII wieku."],
        "Gotycki kościół Bożego Ciała",
        extra=["Z tą samą tradycją z 1399 roku wiąże się pobliski kościół Najświętszej Krwi Pana Jezusa przy ulicy Żydowskiej."]),
    church(
        "kosciol-bernardynow", "Kościół św. Franciszka Serafickiego (Bernardynów)", 40378,
        "ul. Garbary 22, 61-867 Poznań",
        "Barokowy kościół bernardynów z wysokimi hełmami wież i rzeźbami świętych na fasadzie.",
        "Kościół nazywany jest kościołem bernardynów, bo w 1456 roku założyli tu klasztor franciszkanie obserwanci, zwani od Bernardyna ze Sieny bernardynami. Obecny barokowy kościół zbudowano w latach 1661–1668.",
        ["Gotycki kościół z lat 1471–1473 spalili Szwedzi w 1655 roku. Nowy zaprojektowali Krzysztof Bonadura Starszy i Jerzy Catenazzi.",
         "W latach 1730–1738 przebudowano fasadę i dodano wysokie hełmy wież według projektu Jana Adama Stiera z Leszna.",
         "Po kasacie zakonu w 1835 roku kościół służył różnym instytucjom. Zniszczony w czasie II wojny światowej, odbudowywany był do 1988 roku. Od 1974 roku jest kościołem parafialnym."],
        ["Fasadę z rzeźbami świętych franciszkańskich we wnękach, dzieło Franciszka Domusbergera ze Wschowy.",
         "Posadzkę położoną wysoko nad poziomem ulicy, bo pod nią znajdowała się krypta klasztorna.",
         "Kaplicę Matki Boskiej Loretańskiej i ołtarz główny z kopią obrazu Rubensa „Gniew Boży” z 1950 roku."],
        "Fasada kościoła Bernardynów przy ulicy Garbary"),
    church(
        "kosciol-jana-jerozolimskiego", "Kościół św. Jana Jerozolimskiego za Murami", 40379,
        "ul. Świętojańska 1, 61-113 Poznań",
        "Romański kościół joannitów z przełomu XII i XIII wieku, jeden z pierwszych ceglanych w Polsce.",
        "To druga po katedrze najstarsza zachowana świątynia w Poznaniu i jeden z pierwszych kościołów w Polsce zbudowanych z cegły. Wznieśli go na przełomie XII i XIII wieku joannici, sprowadzeni przez księcia Mieszka Starego.",
        ["Patronem jest św. Jan Chrzciciel, nazywany tu Jerozolimskim od szpitala, którym joannici opiekowali się w Jerozolimie. Przydomek „za Murami” oznacza, że kościół stał poza dawnym grodem.",
         "Na przełomie XV i XVI wieku kościół przebudowano w stylu późnogotyckim, dobudowując zakrystię, nawę północną i wieżę-dzwonnicę. W 1736 roku dodano barokową kaplicę Świętego Krzyża."],
        ["Gwiaździste sklepienia i polichromię Stanisława Teisseyre'a z 1948 roku.",
         "Gotycki tryptyk z początku XVI wieku w ołtarzu głównym i kamienną chrzcielnicę z 1522 roku.",
         "Kaplicę Świętego Krzyża z gotycką kratą z XV wieku i czczonym krucyfiksem z połowy XVII wieku. W jej podziemiach spoczywają komandorzy joannitów."],
        "Romański kościół św. Jana Jerozolimskiego za Murami"),
    church(
        "kosciol-sw-jozefa", "Kościół św. Józefa (Karmelitów Bosych)", 40380,
        "ul. Działowa 25, 61-747 Poznań",
        "Barokowy kościół karmelitów bosych, gdzie spoczywa pierwowzór Jana Skrzetuskiego z „Ogniem i mieczem”.",
        "Barokowy kościół zbudowano w latach 1644–1678 według projektu Krzysztofa Bonadury Starszego i Jerzego Catenazziego. Od odbudowy po 1945 roku opiekują się nim karmelici bosi.",
        ["Po kasacie klasztoru Prusacy oddali kościół wojsku. Po 1840 roku wnętrze przebudowano według Karla Friedricha Schinkla na ewangelicki kościół garnizonowy.",
         "Po odzyskaniu niepodległości był katolickim kościołem garnizonowym. Klasztor po zniszczeniach wojennych odbudowywano do 1966 roku."],
        ["Trójnawowe wnętrze z wyposażeniem z lat 1984–1988 i obrazami Alberta Tschautscha z 1878 roku w transepcie.",
         "W kruchcie fragment nagrobka dobroczyńcy konwentu Wojciecha Konarzewskiego i tablicę upamiętniającą Mikołaja Skrzetuskiego, pierwowzór Jana Skrzetuskiego z „Ogniem i mieczem” Sienkiewicza, pochowanego w podziemiach.",
         "Samotnię św. Rafała Kalinowskiego w podziemiach, urządzoną w 1987 roku, i jego pomnik przed kościołem."],
        "Barokowa fasada kościoła Karmelitów Bosych"),
    church(
        "kosciol-sw-malgorzaty", "Kościół św. Małgorzaty na Śródce", 40381,
        "ul. Filipińska, 61-114 Poznań",
        "Gotycki kościół z XIV wieku przy Rynku Śródeckim, tuż obok muralu.",
        "Pierwszy kościół na Śródce powstał zapewne przed 1231 rokiem. Obecną świątynię wzniesiono w XIV wieku. W latach 1671–1805 należała do filipinów.",
        ["W XV wieku dobudowano kaplicę św. Barbary, a około 1652 roku kaplicę św. Filipa Nereusza.",
         "Spalony w czasie potopu szwedzkiego kościół odbudowano w 1658 roku i wtedy stracił częściowo średniowieczny charakter."],
        ["Jednonawowe wnętrze z późnogotyckim sklepieniem gwiaździstym.",
         "Ołtarz główny z wizerunkiem Matki Boskiej w srebrnej sukience z końca XVII wieku.",
         "Obraz Matki Bożej z Dzieciątkiem na półksiężycu z początku XVII wieku oraz obraz z muzykującymi aniołami z około 1603 roku w kaplicy św. Barbary.",
         "Dawny dom Kongregacji Filipinów z lat 1746–1777 obok kościoła."],
        "Kościół św. Małgorzaty na Śródce",
        extra=["Kościół stoi na Śródce, kilka kroków od trójwymiarowego muralu i Bramy Poznania."]),
    church(
        "kosciol-sw-marcina", "Kościół św. Marcina", 40382,
        "ul. Święty Marcin 13, 61-803 Poznań",
        "Gotycki kościół patrona ulicy Święty Marcin, z polichromią Taranczewskiego i tryptykiem z 1498 roku.",
        "Parafię św. Marcina utworzono przed 1236 rokiem. Obecny trójnawowy kościół gotycki budowano od XIV do połowy XVI wieku. Po zniszczeniach 1945 roku odbudowa z lat 1949–1954 przywróciła mu późnogotycki wygląd.",
        ["Kościół spaliły wojska brandenburskie w 1657 roku, a przy odbudowie wnętrze dostało barokowy wystrój. Obecną wieżę zbudowano w latach 1925–1929.",
         "Obok kościoła w 1859 roku odsłonięto pierwszy na ziemiach polskich pomnik Adama Mickiewicza, który stał do 1940 roku. Upamiętnia go cokół z 1957 roku."],
        ["Polichromię malowaną na cegle przez Wacława Taranczewskiego w 1957 roku i witraże Jana Piaseckiego z 1959 roku ze scenami z życia św. Marcina.",
         "Późnogotycki tryptyk z 1498 roku w ołtarzu głównym.",
         "Płaskorzeźbę św. Marcina z 1953 roku w tympanonie portalu, dzieło Edwarda Haupta.",
         "Tablicę upamiętniającą ks. Piotra Wawrzyniaka i grotę Matki Boskiej z Lourdes z 1911 roku."],
        "Gotycki kościół św. Marcina",
        extra=["11 listopada ulica Święty Marcin obchodzi swoje imieniny."]),
    church(
        "kosciol-dominikanow", "Kościół Dominikanów (NSPJ i MB Pocieszenia)", 40383,
        "ul. Szewska 18, 61-760 Poznań",
        "Kościół dominikanów z 1244 roku z sanktuarium Matki Boskiej Różańcowej.",
        "Pierwszy kościół dominikanów ufundowali w 1244 roku książęta wielkopolscy Przemysł I i Bolesław Pobożny. Obecny kształt świątynia dostała na początku XVIII wieku według projektu Jana Catenazziego. Jest sanktuarium Matki Boskiej Różańcowej.",
        ["Zachowały się częściowo wczesnogotyckie mury z XIII wieku z portalem w fasadzie zachodniej, odsłoniętym w 1923 roku.",
         "Kaplica Matki Boskiej Różańcowej z XV wieku stoi prawdopodobnie w miejscu dawnego kościoła św. Gotarda. Obecny kształt dostała w latach 1900–1901."],
        ["Barokowe wyposażenie z XVIII wieku, w tym ołtarz główny z 1760 roku z obrazem Matki Boskiej Różańcowej ze św. Dominikiem.",
         "Manierystyczne stalle z lat 1620–1630 ze scenami z życia św. Dominika i św. Jacka oraz barokową ambonę z lat 1714–1716.",
         "W kaplicy Matki Boskiej Różańcowej czczony obraz Matki Bożej z Dzieciątkiem z 1631 roku, koronowany w 1968 roku, oraz gotycką płytę nagrobną z brązu z norymberskiego warsztatu Vischerów."],
        "Kościół Dominikanów przy ulicy Szewskiej"),
    church(
        "kosciol-zbawiciela", "Kościół Najświętszego Zbawiciela", 40384,
        "ul. Fredry 11, 61-701 Poznań",
        "Neogotycki kościół ze strzelistą wieżą, zbudowany w latach 1866–1869 dla ewangelików.",
        "Neogotycki kościół zbudowano w latach 1866–1869 według projektu Augusta Stülera i Juliusza Hochbergera dla ewangelickiej parafii św. Pawła. Katolicki jest od 1945 roku.",
        ["Katolicką parafię utworzono tu w 1950 roku."],
        ["Strzelistą wieżę i tondo z rzeźbą głowy Chrystusa nad głównym portalem.",
         "Trójnawowe wnętrze ze sklepieniami gwiaździstymi i krzyżowymi oraz zachowanymi drewnianymi emporami.",
         "Rzeźbę Pasji Lecha Czuby z 2000 roku, neogotycką chrzcielnicę z lat 1867–1869 i organy z 1912 roku."],
        "Neogotycki kościół Najświętszego Zbawiciela"),
    church(
        "kosciol-najsw-krwi", "Kościół Najświętszej Krwi Pana Jezusa", 40385,
        "ul. Żydowska 34, 61-761 Poznań",
        "Kościół w dawnej kamienicy związanej z tradycją cudu trzech hostii z 1399 roku.",
        "Kościół stoi w miejscu kamienicy, z którą wiąże się tradycja tzw. cudu trzech hostii z 1399 roku. W XVII wieku karmelici przebudowali ją na kościół, wykorzystując gotyckie mury i piwnicę ze studzienką.",
        ["Obecny wygląd budynek zyskał na początku XX wieku. Na fasadzie widać fragmenty dawnych murów."],
        ["Rzeźbę Matki Bożej z Dzieciątkiem z przełomu XV i XVI wieku nad wejściem, przeniesioną ze Starego Rynku.",
         "Późnobarokowe wnętrze z ołtarzem głównym z 1733 roku i malowidłami na sklepieniu z 1735 roku.",
         "Rzeźbę „Opłakiwanie Chrystusa” z początku XVI wieku.",
         "Kaplicę w podziemiach ze studzienką. Według przekazów jej woda pomagała zwłaszcza na choroby oczu."],
        "Kościół Najświętszej Krwi Pana Jezusa przy ulicy Żydowskiej",
        extra=["Z tą samą tradycją wiąże się kościół Bożego Ciała przy ulicy Strzeleckiej."]),
    church(
        "kosciol-wspomozenia-wiernych", "Kościół NMP Wspomożenia Wiernych (Salezjanów)", 40387,
        "ul. Wroniecka 9, 61-763 Poznań",
        "Gotycki kościół dawnych dominikanek, upamiętniający męczenników z Poznańskiej Piątki.",
        "Kościół i klasztor dominikanek powstały w latach 80. XIII wieku. Po kasacie klasztoru przez Prusaków w 1822 roku kościół niszczał. W 1926 roku odbudowali go i przywrócili mu funkcję salezjanie.",
        ["Najpierw powstało prezbiterium, w XIV wieku nawa, a w XVI wieku nawa boczna.",
         "Przy odbudowie dodano neobarokową fasadę według projektu Lucjana Michałowskiego."],
        ["Sklepienie żebrowe z około 1440 roku w prezbiterium, jedyne takie w Poznaniu.",
         "Ołtarz główny z 1928 roku z obrazem Matki Boskiej Wspomożenia Wiernych.",
         "Ołtarz z portretami Poznańskiej Piątki: Czesława Jóźwiaka, Edwarda Kaźmierskiego, Franciszka Kęsego, Edwarda Klinika i Jarogniewa Wojciechowskiego. To chłopcy z salezjańskiego oratorium, działający w konspiracji i zamordowani przez Niemców. W 1999 roku beatyfikował ich Jan Paweł II.",
         "Basztę w XIII-wiecznym murze obronnym miasta, zachowaną z dawnych zabudowań klasztornych."],
        "Kościół NMP Wspomożenia Wiernych przy ulicy Wronieckiej",
        extra=["Kościół stoi przy ulicy Wronieckiej, gdzie zachowały się też fragmenty średniowiecznych murów miejskich."]),
    church(
        "kosciol-wszystkich-swietych", "Kościół Wszystkich Świętych", 40389,
        "ul. Grobla 1, 61-858 Poznań",
        "Dawny ewangelicki kościół z lat 1777–1787 z eliptyczną kopułą i monogramem Stanisława Augusta.",
        "Kościół zbudowano w latach 1777–1787 według projektu Antoniego Höhnego jako ewangelicką świątynię św. Krzyża. Od 1945 roku jest kościołem katolickim, a od 1981 roku parafialnym.",
        ["Wyposażenie wnętrza wykonał w latach 1785–1787 Augustyn Schöps."],
        ["Późnobarokowo-klasycystyczną budowlę z eliptyczną pseudokopułą wspartą na ośmiu filarach i dwupoziomowymi emporami.",
         "Figury św. Piotra i św. Pawła z 1788 roku nad wejściem oraz rzeźbę Mojżesza z 1787 roku.",
         "Ołtarz główny z „Ostatnią Wieczerzą” połączony z amboną i organami. Prospekt organowy z 1785 roku ma monogram króla Stanisława Augusta."],
        "Kościół Wszystkich Świętych przy ulicy Grobla",
        extra=["Kilka kroków dalej, przy tej samej ulicy, jest Muzeum Kultur Świata."]),
    church(
        "kosciol-mb-bolesnej", "Kościół Matki Boskiej Bolesnej", 66145,
        "ul. Głogowska 97, 60-265 Poznań",
        "Neoromański kościół z czerwonej cegły z marmurową kopią Piety Michała Anioła.",
        "Kościół zbudowano w latach 1899–1901 w stylu neoromańskim z czerwonej cegły. Wyróżnia się wysoką wieżą ze smukłym, metalowym hełmem.",
        ["Świątynia ma trzy nawy z transeptem i sklepienia krzyżowe."],
        ["Marmurową kopię watykańskiej Piety Michała Anioła z około 1900 roku w ołtarzu głównym.",
         "Kamienną chrzcielnicę z rzeźbą chrztu Chrystusa i ambonę z figurami ewangelistów.",
         "Symboliczny grób z pomnikiem ks. Jerzego Popiełuszki przy bramie."],
        "Neoromański kościół Matki Boskiej Bolesnej",
        phone="+48 61 866 87 38", www=("mbbolesna-poznan.org", "https://www.mbbolesna-poznan.org/")),
    church(
        "kosciol-zmartwychwstania", "Kościół Zmartwychwstania Pańskiego", 66162,
        "ul. Dąbrówki 4/7, 61-101 Poznań",
        "Neoklasycystyczny kościół-wotum za niepodległość, z portykiem jak w greckiej świątyni.",
        "Kościół zbudowano w latach 1923–1926. Jego neoklasycystyczna forma miała wyrażać wdzięczność za odzyskanie niepodległości w 1918 roku i upamiętniać 950-lecie chrztu Polski. Od początku prowadzą go zmartwychwstańcy.",
        ["Architektura i wystrój nawiązują do symboliki odrodzenia i zwycięstwa."],
        ["Monumentalny portyk z kolumnami jońskimi, nawiązujący do świątyni greckiej.",
         "Jednonawowe, halowe wnętrze z kasetonowym stropem i posągiem zwycięskiego Chrystusa w prezbiterium.",
         "Wieżę z figurami polskich świętych: Andrzeja Boboli, Kazimierza, Stanisława ze Szczepanowa i Jana Kantego."],
        "Neoklasycystyczny kościół Zmartwychwstania Pańskiego na Wildzie",
        phone="+48 61 833 34 62", www=("poznancr.pl", "http://www.poznancr.pl/")),
    church(
        "kosciol-maryi-krolowej", "Kościół Maryi Królowej", 66243,
        "Rynek Wildecki 4, 61-546 Poznań",
        "Neorenesansowy kościół na Rynku Wildeckim z 45-metrową wieżą.",
        "Kościół zbudowano w latach 1904–1907 w stylu neorenesansowym. Do końca II wojny światowej należał do gminy ewangelickiej jako kościół św. Mateusza. Od 1945 roku jest katolicki.",
        ["Po przejęciu przez parafię katolicką zmieniono wezwanie na obecne."],
        ["Wieżę o wysokości 45 metrów z portalem wejściowym, na osi budynku.",
         "Wnętrze ze sklepieniem beczkowym, witrażami, malarstwem ściennym i rzeźbami.",
         "Pomnik Archanioła Michała przed kościołem."],
        "Kościół Maryi Królowej na Rynku Wildeckim",
        phone="+48 61 833 15 90", www=("parafia-maryi-krolowej.poznan.pl", "http://www.parafia-maryi-krolowej.poznan.pl/")),
    church(
        "kosciol-jana-vianneya", "Kościół św. Jana Vianneya", 66475,
        "ul. Podlaska 10, 60-623 Poznań",
        "Międzywojenna rotunda z kolumnowym portykiem na wzgórzu na Sołaczu.",
        "Kościół na Sołaczu to neoklasycystyczna rotunda na planie koła, zbudowana w latach 1928–1930. Jest zabytkiem polskiej architektury międzywojennej.",
        ["Świątynia stoi na wzniesieniu, a prowadzą do niej monumentalne, szerokie schody."],
        ["Centralny portyk kolumnowy, dwa portyki boczne i kopułę nad prezbiterium.",
         "Jasne, przestronne wnętrze z krucyfiksem w ołtarzu głównym i witrażami nawiązującymi do św. Jana Vianneya, św. Wojciecha i Ostatniej Wieczerzy."],
        "Rotunda kościoła św. Jana Vianneya na Sołaczu",
        extra=["Kościół leży niedaleko Parku Sołackiego, więc łatwo połączyć oba miejsca."],
        www=("jmv-solacz.pl", "http://www.jmv-solacz.pl/")),
    church(
        "kosciol-sw-anny", "Kościół św. Anny", 66502,
        "ul. Limanowskiego 13, 60-744 Poznań",
        "Neogotycki kościół na Łazarzu z wieżą zegarową i oryginalnymi witrażami.",
        "Neogotycki kościół na Łazarzu zbudowano w latach 1904–1907. Początkowo należał do Kościoła ewangelickiego, a od 1945 roku jest katolicki.",
        ["Świątynia jest trójnawowa, na planie krzyża greckiego."],
        ["Wieżę zegarową, trzy zdobione portale i neogotyckie szczyty.",
         "Sklepienia kryształowe i krzyżowo-żebrowe, polichromie i oryginalne witraże.",
         "Obraz Chrystusa Cierpiącego z XVIII wieku, kopię obrazu Leonarda da Vinci z twarzą św. Anny i płaskorzeźby XIX-wiecznego włoskiego artysty Cirilla dell'Antonio."],
        "Neogotycki kościół św. Anny na Łazarzu",
        www=("swanna.tami.pl", "http://swanna.tami.pl/")),
]
