# -*- coding: utf-8 -*-
"""Atrakcje z rozbudowy od 29.09.2026 (plan w src/PLAN.md).
Format taki sam jak w site_data.py. Dane sprawdzone 29.09.2026."""

EXTRA = [
    # ─── Partia 1 ───
    dict(
        slug="centrum-szyfrow-enigma", cat="muzea", name="Centrum Szyfrów Enigma",
        img="centrum-szyfrow-enigma", img_alt="Ekspozycja Centrum Szyfrów Enigma",
        short="Jak trzech matematyków z Poznania złamało szyfr Enigmy. Multimedialna wystawa z audioprzewodnikiem.",
        badge="Pn nieczynne",
        status=None,
        lead="Centrum Szyfrów Enigma, otwarte w 2021 roku, opowiada o tym, jak trzej polscy matematycy, Marian Rejewski, Henryk Zygalski i Jerzy Różycki, złamali szyfry niemieckiej maszyny Enigma. Prowadzi je Poznańskie Centrum Dziedzictwa.",
        sections=[
            ("Co zobaczyć", [
                "Nowoczesną, multimedialną wystawę o złamaniu szyfrów Enigmy. Centrum podkreśla, że to osiągnięcie, zapoczątkowane w Poznaniu, otworzyło drogę do rewolucji cyfrowej.",
                "Część ekspozycji pokazuje też, jak na przestrzeni dziejów ukrywano informacje.",
            ]),
            ("Jak zwiedzać", [
                "Bilety kupuje się na konkretną godzinę. Na wystawę wchodzi się co 15 minut, w grupach do 15 osób. Ostatnie wejście jest godzinę przed zamknięciem.",
                "Na zwiedzanie warto zarezerwować około 2 godzin.",
                "Audioprzewodnik jest w cenie biletu, w pięciu językach. Są też wersje z tłumaczeniem na polski język migowy, z audiodeskrypcją i w tekście łatwym do czytania.",
            ]),
        ],
        address="ul. Święty Marcin 78, 61-809 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–piątek", "9:00–18:00"), ("Sobota–niedziela", "10:00–19:00")],
        tickets=[("Normalny", "35 zł"), ("Ulgowy", "29 zł"), ("Rodzinny", "75 zł"), ("Dzieci do 6 lat", "bezpłatnie")],
        phone="+48 61 888 45 12", www=("csenigma.pl", "https://csenigma.pl/zaplanuj-wizyte/"),
        credit="centrum-szyfrow-enigma",
        sources=[("Centrum Szyfrów Enigma: zaplanuj wizytę", "https://csenigma.pl/zaplanuj-wizyte/"),
                 ("Wikipedia: Centrum Szyfrów Enigma w Poznaniu", "https://pl.wikipedia.org/wiki/Centrum_Szyfr%C3%B3w_Enigma_w_Poznaniu"),
                 ("kultura.poznan.pl: Centrum Szyfrów Enigma", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/centrum-szyfrow-enigma,75354.html")],
    ),
    dict(
        slug="fort-vii", cat="muzea", name="Fort VII – Muzeum Martyrologii Wielkopolan",
        img="fort-vii", img_alt="Brama Fortu VII w Poznaniu",
        short="Miejsce pamięci w dawnym forcie, gdzie w 1939 roku Niemcy utworzyli obóz KL Posen.",
        badge="Wt wstęp wolny",
        status=None,
        lead="Fort VII zbudowano w latach 1876–1880 jako część pruskiej Twierdzy Poznań. 10 października 1939 roku Niemcy utworzyli w nim obóz koncentracyjny KL Posen. Od 1979 roku działa tu Muzeum Martyrologii Wielkopolan.",
        sections=[
            ("Historia", [
                "Obóz działał do 1944 roku, później także jako więzienie policyjne Gestapo i obóz przejściowy. Więziono tu polskich cywilów: inteligencję, działaczy politycznych, członków konspiracji, duchownych i lekarzy. Zginęło tu około 20 tysięcy osób.",
                "W październiku 1939 roku w bunkrze nr 17 zamordowano gazem około 400 pacjentów i pracowników szpitala psychiatrycznego w Owińskach. Był to pierwszy w Europie przypadek użycia gazu do mordowania ludności cywilnej.",
            ]),
            ("Warto wiedzieć", [
                "Zwiedzanie nie jest zalecane dzieciom poniżej 13 lat. Dzieci i grupy szkolne muszą być pod opieką dorosłych.",
                "Do samodzielnego zwiedzania służy aplikacja z audioprzewodnikiem Movi Guide.",
                "1 listopada muzeum jest czynne w godzinach 9:00–19:00.",
                "Dojazd autobusami 121, 156, 161, 177, 186, 191, 193, 729 i 834. Przy muzeum są stojaki na rowery.",
            ]),
        ],
        address="al. Polska, 60-591 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Marzec–październik", "wt–sb 10:00–17:00, nd 10:00–16:00"), ("Listopad–luty", "wt–nd 10:00–16:00")],
        tickets=[("Normalny", "10 zł"), ("Ulgowy", "5 zł"), ("Wtorek", "wstęp wolny"), ("Przewodnik (grupa)", "70 zł po polsku, 90 zł po angielsku")],
        phone="+48 61 848 31 38", www=("fortvii.eu", "https://fortvii.eu/zaplanuj-wizyte/"),
        credit="fort-vii",
        sources=[("Fort VII: zaplanuj wizytę", "https://fortvii.eu/zaplanuj-wizyte/"),
                 ("Wikipedia: Fort VII w Poznaniu", "https://pl.wikipedia.org/wiki/Fort_VII_w_Poznaniu"),
                 ("Wikipedia: Fort VII (miejsce kaźni)", "https://pl.wikipedia.org/wiki/Fort_VII_w_Poznaniu_(miejsce_kaźni)")],
    ),
    dict(
        slug="muzeum-wojskowe", cat="muzea", name="Wielkopolskie Muzeum Wojskowe",
        img="muzeum-wojskowe", img_alt="Ekspozycja Wielkopolskiego Muzeum Wojskowego",
        short="Broń od XI wieku i fragment panoramy „Bitwa pod Piramidami” Wojciecha Kossaka.",
        badge="Pn nieczynne",
        status=None,
        lead="Wielkopolskie Muzeum Wojskowe, oddział Muzeum Narodowego, mieści się w powojennym pawilonie na Starym Rynku. Pokazuje polską i obcą broń oraz pamiątki powstań narodowych, zwłaszcza Powstania Wielkopolskiego.",
        sections=[
            ("Co zobaczyć", [
                "Fragment panoramy „Bitwa pod Piramidami” Wojciecha Kossaka z 1901 roku, jeden z nielicznych eksponatów, które przetrwały z przedwojennych zbiorów.",
                "Rapier z XVI wieku z głownią wykutą w Mediolanie.",
                "Bechter, czyli zbroję z 1580 roku, należącą do miejskiego rotmistrza i ozdobioną herbem Poznania.",
                "Broń białą i palną, uzbrojenie ochronne, mundury i odznaki wojskowe.",
            ]),
            ("Warto wiedzieć", [
                "Z Poznańską Kartą Turystyczną wstęp jest bezpłatny.",
            ]),
        ],
        address="Stary Rynek 9, 61-768 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–środa", "10:00–16:00"), ("Czwartek", "10:00–18:00"), ("Piątek", "10:00–20:00"), ("Sobota–niedziela", "10:00–17:00")],
        tickets=[("Normalny", "15 zł"), ("Ulgowy", "10 zł"), ("Dzieci i młodzież 8–26 lat", "1 zł"), ("Wtorek", "wstęp wolny"), ("Z Poznańską Kartą Turystyczną", "bezpłatnie")], checked="01.10.2026",
        phone="+48 61 852 67 39", www=("mnp.art.pl", "https://mnp.art.pl/"),
        credit="muzeum-wojskowe",
        sources=[("poznan.pl: Wielkopolskie Muzeum Wojskowe", "https://www.poznan.pl/mim/main/muzea-w-poznaniu,poi,202,12/wielkopolskie-muzeum-wojskowe-oddzial-muzeum-narodowego,15709.html"),
                 ("Visit Poznań: Wielkopolskie Muzeum Wojskowe", "https://visitpoznan.pl/wielkopolskie-muzeum-wojskowe")],
    ),
    dict(
        slug="muzeum-pyry", cat="muzea", name="Poznańskie Muzeum Pyry",
        img="muzeum-pyry", img_alt="Ulica Wroniecka, przy której mieści się Muzeum Pyry",
        short="Godzina z humorem o ziemniakach, z wykopkami i pieczeniem własnej pyry. Rezerwacja wymagana.",
        badge="Rezerwacja",
        status=None,
        lead="„Pyra” to po poznańsku ziemniak. Muzeum Pyry to interaktywna, pełna humoru godzinna trasa dla dzieci i dorosłych, prowadzona przez przewodnika.",
        sections=[
            ("Co tu się dzieje", [
                "Uczestnicy dowiadują się, jak ziemniaki trafiły do Europy i Polski, co łączy ziemniaki z praniem, jak walczono ze stonką i jakie potrawy z ziemniaków królują w Polsce i na świecie.",
                "W programie są symulowane wykopki i pieczenie własnego ziemniaka.",
            ]),
            ("Warto wiedzieć", [
                "Zwiedzanie trwa około 60 minut. Miejsce trzeba wcześniej zarezerwować w systemie na stronie muzeum, gdzie widać też dostępne godziny.",
                "Wejście jest od ulicy Mokrej.",
                "Cena obejmuje oprowadzanie i warsztaty.",
            ]),
        ],
        address="ul. Wroniecka 18 (wejście od ul. Mokrej), 61-763 Poznań",
        hours=[("Wtorek–niedziela", "godziny w systemie rezerwacji"), ("Poniedziałek", "nieczynne")],
        tickets=[("Normalny", "31 zł"), ("Ulgowy", "29 zł"), ("Rodzinny (od 3 osób)", "28 zł od osoby"), ("Po angielsku", "35 zł"), ("Dzieci do 4 lat", "bezpłatnie")],
        phone="+48 609 121 611", www=("muzeumpyry.pl", "https://muzeumpyry.pl/"),
        credit="muzeum-pyry",
        sources=[("Poznańskie Muzeum Pyry", "https://muzeumpyry.pl/"),
                 ("Visit Poznań: Poznańskie Muzeum Pyry", "https://visitpoznan.pl/poznanskie-muzeum-pyry")],
    ),
    dict(
        slug="fotoplastykon", cat="muzea", name="Fotoplastykon Poznański",
        img="fotoplastykon", img_alt="Fotoplastykon Poznański",
        short="Zabytkowe urządzenie do oglądania trójwymiarowych zdjęć, jedno z nielicznych działających w Polsce.",
        badge="Nd nieczynne",
        status=None,
        lead="Fotoplastykon to XIX-wieczne urządzenie do oglądania stereofotografii, czyli zdjęć, które przez okular wyglądają na trójwymiarowe. Poznański egzemplarz jest jednym z nielicznych działających w Polsce.",
        sections=[
            ("Historia", [
                "Fotoplastykon trafił do Poznania po II wojnie światowej. W latach 1982–2005 stał w galerii fotografa Antoniego Ruta przy ulicy Święty Marcin.",
                "W 2014 roku, dzięki współpracy Antoniego Ruta z miastem, urządzenie stało się własnością miejską. Od tego roku stoi w budynku Arkadii przy ulicy Ratajczaka.",
            ]),
            ("Co zobaczyć", [
                "Czasowe wystawy tematyczne ze zdjęciami stereoskopowymi. Opisy są po polsku, angielsku i ukraińsku.",
            ]),
        ],
        address="ul. Ratajczaka 44 (Arkadia, wejście przez Centrum Informacji Kulturalnej), 61-728 Poznań",
        hours=[("Poniedziałek–piątek", "10:00–18:00"), ("Sobota", "10:00–17:00"), ("Niedziela i święta", "nieczynne")],
        tickets=[("Ceny biletów", "na fotoplastykon.poznan.pl")],
        phone="+48 61 854 07 52", www=("kultura.poznan.pl", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/fotoplastykon-poznanski,71379.html"),
        credit="fotoplastykon",
        sources=[("kultura.poznan.pl: Fotoplastykon Poznański", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/fotoplastykon-poznanski,71379.html"),
                 ("kultura.poznan.pl: aktualności o Fotoplastykonie", "https://kultura.poznan.pl/mim/kultura/news/fotoplastykon-poznanski,252807.html")],
    ),
    dict(
        slug="akademia-lubranskiego", cat="muzea", name="Muzeum Archidiecezjalne – Akademia Lubrańskiego",
        img="akademia-lubranskiego", img_alt="Budynek Akademii Lubrańskiego na Ostrowie Tumskim",
        short="Sztuka sakralna w budynku z 1520 roku: miecz św. Piotra i monstrancja króla Jagiełły.",
        badge="Pn nieczynne",
        status=None,
        lead="Muzeum Archidiecezjalne założył w latach 1894–1898 arcybiskup Florian Stablewski. To najstarsza placówka muzealna w Poznaniu i jedno z najstarszych muzeów tego typu w Polsce. Mieści się na Ostrowie Tumskim, w budynku dawnej Akademii Lubrańskiego z 1520 roku.",
        sections=[
            ("Co zobaczyć", [
                "Sztukę sakralną od średniowiecza do współczesności, w tym najbogatszy w tej części Polski zbiór rzeźby i malarstwa z XIV i XV wieku.",
                "Miecz św. Piotra, monstrancję króla Władysława Jagiełły, złoty kielich biskupa Tolibowskiego i pastorał z Limoges.",
                "Galerie portretów, malarstwa polskiego i europejskiego, tkaniny oraz złotnictwo.",
            ]),
            ("Warto wiedzieć", [
                "Muzeum jest częścią biletu na trzy miejsca na Ostrowie Tumskim (Brama Poznania, Genius Loci i Akademia Lubrańskiego), który kosztuje 49 zł.",
            ]),
        ],
        address="ul. Lubrańskiego 1, 61-108 Poznań",
        hours=[("Wtorek–piątek", "11:00–17:00"), ("Sobota", "11:00–16:00"), ("Niedziela", "11:00–15:00")],
        tickets=[("Ceny biletów", "na akademialubranskiego.pl"), ("Bilet na 3 miejsca na Ostrowie", "49 zł")],
        phone="+48 61 852 61 95", www=("akademialubranskiego.pl", "https://akademialubranskiego.pl/muzeum"),
        credit="akademia-lubranskiego",
        sources=[("Akademia Lubrańskiego: muzeum", "https://akademialubranskiego.pl/muzeum"),
                 ("Visit Poznań: Muzeum Archidiecezjalne", "https://visitpoznan.pl/muzeum-archidiecezjalne-akademia-lubranskiego"),
                 ("Genius Loci: bilety (bilet na 3 miejsca)", "https://rezerwat.muzarp.poznan.pl/pl/bilety")],
    ),
    dict(
        slug="biblioteka-raczynskich", cat="zabytki", name="Biblioteka Raczyńskich",
        img="biblioteka-raczynskich", img_alt="Gmach Biblioteki Raczyńskich na placu Wolności",
        short="Klasycystyczny gmach z 1829 roku z fasadą wzorowaną na Luwrze, przy placu Wolności.",
        badge="Bezpłatnie",
        status=None,
        lead="Bibliotekę założył hrabia Edward Raczyński. Otwarto ją 5 maja 1829 roku jako pierwszą bibliotekę publiczną na ziemiach polskich pod zaborem pruskim.",
        sections=[
            ("Gmach", [
                "Klasycystyczny budynek przy placu Wolności wzniesiono w latach 1822–1828. Fasada nawiązuje do paryskiego Luwru i ma dwanaście par żeliwnych kolumn w porządku korynckim.",
                "1 lipca 2013 roku otwarto nowe skrzydło biblioteki, zaprojektowane przez pracownię JEMS Architekci.",
            ]),
            ("Warto wiedzieć", [
                "Biblioteka ma około 1,8 miliona zbiorów i 35 filii w Poznaniu. Prowadzi też muzea literackie, m.in. Muzeum Literackie Henryka Sienkiewicza na Starym Rynku.",
            ]),
        ],
        address="pl. Wolności, 61-738 Poznań",
        hours=[("Gmach od strony placu", "widoczny całą dobę")],
        tickets=[("Oglądanie gmachu", "bezpłatnie")],
        phone=None, www=("bracz.edu.pl", "https://bracz.edu.pl/"),
        credit="biblioteka-raczynskich",
        sources=[("Wikipedia: Biblioteka Raczyńskich", "https://pl.wikipedia.org/wiki/Biblioteka_Raczyńskich")],
    ),
    dict(
        slug="kolegium-jezuickie", cat="zabytki", name="Dawne Kolegium Jezuickie",
        img="kolegium-jezuickie", img_alt="Barokowy gmach dawnego Kolegium Jezuickiego",
        short="Barokowy gmach, w którym mieszkał Napoleon. Dziś siedziba Urzędu Miasta Poznania.",
        badge="Bezpłatnie",
        status=None,
        lead="Kolegium Jezuitów działało w latach 1572–1773 i było jedną z najbardziej cenionych szkół w Rzeczypospolitej. Obecny barokowy gmach powstał w latach 1701–1733 według projektu Giovanniego Catenazziego. Dziś mieści się w nim Urząd Miasta Poznania.",
        sections=[
            ("Historia", [
                "W kolegium uczono języków klasycznych, matematyki, fizyki, filozofii i nauk przyrodniczych. Na początku było 16 profesorów i około 300 uczniów. Do jego tradycji nawiązują Uniwersytet im. Adama Mickiewicza i Liceum św. Marii Magdaleny.",
                "W listopadzie 1806 roku przez prawie trzy tygodnie mieszkał tu Napoleon Bonaparte. 23 października 1805 roku gościł car Aleksander I, a w latach 1815–1830 rezydował tu namiestnik Wielkiego Księstwa Poznańskiego, książę Antoni Radziwiłł.",
            ]),
            ("Co zobaczyć", [
                "Trzykondygnacyjny gmach w kształcie podkowy, otaczający wewnętrzny dziedziniec.",
                "Tuż obok stoi Fara Poznańska. W sezonie, od maja do września, przy placu Kolegiackim 17 działa punkt informacji turystycznej.",
            ]),
        ],
        address="pl. Kolegiacki 17, 61-841 Poznań",
        hours=[("Gmach od strony placu", "widoczny całą dobę")],
        tickets=[("Oglądanie gmachu", "bezpłatnie")],
        phone=None, www=("poznan.pl", "https://www.poznan.pl/"),
        credit="kolegium-jezuickie",
        sources=[("Wikipedia: Kolegium Jezuickie w Poznaniu", "https://pl.wikipedia.org/wiki/Kolegium_Jezuickie_w_Poznaniu"),
                 ("Visit Poznań: informacja turystyczna", "https://visitpoznan.pl/it")],
    ),
    dict(
        slug="kosciol-nmp-in-summo", cat="koscioly", name="Kościół NMP in Summo",
        img="kosciol-nmp-in-summo", img_alt="Gotycki kościół NMP in Summo na tle katedry",
        short="Gotycki kościół z XV wieku w miejscu kaplicy z czasów Mieszka I i Dobrawy.",
        badge="Bezpłatnie",
        status=None,
        lead="Gotycki kościół Najświętszej Maryi Panny in Summo stoi na Ostrowie Tumskim, obok katedry. Konsekrowano go 2 lipca 1448 roku. W tym miejscu w X wieku stała kaplica pałacu Mieszka I.",
        sections=[
            ("Historia", [
                "Według tradycji przedromańską kaplicę wzniosła około 965 roku Dobrawa, żona Mieszka I, która była chrześcijanką przed jego chrztem. Była to najstarsza świątynia na grodzie poznańskim i prawdopodobnie w całym państwie Piastów.",
                "Około 1430 roku starą świątynię rozebrano i zaczęto budować nowy, gotycki kościół. Konsekrował go biskup Andrzej z Bnina.",
                "Od 1999 roku wokół kościoła trwają badania archeologiczne pod kierunkiem prof. Hanny Kóčki-Krenz, które odsłaniają relikty zespołu pałacowego Mieszka I.",
            ]),
            ("Co zobaczyć", [
                "Polichromie, witraże i ołtarz główny zaprojektowany przez prof. Wacława Taranczewskiego po 1954 roku.",
                "Obok kościoła leży Rezerwat Archeologiczny Genius Loci, który organizuje zwiedzanie kościoła i okolic.",
            ]),
        ],
        address="Ostrów Tumski, 61-109 Poznań",
        hours=[("Kościół", "otwarty dla zwiedzających, poza nabożeństwami")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("katedra.archpoznan.pl", "https://www.katedra.archpoznan.pl/historia-kosciola-na-ostrowiu-tumskim-p-w-najswietszej-maryi-panny-in-summo/"),
        credit="kosciol-nmp-in-summo",
        sources=[("Katedra Poznańska: historia kościoła NMP in Summo", "https://www.katedra.archpoznan.pl/historia-kosciola-na-ostrowiu-tumskim-p-w-najswietszej-maryi-panny-in-summo/"),
                 ("Genius Loci: zwiedzaj kościół NMP in Summo", "https://rezerwat.muzarp.poznan.pl/pl/zwiedzaj-z-nami-kosciol-nmp-in-summo-i-okolice")],
    ),
    dict(
        slug="mury-miejskie", cat="zabytki", name="Średniowieczne mury miejskie",
        img="mury-miejskie", img_alt="Fragment murów miejskich przy ulicy Wronieckiej",
        short="Relikty murów z XIII–XV wieku, Baszta Katarzynek i ścieżka turystyczna przy Bramie Wronieckiej.",
        badge="Bezpłatnie",
        status=None,
        lead="Mury obronne otaczały Poznań od XIII do XV wieku. Miały około 1725 metrów długości i 7 metrów wysokości, a wewnętrzne baszty sięgały 11 metrów.",
        sections=[
            ("Historia", [
                "Drewniano-ziemne umocnienia zaczęto budować wkrótce po lokacji miasta w 1253 roku, a potem zastąpiono je murem z 32 wykuszami.",
                "Po 1431 roku dobudowano drugi, zewnętrzny mur z półkolistymi basztami przystosowanymi do broni palnej. W XVII wieku, wraz z rozwojem artylerii, mury straciły znaczenie obronne.",
            ]),
            ("Co zobaczyć", [
                "Basztę Katarzynek, jedyną zachowaną oryginalną basztę.",
                "Relikty bastionu artyleryjskiego przy ulicy 23 Lutego.",
                "Fragmenty muru zewnętrznego z Furtą Zamkową przy Zamku Królewskim oraz zachodnie odcinki przy ulicy Ludgardy.",
                "Ścieżkę turystyczną między bastionem a reliktami Bramy Wronieckiej.",
            ]),
            ("Warto wiedzieć", [
                "Od sierpnia 2013 roku przebieg dawnych murów wyznacza 17 tablic wmurowanych w chodniki Starego Miasta.",
            ]),
        ],
        address="ul. Wroniecka, 61-763 Poznań",
        hours=[("Relikty murów", "dostępne całą dobę")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", "https://www.poznan.pl/mim/wortals/turystyka/fortyfikacje,poi,2575/"),
        credit="mury-miejskie",
        sources=[("Wikipedia: Mury miejskie w Poznaniu", "https://pl.wikipedia.org/wiki/Mury_miejskie_w_Poznaniu"),
                 ("poznan.pl: fortyfikacje", "https://www.poznan.pl/mim/wortals/turystyka/fortyfikacje,poi,2575/")],
    ),

    # ─── Partia 2 ───
    dict(
        slug="muzeum-broni-pancernej", cat="muzea", name="Muzeum Broni Pancernej",
        img="muzeum-broni-pancernej", img_alt="Niszczyciel czołgów Jagdpanzer 38(t) w Muzeum Broni Pancernej",
        short="75 pojazdów pancernych z całego świata, od Powstania Wielkopolskiego po zimną wojnę.",
        badge="Czw wstęp wolny",
        status=None,
        lead="Muzeum Broni Pancernej jest oddziałem Muzeum Wojska Polskiego w Warszawie. Utworzono je 1 kwietnia 2015 roku, a w obecnej siedzibie przy ul. 3 Pułku Lotniczego działa od października 2019 roku.",
        sections=[
            ("Co zobaczyć", [
                "Około 230 eksponatów, w tym 75 pojazdów z całego świata. Wiele z nich to egzemplarze unikatowe.",
                "Ekspozycja zajmuje cztery pawilony po 700 m² i zadaszoną wystawę plenerową o powierzchni 3000 m².",
                "Wystawy opowiadają o Powstaniu Wielkopolskim, II wojnie światowej, 1. Dywizji Pancernej gen. Stanisława Maczka, stu latach polskiej broni pancernej i czasach zimnej wojny.",
            ]),
            ("Warto wiedzieć", [
                "Na zwiedzanie warto zarezerwować co najmniej 2 godziny.",
                "W czwartki wstęp na wystawę stałą jest bezpłatny. Bezpłatny bilet odbiera się w kasie.",
                "Kasa czynna jest do 17:00 i to jest godzina ostatniego wejścia. Bilety można też kupić przez serwis Bilety24.",
            ]),
        ],
        address="ul. 3 Pułku Lotniczego 4, 60-421 Poznań",
        hours=[("Poniedziałek–wtorek", "nieczynne"), ("Środa–niedziela", "10:30–17:30"), ("Kasa", "10:00–17:00, ostatnie wejście o 17:00")],
        tickets=[("Normalny", "30 zł"), ("Ulgowy", "20 zł"), ("Czwartek", "wstęp wolny (bezpłatny bilet z kasy)")], checked="01.10.2026",
        phone=None, www=("muzeumbronipancernej.pl", "https://muzeumbronipancernej.pl/zwiedzanie/"),
        credit="muzeum-broni-pancernej",
        sources=[("Muzeum Broni Pancernej: dla zwiedzających", "https://muzeumbronipancernej.pl/zwiedzanie/")],
    ),
    dict(
        slug="muzeum-farmacji", cat="muzea", name="Muzeum Farmacji",
        img="muzeum-farmacji", img_alt="Ekspozycja Muzeum Farmacji w Poznaniu",
        short="Dawna apteka z Miłosławia, naczynia apteczne i stare druki. Otwarte w czwartki, wstęp wolny.",
        badge="Wstęp wolny",
        status=None,
        lead="Muzeum Farmacji powstało w czerwcu 1989 roku z inicjatywy Sekcji Historii Farmacji Polskiego Towarzystwa Farmaceutycznego. Od 1992 roku opiekuje się nim Wielkopolska Okręgowa Izba Aptekarska.",
        sections=[
            ("Co zobaczyć", [
                "Oficynę apteczną z przełomu XIX i XX wieku, przeniesioną z apteki w Miłosławiu.",
                "Naczynia apteczne z drewna, szkła, kamionki i porcelany, żeliwne moździerze i sprzęt laboratoryjny.",
                "Około 1200 książek, w tym stare druki.",
            ]),
            ("Warto wiedzieć", [
                "Muzeum najpierw działało w kamienicy na Starym Rynku. Do obecnej siedziby przeniesiono je w 1996 roku, a oficjalnie otwarto w styczniu 2000 roku.",
                "Przed wizytą warto zadzwonić do kustosza muzeum.",
            ]),
        ],
        address="al. Marcinkowskiego 11, 61-827 Poznań",
        hours=[("Czwartek", "10:00–17:00"), ("Pozostałe dni", "nieczynne")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone="+48 798 195 988", www=("woia.pl", "https://woia.pl/aktualnosci/muzeumfarmacji"),
        credit="muzeum-farmacji",
        sources=[("Wielkopolska Okręgowa Izba Aptekarska: Muzeum Farmacji", "https://woia.pl/aktualnosci/muzeumfarmacji")],
    ),
    dict(
        slug="muzeum-historii-ubioru", cat="muzea", name="Muzeum Historii Ubioru",
        img="muzeum-historii-ubioru", img_alt="Wystawa „Moda lubi się powtarzać” w Muzeum Historii Ubioru",
        short="Historia mody i ubioru w prywatnym muzeum fundacji, 15 minut pieszo od dworca.",
        badge="Nd–pn nieczynne",
        status=None,
        lead="Muzeum Historii Ubioru prowadzi Fundacja Muzeum Historii Ubioru, a dochód z biletów przeznacza na swoją działalność statutową. Muzeum leży w centrum, około 15 minut pieszo od dworca Poznań Główny.",
        sections=[
            ("Warto wiedzieć", [
                "Ostatnie wejście jest 30 minut przed zamknięciem.",
                "Grupy od 10 do 21 osób mogą zamówić oprowadzanie: 120 zł po polsku lub 150 zł po angielsku, plus bilety.",
                "Z Poznańską Kartą Turystyczną bilet jest tańszy.",
                "Dojazd tramwajami 2, 3, 6, 9, 12, 13, 16 i 18.",
            ]),
        ],
        address="ul. Kwiatowa 14/2, 61-886 Poznań",
        hours=[("Wtorek, środa, piątek", "10:00–15:00"), ("Czwartek", "15:00–19:00"), ("Sobota", "11:00–16:00"), ("Niedziela–poniedziałek", "nieczynne")],
        tickets=[("Normalny", "20 zł"), ("Ulgowy", "15 zł"), ("Dzieci do 7 lat", "bezpłatnie")],
        phone=None, www=("fmhu.pl", "https://www.fmhu.pl/twoja-wizyta/"),
        credit="muzeum-historii-ubioru",
        sources=[("Muzeum Historii Ubioru: twoja wizyta", "https://www.fmhu.pl/twoja-wizyta/")],
    ),
    dict(
        slug="muzeum-iluzji", cat="muzea", name="Muzeum Iluzji, Nauki i Sztuki",
        img="muzeum-iluzji", img_alt="Ulica Woźna, przy której mieści się Muzeum Iluzji",
        short="Ponad 60 interaktywnych eksponatów: odwrócony pokój, lewitacja i złudzenia optyczne.",
        badge="Pn nieczynne",
        status=None,
        lead="Muzeum Iluzji, Nauki i Sztuki leży przy ulicy Woźnej, tuż obok Starego Rynku. Łączy złudzenia optyczne z nauką i sztuką, a eksponaty można dotykać i wypróbowywać.",
        sections=[
            ("Co zobaczyć", [
                "Ponad 60 eksponatów w siedmiu przestrzeniach wystawowych: iluzje optyczne, łamigłówki i duże instalacje.",
                "Odwrócony pokój, Pixel Table i stanowiska, na których można „lewitować”.",
            ]),
            ("Warto wiedzieć", [
                "Ostatnie wejście jest o 17:30.",
                "Aktualne ceny biletów muzeum podaje na swojej stronie i w mediach społecznościowych.",
            ]),
        ],
        address="ul. Woźna 19/20, 61-777 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–niedziela", "10:00–19:00")],
        tickets=[("Ceny biletów", "na muzeumins.pl")],
        phone="+48 609 711 931", www=("muzeumins.pl", "https://muzeumins.pl/"),
        credit="muzeum-iluzji",
        sources=[("kultura.poznan.pl: Muzeum Iluzji, Nauki i Sztuki", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/muzeum-iluzji-nauki-i-sztuki,79651.html")],
    ),
    dict(
        slug="muzeum-komunikacji-mpk", cat="muzea", name="Muzeum Komunikacji Miejskiej MPK",
        img="muzeum-komunikacji-mpk", img_alt="Zajezdnia tramwajowa przy ulicy Głogowskiej",
        short="Historia poznańskich tramwajów w zajezdni Głogowska. Obecnie nieczynne.",
        badge="Zamknięte",
        status=("closed", "Izba Pamięci i Tradycji MPK Poznań jest zamknięta ze względów technicznych do odwołania (komunikat MPK Poznań)."),
        lead="Muzeum, oficjalnie nazywane Izbą Pamięci i Tradycji MPK Poznań, otwarto 31 stycznia 2007 roku. Mieści się w najstarszym budynku zajezdni przy ulicy Głogowskiej, dawnej podstacji transformatorowej z lat 1928–1929.",
        sections=[
            ("Co zobaczyć", [
                "Pamiątki z historii poznańskiej komunikacji, m.in. z budowy i otwarcia Poznańskiego Szybkiego Tramwaju.",
                "Archiwalne nagrania z lokalnej telewizji.",
            ]),
            ("Warto wiedzieć", [
                "Gdy muzeum działa, zwiedza się je w grupach do 20 osób po wcześniejszej rezerwacji telefonicznej.",
                "Dotychczasowe ceny: normalny 10 zł, dzieci do 16 lat 7 zł, rodzinny (do 5 osób) 30 zł.",
            ]),
        ],
        address="ul. Głogowska 131/133, 60-244 Poznań",
        hours=[("Obecnie", "zamknięte do odwołania")],
        tickets=[("Obecnie", "brak zwiedzania")],
        phone="+48 507 036 842", www=("mpk.poznan.pl", "https://www.mpk.poznan.pl/strefa-pasazera/turystyka/muzeum/"),
        credit="muzeum-komunikacji-mpk",
        sources=[("MPK Poznań: Izba Pamięci i Tradycji", "https://www.mpk.poznan.pl/strefa-pasazera/turystyka/muzeum/"),
                 ("kultura.poznan.pl: Muzeum Komunikacji Miejskiej MPK", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/muzeum-komunikacji-miejskiej-mpk-poznan,36225.html")],
    ),
    dict(
        slug="muzeum-prl", cat="muzea", name="Muzeum PRL-u",
        img="muzeum-prl", img_alt="Ulica Żydowska, przy której mieści się Muzeum PRL-u",
        short="Codzienność w PRL do dotknięcia: telefon z tarczą, ubrania z epoki, mieszkanie i zakład pracy.",
        badge="Pn nieczynne",
        status=None,
        lead="Muzeum PRL-u przy ulicy Żydowskiej pokazuje codzienne życie w Polsce Ludowej: jak wyglądały mieszkanie i zakład pracy, czym bawiły się dzieci, co się czytało i jadło.",
        sections=[
            ("Co tu się robi", [
                "Eksponaty można dotykać: zadzwonić z telefonu z tarczą, przymierzyć ubrania z epoki i sprawdzić, jak dobrze zna się Poznań sprzed 50 lat.",
                "Muzeum jest dla wszystkich grup wiekowych: starsi odwiedzający wspominają, a młodsi dostają interaktywną lekcję historii.",
            ]),
            ("Warto wiedzieć", [
                "Grupy powyżej 10 osób muszą wcześniej zarezerwować wizytę. Przewodnik po polsku jest wtedy w cenie biletu.",
                "Przewodnik dla osób indywidualnych kosztuje 100 zł.",
                "Bilet senioralny (65+) za 19 zł obowiązuje tylko w środy w godzinach 14:00–18:00.",
            ]),
        ],
        address="ul. Żydowska 4, 61-761 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–niedziela", "10:00–18:00")],
        tickets=[("Normalny", "35 zł"), ("Ulgowy", "31 zł"), ("Rodzinny (min. 2 dorosłych + dziecko)", "27 zł od osoby"), ("Dzieci do 3 lat", "bezpłatnie")],
        phone="+48 603 090 206", www=("prlmuzeum.pl", "https://prlmuzeum.pl/cennik/"),
        credit="muzeum-prl",
        sources=[("Muzeum PRL-u: cennik", "https://prlmuzeum.pl/cennik/"),
                 ("Visit Poznań: Muzeum PRL-u", "https://visitpoznan.pl/muzeum-prl")],
    ),
    dict(
        slug="schron-przeciwatomowy", cat="muzea", name="Przeciwatomowy Schron i Galeria Plakatu",
        img="schron-przeciwatomowy", img_alt="Naziemne zabudowania schronu przy ulicy Słupskiej 62",
        short="Tajny schron dla władz miasta z oryginalnym wyposażeniem z PRL i plakaty z epoki socjalizmu.",
        badge="Sprawdź przed wizytą",
        status=("warning", "Według portalu miasta schron jest zamknięty dla zwiedzających indywidualnych do 2026 roku, a grupy mogą umówić wizytę telefonicznie. Przed przyjazdem zadzwoń i potwierdź, czy obiekt jest otwarty."),
        lead="Przy ulicy Słupskiej, na Krzyżownikach niedaleko Jeziora Kierskiego, znajduje się tajny schron przeciwatomowy zbudowany dla prezydenta Poznania i najwyższych władz miasta.",
        sections=[
            ("Co zobaczyć", [
                "Wnętrza schronu z oryginalnym, niezmienionym wyposażeniem z czasów PRL.",
                "Galerię Plakatu z okresu socjalizmu, podzieloną na trzy części tematyczne.",
            ]),
            ("Warto wiedzieć", [
                "Ostatnie wejście jest 30 minut przed zamknięciem.",
                "Grupy zorganizowane muszą wcześniej zarezerwować wizytę telefonicznie.",
            ]),
        ],
        address="ul. Słupska 62, 60-458 Poznań",
        hours=[("Środa–piątek", "10:00–16:00"), ("Ostatnia sobota miesiąca", "10:00–16:00")],
        tickets=[("Normalny", "15 zł"), ("Ulgowy", "10 zł")],
        phone="+48 61 852 94 64", www=("kultura.poznan.pl", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/przeciwatomowy-schron-i-galeria-plakatu-oddzial-wielkopolskiego-muzeum-niepodleglosci,55885.html"),
        credit="schron-przeciwatomowy",
        sources=[("kultura.poznan.pl: Przeciwatomowy Schron i Galeria Plakatu", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/przeciwatomowy-schron-i-galeria-plakatu-oddzial-wielkopolskiego-muzeum-niepodleglosci,55885.html")],
    ),
    dict(
        slug="gaspar", cat="muzea", name="GASPAR Muzeum Starych Narzędzi i Maszyn",
        img=None, img_alt="",
        short="Prywatne muzeum techniki z pamiątkami po Hipolicie Cegielskim i kolejką wąskotorową.",
        badge="Po umówieniu",
        status=None,
        lead="GASPAR to prywatne muzeum techniki, którego patronem jest Hipolit Cegielski, założyciel słynnych poznańskich zakładów HCP.",
        sections=[
            ("Co zobaczyć", [
                "Narzędzia ręczne, stolarskie i ślusarskie oraz dawne maszyny.",
                "Pamiątki związane z Hipolitem Cegielskim i zakładami H. Cegielski – Poznań.",
                "Budynki wzniesione z odzyskanych materiałów w technologii muru pruskiego i oryginalną kolejkę wąskotorową.",
            ]),
            ("Warto wiedzieć", [
                "Muzeum jest otwarte w wybrane weekendy, a w inne dni po wcześniejszym umówieniu wizyty.",
                "Zwiedza się je z przewodnikiem. Muzeum prowadzi też warsztaty tematyczne.",
                "Aktualne terminy i ceny są na stronie muzeum.",
            ]),
        ],
        address="ul. Oliwkowa 12, 61-306 Poznań",
        hours=[("Wybrane weekendy", "terminy na gaspar.org.pl"), ("Inne dni", "po umówieniu")],
        tickets=[("Ceny biletów", "na gaspar.org.pl")],
        phone=None, www=("gaspar.org.pl", "https://gaspar.org.pl/"),
        credit=None,
        sources=[("Visit Poznań: GASPAR Muzeum Starych Narzędzi i Maszyn", "https://visitpoznan.pl/gaspar-muzeum-starych-narzedzi-i-maszyn"),
                 ("kultura.poznan.pl: GASPAR", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/gaspar-muzeum-starych-narzedzi-i-maszyn,83432.html")],
    ),
    dict(
        slug="muzeum-czekolady", cat="muzea", name="Muzeum Czekolady",
        img="muzeum-czekolady", img_alt="Ulica Wrocławska, przy której mieści się Muzeum Czekolady",
        short="Zwiedzanie z warsztatem: degustacja, praliny i własna tabliczka czekolady do zabrania.",
        badge="Codziennie",
        status=None,
        lead="Muzeum Czekolady przy ulicy Wrocławskiej, kilka kroków od Starego Rynku, łączy zwiedzanie z warsztatami. Wizyta trwa około 50 minut.",
        sections=[
            ("Co tu się dzieje", [
                "Prezentacja o historii czekolady „od ziarna do tabliczki” i film o uprawie kakaowca.",
                "Degustacja kakao i belgijskiej czekolady.",
                "Samodzielne robienie pralin i własnej tabliczki czekolady, którą zabiera się do domu.",
            ]),
            ("Warto wiedzieć", [
                "Nie trzeba rezerwować. Wejścia są o pełnych godzinach.",
                "Warsztaty prowadzone są po polsku i po angielsku.",
                "W tygodniach roku szkolnego muzeum przyjmuje odwiedzających indywidualnych w godzinach 13:00–18:00.",
            ]),
        ],
        address="ul. Wrocławska 12, 61-838 Poznań",
        hours=[("Codziennie", "10:00–18:00"), ("Sobota", "do 19:00"), ("Niedziela", "od 11:00")],
        tickets=[("Zwiedzanie z warsztatem", "65 zł od osoby (dzieci i dorośli)")],
        phone=None, www=("muzeumczekolady.edu.pl", "https://www.muzeumczekolady.edu.pl/warsztaty-czekoladowe-indywidualne-muzeum-czekolady-zwiedzanie/"),
        credit="muzeum-czekolady",
        sources=[("Muzeum Czekolady: warsztaty dla osób indywidualnych", "https://www.muzeumczekolady.edu.pl/warsztaty-czekoladowe-indywidualne-muzeum-czekolady-zwiedzanie/")],
    ),
    dict(
        slug="izba-prl-w7", cat="muzea", name="Izba PRL w dawnej Hali W7",
        img=None, img_alt="",
        short="Prywatna kolekcja pamiątek z PRL w historycznej hali zakładów Cegielskiego. Wstęp wolny.",
        badge="Wstęp wolny",
        status=None,
        lead="Izba PRL przy ulicy Hetmańskiej pokazuje część kolekcji pamiątek z czasów PRL zgromadzonej przez kolekcjonera i społecznika Marcina Kentzera-Nowakowskiego. Mieści się w dawnej Hali W7 zakładów HCP.",
        sections=[
            ("Co zobaczyć", [
                "Przedmioty codziennego użytku, wyposażenie sklepów, pamiątki z zakładów H. Cegielskiego i z czasów Solidarności oraz polską motoryzację z epoki.",
            ]),
            ("O hali W7", [
                "Hala powstała w czasie I wojny światowej. Produkowano w niej pojazdy sanitarne, a później pociągi pancerne. Po II wojnie światowej, aż do końca zimnej wojny, powstawały tu karabiny i karabiny maszynowe dla wojska.",
            ]),
            ("Warto wiedzieć", [
                "Wizytę trzeba wcześniej umówić z opiekunem kolekcji, telefonicznie lub przez media społecznościowe. Opowiada on o historii eksponatów.",
            ]),
        ],
        address="ul. Hetmańska 90, 61-587 Poznań",
        hours=[("Zwiedzanie", "po wcześniejszym umówieniu")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone="+48 536 779 688", www=("poznan.pl", "https://www.poznan.pl/mim/main/it/izba-prl-przy-dawnej-hali-w7-hcp,poi,202/izba-prl-przy-dawnej-hali-w7-hcp,84872.html"),
        credit=None,
        sources=[("poznan.pl: Izba PRL przy dawnej Hali W7 HCP", "https://www.poznan.pl/mim/main/it/izba-prl-przy-dawnej-hali-w7-hcp,poi,202/izba-prl-przy-dawnej-hali-w7-hcp,84872.html")],
    ),

    # ─── Partia 3 ───
    dict(
        slug="muzeum-ump", cat="muzea", name="Muzeum Uniwersytetu Medycznego",
        img=None, img_alt="",
        short="Historia medycyny i uczelni w otwartej ekspozycji na kampusie UMP. Wstęp wolny.",
        badge="Wstęp wolny",
        status=None,
        lead="Muzeum Uniwersytetu Medycznego im. Karola Marcinkowskiego pokazuje swoje zbiory w otwartej przestrzeni, w budynkach kampusu uczelni przy skrzyżowaniu ulic Przybyszewskiego i Bukowskiej.",
        sections=[
            ("Co zobaczyć", [
                "W Centrum Biologii Medycznej (1. piętro, prawa strona): eksponaty związane ze stomatologią, chorobami wewnętrznymi, chirurgią, pediatrią, radiologią, okulistyką i diagnostyką laboratoryjną.",
                "W Centrum Kongresowo-Dydaktycznym (poziom 1, przy salach A i B, schodami od głównego wejścia): historia uczelni, jej patron Karol Marcinkowski, farmacja, chirurgia i anestezjologia.",
            ]),
            ("Warto wiedzieć", [
                "Obie ekspozycje są bezpłatne i dostępne w godzinach otwarcia budynków.",
                "Grupy zorganizowane powinny wcześniej skontaktować się z muzeum.",
            ]),
        ],
        address="kampus UMP, ul. Bukowska 70, 60-812 Poznań",
        hours=[("Ekspozycje", "w godzinach otwarcia budynków uczelni")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("muzeum.ump.edu.pl", "https://muzeum.ump.edu.pl/zwiedzanie"),
        credit=None,
        sources=[("Muzeum UMP: zwiedzanie", "https://muzeum.ump.edu.pl/zwiedzanie")],
    ),
    dict(
        slug="muzeum-ziemi", cat="muzea", name="Muzeum Ziemi UAM",
        img="muzeum-ziemi", img_alt="Fragment meteorytu Morasko ważący 261,8 kg",
        short="Meteoryty Morasko, w tym okaz ważący 261 kg, minerały i skamieniałości. Wstęp wolny.",
        badge="Wstęp wolny",
        status=None,
        lead="Muzeum Ziemi Wydziału Nauk Geograficznych i Geologicznych UAM gromadzi minerały, skały, skamieniałości i polskie meteoryty. Najcenniejsze są fragmenty meteorytu Morasko.",
        sections=[
            ("Co zobaczyć", [
                "Dwa duże fragmenty meteorytu Morasko: ważący 261 kg, znaleziony w 2012 roku, i ważący 160 kg.",
                "Około półtora tysiąca okazów minerałów, skał i skamieniałości z Polski i świata, w tym kolekcję agatów dolnośląskich.",
                "Repliki czaszek wczesnych australopiteków, zęby wymarłych ryb i gadów oraz lapidarium, czyli ogród skał.",
            ]),
            ("Warto wiedzieć", [
                "Godziny otwarcia zmieniają się co semestr. Aktualny kalendarz jest na stronie muzeum i tam też rezerwuje się wizytę.",
                "W muzeum może jednocześnie przebywać do 20 osób, więc większe grupy muszą się podzielić. Na zwiedzanie wystarczy około 30 minut.",
            ]),
        ],
        address="ul. Bogumiła Krygowskiego 10, 61-680 Poznań",
        hours=[("Godziny", "zmienne, kalendarz na muzeumziemi.amu.edu.pl")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone="+48 61 829 63 50", www=("muzeumziemi.amu.edu.pl", "https://muzeumziemi.amu.edu.pl/"),
        credit="muzeum-ziemi",
        sources=[("kultura.poznan.pl: Muzeum Ziemi UAM", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/muzeum-ziemi-wngig-uam,62348.html"),
                 ("Muzeum Ziemi UAM", "https://muzeumziemi.amu.edu.pl/")],
    ),
    dict(
        slug="salon-nowowiejskiego", cat="muzea", name="Salon Muzyczny Feliksa Nowowiejskiego",
        img="salon-nowowiejskiego", img_alt="Willa Feliksa Nowowiejskiego w Poznaniu",
        short="Willa kompozytora „Roty” z oryginalnym wnętrzem, instrumentami i koncertami kameralnymi.",
        badge="Wt–sb",
        status=None,
        lead="Salon Muzyczny otwarto 7 lutego 2008 roku w willi, w której Feliks Nowowiejski, kompozytor melodii „Roty”, mieszkał i tworzył w latach 1929–1939 i gdzie zmarł w 1946 roku. Prowadzi go Towarzystwo im. Feliksa Nowowiejskiego.",
        sections=[
            ("Co zobaczyć", [
                "Oryginalny układ wnętrz, dzieła sztuki, instrumenty i przedmioty codziennego użytku kompozytora.",
            ]),
            ("Warto wiedzieć", [
                "W salonie odbywają się koncerty kameralne, nawiązujące do tradycji domu Nowowiejskich z okresu międzywojennego i powojennego, a także warsztaty dla dzieci.",
                "Grupy zorganizowane powinny wcześniej zarezerwować wizytę z przewodnikiem.",
            ]),
        ],
        address="al. Wielkopolska 11, 60-603 Poznań",
        hours=[("Wtorek–sobota", "10:00–16:00"), ("Niedziela–poniedziałek", "nieczynne")],
        tickets=[("Normalny", "15 zł"), ("Ulgowy", "13 zł")],
        phone="+48 61 853 40 76", www=("nowowiejski.pl", "http://www.nowowiejski.pl/"),
        credit="salon-nowowiejskiego",
        sources=[("kultura.poznan.pl: Salon Muzyczny Feliksa Nowowiejskiego", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202/salon-muzyczny-feliksa-nowowiejskiego,39688.html")],
    ),
    dict(
        slug="muzeum-kultury-cyfrowej", cat="muzea", name="Poznańskie Muzeum Kultury Cyfrowej",
        img=None, img_alt="",
        short="Commodore 64, Amiga i Atari do uruchomienia. Obecnie zamknięte z powodu przeprowadzki.",
        badge="Zamknięte",
        status=("closed", "Muzeum jest zamknięte na czas remontu nowej, większej siedziby (ponad 200 m²). O ponownym otwarciu poinformuje w mediach społecznościowych."),
        lead="Poznańskie Muzeum Kultury Cyfrowej łączy historię technologii z zabawą. Na klasycznych mikrokomputerach można samodzielnie uruchamiać gry i programy.",
        sections=[
            ("Co zobaczyć", [
                "Mikrokomputery takie jak Commodore 64, Amiga i Atari.",
                "Wystawę o demoscenie, zjawisku z końca lat 80.",
                "Dawną elektronikę: telefony, aparaty i przenośne odtwarzacze, a także podzespoły komputerów i nośniki danych.",
            ]),
        ],
        address="ul. Błękitna 1/7 (wejście od ul. Turkusowej), 60-656 Poznań",
        hours=[("Obecnie", "zamknięte")],
        tickets=[("Obecnie", "brak zwiedzania")],
        phone=None, www=("pmkc.pl", "https://pmkc.pl/"),
        credit=None,
        sources=[("Poznańskie Muzeum Kultury Cyfrowej", "https://pmkc.pl/"),
                 ("kultura.poznan.pl: Poznańskie Muzeum Kultury Cyfrowej", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/poznanskie-muzeum-kultury-cyfrowej,85132.html")],
    ),
    dict(
        slug="muzeum-bizuterii-moja", cat="muzea", name="Muzeum Biżuterii MoJA",
        img="muzeum-bizuterii-moja", img_alt="Ulica 27 Grudnia, przy której mieści się Muzeum Biżuterii MoJA",
        short="Biżuteria na wystawach stałych i czasowych, obok Okrąglaka i Teatru Polskiego.",
        badge="Wt nieczynne",
        status=None,
        lead="Muzeum Biżuterii MoJA mieści się przy ulicy 27 Grudnia, obok Okrąglaka i Teatru Polskiego, kilka minut pieszo od placu Wolności.",
        sections=[
            ("Co zobaczyć", [
                "Stałe i czasowe wystawy biżuterii oraz sklep z biżuterią artystyczną.",
            ]),
            ("Warto wiedzieć", [
                "Ulgowy bilet przysługuje uczniom, studentom, nauczycielom i seniorom od 60 lat.",
                "Grupy od 10 osób mogą zamówić oprowadzanie przez kuratora i warsztaty (25–40 zł od osoby).",
                "Bilety można kupić online w serwisie tobilet.pl.",
            ]),
        ],
        address="ul. 27 Grudnia 17/19, 61-738 Poznań",
        hours=[("Wtorek", "nieczynne"), ("Pozostałe dni", "10:00–18:00")],
        tickets=[("Normalny", "35 zł"), ("Ulgowy", "15 zł"), ("Dzieci do 6 lat", "bezpłatnie")],
        phone="+48 697 500 029", www=("muzeumbizuterii.com", "https://muzeumbizuterii.com/pl/zaplanuj-wizyte"),
        credit="muzeum-bizuterii-moja",
        sources=[("Muzeum Biżuterii MoJA: zaplanuj wizytę", "https://muzeumbizuterii.com/pl/zaplanuj-wizyte")],
    ),
    dict(
        slug="mieszkanie-illakowiczowny", cat="muzea", name="Mieszkanie-Pracownia Kazimiery Iłłakowiczówny",
        img="mieszkanie-illakowiczowny", img_alt="Ulica Gajowa, przy której mieści się mieszkanie poetki",
        short="Autentyczne mieszkanie poetki i sekretarki Piłsudskiego. Zwiedzanie po zapisach.",
        badge="Po zapisie",
        status=None,
        lead="Muzeum urządzono w mieszkaniu poetki Kazimiery Iłłakowiczówny w pierwszą rocznicę jej śmierci, 16 lutego 1984 roku. Jest oddziałem Biblioteki Raczyńskich i zachowało autentyczne wyposażenie, książki i przedmioty osobiste.",
        sections=[
            ("Co zobaczyć", [
                "Oksfordzki certyfikat językowy poetki, jej debiutancki tomik „Ikarowe loty” z 1911 roku i medale za służbę sanitariuszki w czasie I wojny światowej.",
                "Dokumenty z pracy w polskich ministerstwach, odznaczenia, korespondencję ze znanymi osobami, maskę pośmiertną wykonaną przez Józefę Petrukę i portret pędzla Jadwigi Łubowskiej.",
            ]),
            ("Jak zwiedzać", [
                "Zwiedzający indywidualni mogą przyjść w drugą i ostatnią środę miesiąca o 12:30, po wcześniejszym zapisie.",
                "Grupy zorganizowane przyjmowane są po rezerwacji. Są też oprowadzania tematyczne, m.in. o poglądach politycznych poetki i jej podróżach jako sekretarki marszałka Piłsudskiego.",
            ]),
        ],
        address="ul. Gajowa 4/8, 60-815 Poznań",
        hours=[("Zwiedzający indywidualni", "2. i ostatnia środa miesiąca, 12:30"), ("Grupy", "po rezerwacji")],
        tickets=[("Zapisy i informacje", "tel. 61 855 12 44")],
        phone="+48 61 855 12 44", www=("bracz.edu.pl", "https://bracz.edu.pl/mieszkanie-illakowiczowny/"),
        credit="mieszkanie-illakowiczowny",
        sources=[("Biblioteka Raczyńskich: Mieszkanie-Pracownia Kazimiery Iłłakowiczówny", "https://bracz.edu.pl/mieszkanie-illakowiczowny/")],
    ),
    dict(
        slug="makiety-dawnego-poznania", cat="muzea", name="Makiety Dawnego Poznania",
        img=None, img_alt="",
        short="Poznań z 1618 roku w skali 1:150, z pokazem światła i dźwięku w podziemiach kościoła.",
        badge="Pokazy codziennie",
        status=None,
        lead="W podziemiach kościoła franciszkanów przy ulicy Ludgardy stoją szczegółowe makiety historycznego Poznania, pokazywane z komentarzem, światłem i dźwiękiem.",
        sections=[
            ("Co zobaczyć", [
                "Makietę dawnego Poznania w skali 1:150, odtworzoną na podstawie sztychu z 1618 roku. Ma ponad 2300 obiektów i była pierwszą tak szczegółową makietą historyczną w Polsce.",
                "Makietę Grodu Pierwszych Piastów i makietę Starego Rynku.",
                "Jedna z makiet, w skali 1:100, ma elementy dotykowe i opisy w alfabecie Braille'a dla osób niewidomych.",
            ]),
            ("Warto wiedzieć", [
                "Pokazy zaczynają się o 11:00, 11:45, 12:30, 13:15, 14:00, 14:45, 15:30, 16:15 i 17:00. Od 1 października do 31 marca ostatni pokaz zaczyna się o 15:30.",
                "Bilety kupisz do 15 minut przed pokazem albo w przedsprzedaży. Płatność gotówką lub BLIK-iem.",
                "Z Poznańską Kartą Turystyczną bilet jest o 25% tańszy.",
            ]),
        ],
        address="ul. Ludgardy 1, 61-709 Poznań",
        hours=[("Pokazy, 1.10–31.03", "11:00–15:30, początki co 45 minut"), ("Pokazy, pozostałe miesiące", "11:00–17:00, początki co 45 minut"),
               ("Zamknięte", "1.01, Wielki Piątek, Wielka Sobota, Wielkanoc, Boże Ciało, 31.10, 1.11, 23–25.12, 31.12")],
        tickets=[("Normalny", "35 zł"), ("Wersje obcojęzyczne", "35 zł"), ("Dzieci poniżej 10 lat (wersja polska)", "25 zł"),
                 ("Z Poznańską Kartą Miejską lub Kartą Piasta", "25 zł"), ("Z Poznańską Kartą Turystyczną", "25% taniej")],
        phone="+48 532 651 218", www=("makieta.poznan.pl", "https://www.makieta.poznan.pl/"),
        credit=None,
        sources=[("Visit Poznań: Makiety Dawnego Poznania", "https://visitpoznan.pl/makiety-dawnego-poznania"),
                 ("kultura.poznan.pl: Makiety dawnego Poznania", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/makiety-dawnego-poznania,78932.html")],
    ),
    dict(
        slug="niewidzialna-ulica", cat="muzea", name="Niewidzialna Ulica",
        img="niewidzialna-ulica", img_alt="Kamienica przy ulicy Matejki 53",
        short="Wystawa w całkowitej ciemności, prowadzona przez niewidomych przewodników. Od 7 lat.",
        badge="Pn nieczynne",
        status=None,
        lead="Niewidzialna Ulica to wystawa w całkowitej ciemności, na której poznaje się świat wszystkimi zmysłami poza wzrokiem. Przewodnikami są osoby niewidome i słabowidzące, które dzielą się własnym doświadczeniem.",
        sections=[
            ("Co tu się dzieje", [
                "Zwiedzający pokonują w ciemności codzienne przeszkody, które napotykają osoby niewidome, np. wsiadanie do autobusu czy tramwaju albo omijanie hulajnogi zostawionej na chodniku.",
                "Wewnątrz budynku stoi prawdziwy wagon tramwajowy.",
            ]),
            ("Warto wiedzieć", [
                "Wystawa jest dla osób od 7 lat. Trwa około 30–45 minut.",
                "Grupy zorganizowane przyjmowane są od poniedziałku do piątku od rana, po rezerwacji mailowej. Na życzenie jest przewodnik mówiący po angielsku.",
                "Ceny różnią się w zależności od dnia tygodnia. Aktualny cennik jest na stronie wystawy.",
            ]),
        ],
        address="ul. Matejki 53, 60-770 Poznań",
        hours=[("Poniedziałek", "nieczynne dla indywidualnych"), ("Wtorek–sobota", "12:00–18:00"), ("Niedziela", "12:00–17:00")],
        tickets=[("Ceny biletów", "na niewidzialnaulica.pl")],
        phone=None, www=("niewidzialnaulica.pl", "https://niewidzialnaulica.pl/"),
        credit="niewidzialna-ulica",
        sources=[("poznan.pl: Niewidzialna Ulica", "https://www.poznan.pl/mim/turystyka/nietypowe-atrakcje,poi,4420/-,83693.html"),
                 ("Niewidzialna Ulica", "https://niewidzialnaulica.pl/en/")],
    ),
    dict(
        slug="palac-dzialynskich", cat="zabytki", name="Pałac Działyńskich",
        img="palac-dzialynskich", img_alt="Fasada Pałacu Działyńskich z pelikanem na attyce",
        short="Pałac przy Starym Rynku z pelikanem na attyce, w XIX wieku ośrodek polskości.",
        badge="Bezpłatnie",
        status=None,
        lead="Pałac przy Starym Rynku zbudował w latach 1773–1776 architekt Antoni Höhne dla marszałka wielkiego litewskiego Władysława Rocha Gurowskiego.",
        sections=[
            ("Co zobaczyć", [
                "Okazałą wschodnią fasadę podzieloną pilastrami w porządku korynckim.",
                "Pelikana na obelisku na szczycie attyki. W heraldyce symbolizuje poświęcenie, a w czasach zaborów stał się symbolem polskiego oporu.",
            ]),
            ("Historia", [
                "W XIX wieku pałac był ośrodkiem życia kulturalnego i politycznego Polaków. W Czerwonej Sali odbywały się spotkania związane z powstaniami 1830, 1848 i 1863 roku, wystawy, koncerty i wykłady, m.in. filozofa Augusta Cieszkowskiego.",
                "Dziś mieszczą się tu instytuty naukowe Polskiej Akademii Nauk i oddział Biblioteki Kórnickiej.",
            ]),
        ],
        address="Stary Rynek, 61-772 Poznań",
        hours=[("Fasada", "widoczna całą dobę")],
        tickets=[("Oglądanie fasady", "bezpłatnie")],
        phone=None, www=("poznan.pl", "https://www.poznan.pl/mim/wortals/turystyka/zabytki,poi,2572/"),
        credit="palac-dzialynskich",
        sources=[("Wikipedia: Pałac Działyńskich w Poznaniu", "https://pl.wikipedia.org/wiki/Pałac_Działyńskich_w_Poznaniu")],
    ),
    dict(
        slug="bazar", cat="zabytki", name="Hotel Bazar",
        img="bazar", img_alt="Gmach Hotelu Bazar w Poznaniu",
        short="Gmach z 1838 roku, założony m.in. przez Karola Marcinkowskiego jako ośrodek polskiego życia.",
        badge="Bezpłatnie",
        status=None,
        lead="Bazar powstał z inicjatywy spółki akcyjnej założonej 24 czerwca 1838 roku. W jej komitecie był m.in. lekarz i społecznik Karol Marcinkowski. Budynek stoi na skrzyżowaniu Alej Marcinkowskiego i ulicy Paderewskiego, na skraju Starego Miasta.",
        sections=[
            ("Historia", [
                "Akcjonariusze rezygnowali z zysków na rzecz celów społecznych, a sklepy w Bazarze wynajmowano tylko Polakom.",
                "Działał tu luksusowy hotel ze słynną restauracją, a także liczne polskie organizacje, redakcje gazet (m.in. „Dziennika Poznańskiego”) i instytucje kultury.",
                "Hotel spłonął w 1945 roku i do 1950 roku został odbudowany. W latach 1950–1990 zarządzał nim Orbis, a w 1990 roku budynek odzyskała przedwojenna spółka Bazar Poznański.",
            ]),
        ],
        address="al. Marcinkowskiego / ul. Paderewskiego, 61-745 Poznań",
        hours=[("Fasada", "widoczna całą dobę")],
        tickets=[("Oglądanie gmachu", "bezpłatnie")],
        phone=None, www=("poznan.pl", "https://www.poznan.pl/mim/wortals/turystyka/zabytki,poi,2572/"),
        credit="bazar",
        sources=[("Wikipedia: Hotel Bazar w Poznaniu", "https://pl.wikipedia.org/wiki/Bazar_w_Poznaniu")],
    ),
]
