"""Kalendarz corocznych wydarzeń (strona kalendarz.html i sekcja „Nadchodzące wydarzenia”).

Każde wydarzenie: id, month (miesiąc, w którym zwykle się zaczyna), name, place, when (kiedy zwykle),
dates (start, koniec) bieżącej edycji w formacie RRRR-MM-DD albo None, gdy termin nie jest ogłoszony,
note (o terminie), desc (akapity), link (etykieta, adres), sources.
Sprawdzono 30.09.2026, uzupełniono 01.10.2026 (jedenaście wydarzeń), terminy 2027 i Betlejem zaktualizowano 05.10.2026. Pominięte celowo: Jarmark Świętojański (nie odbył się w 2024 ani 2025,
miasto nie zgadza się na jarmarki na Starym Rynku) i akcja „Poznań za pół ceny” (miasto zrezygnowało).
"""

CAL_CHECKED = "05.10.2026"

CALENDAR = [
    dict(
        id="jarmark-wielkanocny", month=3, name="Jarmark Wielkanocny", place="Plac Wolności",
        when="Przed Wielkanocą, termin zależy od daty świąt",
        dates=("2026-03-21", "2026-03-29"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Stoiska z regionalnymi przysmakami, rękodziełem i świątecznymi wypiekami oraz warsztaty dla dzieci. W 2026 roku jarmark odbył się na Placu Wolności zamiast na Starym Rynku."],
        link=("poznan.pl", "https://www.poznan.pl/mim/smartcity/news,9780/jarmark-wielkanocny-w-poznaniu,274279.html"),
        sources=[("poznan.pl: Jarmark Wielkanocny w Poznaniu (20.03.2026)", "https://www.poznan.pl/mim/smartcity/news,9780/jarmark-wielkanocny-w-poznaniu,274279.html")],
    ),
    dict(
        id="polmaraton", month=4, name="Poznań Półmaraton", place="Ulice Poznania",
        when="Co roku w kwietniu, w niedzielę",
        dates=("2027-04-18", "2027-04-18"), note="Termin edycji 2027 podał organizator.",
        desc=["Bieg na 21,097 km ulicami miasta. W 2026 roku metę minęło 13 505 osób.",
              "W dniu biegu w centrum są duże utrudnienia w ruchu i zmiany tras komunikacji miejskiej."],
        link=("halfmarathon.poznan.pl", "https://halfmarathon.poznan.pl/"),
        sources=[("Poznań Półmaraton (organizator)", "https://halfmarathon.poznan.pl/")],
    ),
    dict(
        id="noc-muzeow", month=5, name="Noc Muzeów", place="Muzea i instytucje kultury w całym mieście",
        when="Co roku w maju, w sobotę",
        dates=("2026-05-16", "2026-05-16"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Jedna noc w roku, gdy muzea, galerie, teatry i inne instytucje kultury są otwarte do późna i przygotowują specjalny program."],
        link=("nocmuzeow.poznan.pl", "https://nocmuzeow.poznan.pl/"),
        sources=[("Noc Muzeów Poznań (organizator)", "https://nocmuzeow.poznan.pl/")],
    ),
    dict(
        id="enter-enea", month=5, name="Enter Enea Festival", place="Jezioro Strzeszyńskie",
        when="Co roku na przełomie maja i czerwca",
        dates=("2027-05-23", "2027-05-26"), note="Termin edycji 2027 podał organizator. Miejsca tej edycji organizator jeszcze nie potwierdził.",
        desc=["Festiwal jazzu i muzyki improwizowanej nad Jeziorem Strzeszyńskim. Dyrektorem artystycznym jest pianista Leszek Możdżer. W 2026 roku odbyła się 16. edycja: 11 koncertów w cztery dni."],
        link=("media.enea.pl", "https://media.enea.pl/pr/870010/enter-enea-festival-swiatowy-jazz-w-poznaniu"),
        sources=[("Enter Enea Festival (organizator): termin 2027", "https://entereneafestival.pl/"),
                 ("Enea: Enter Enea Festival – światowy jazz w Poznaniu (16.05.2026)", "https://media.enea.pl/pr/870010/enter-enea-festival-swiatowy-jazz-w-poznaniu")],
    ),
    dict(
        id="ethno-port", month=6, name="Festiwal Ethno Port", place="Centrum Kultury Zamek, ul. Święty Marcin 80/82",
        when="Co roku w czerwcu",
        dates=("2026-06-11", "2026-06-14"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Festiwal muzyki świata: artyści z wielu krajów oraz polscy wykonawcy muzyki tradycyjnej. W 2026 roku odbyła się 19. edycja."],
        link=("ckzamek.pl", "https://ckzamek.pl/wydarzenia/13969-ethno-port-poznan-2026/"),
        sources=[("CK Zamek: Ethno Port Poznań 2026", "https://ckzamek.pl/wydarzenia/13969-ethno-port-poznan-2026/"),
                 ("CK Zamek: plany na 2026 rok", "https://ckzamek.pl/artykuly/13944-sprawdz-co-planujemy-w-2026-roku/")],
    ),
    dict(
        id="pyrkon", month=6, name="Pyrkon – Festiwal Fantastyki", place="Międzynarodowe Targi Poznańskie",
        when="Co roku, w 2026 roku w czerwcu",
        dates=("2027-06-18", "2027-06-20"), note="Termin edycji 2027 podał organizator.",
        desc=["Festiwal fantastyki: gry, komiksy, cosplay, literatura, film i seriale. W 2026 roku obchodził 25-lecie i miał ponad 2000 punktów programu. Wstęp jest biletowany."],
        link=("pyrkon.pl", "https://pyrkon.pl/"),
        sources=[("Pyrkon: termin i miejsce", "https://pyrkon.pl/en/time-place/"),
                 ("MTP: Pyrkon 2026 – 25 lat i ponad 2000 punktów programu", "https://www.mtp.pl/pl/mtp-targi/pyrkon-2026-25-lat-i-ponad-2000-punktow-programu-sprawdz-szczegoly")],
    ),
    dict(
        id="malta", month=6, name="Malta Festival Poznań", place="Jezioro Maltańskie i miejsca w całym mieście",
        when="Co roku pod koniec czerwca",
        dates=("2026-06-21", "2026-06-28"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Jeden z najważniejszych festiwali sztuki w Polsce: teatr, taniec, muzyka, sztuki wizualne i film. Wiele wydarzeń odbywa się na ulicach i placach. W 2026 roku festiwal otworzyło bezpłatne widowisko nad Jeziorem Maltańskim."],
        link=("malta-festival.pl", "https://malta-festival.pl/"),
        sources=[("Malta Festival: o festiwalu", "https://malta-festival.pl/festiwal/o-festiwalu/"),
                 ("poznan.pl: Malta Festival 2026 starts June 21", "https://www.poznan.pl/mim/wortals/en/wortal,2245/news,9560/malta-festival-2026-starts-june-21-at-lake-malta-free-opening-spectacle-for-love,278244.html")],
    ),
    dict(
        id="maraton", month=10, name="Poznań Maraton", place="Ulice Poznania",
        when="Co roku w październiku, w niedzielę",
        dates=("2026-10-04", "2026-10-04"), note="W 2026 roku 25., jubileuszowa edycja.",
        desc=["Bieg maratoński ulicami miasta, nazwany imieniem Macieja Frankiewicza, byłego zastępcy prezydenta Poznania.",
              "W dniu biegu w wielu częściach miasta są utrudnienia w ruchu i zmiany tras komunikacji miejskiej."],
        link=("marathon.poznan.pl", "https://marathon.poznan.pl/"),
        sources=[("Poznań Maraton (organizator)", "https://marathon.poznan.pl/")],
    ),
    dict(
        id="wieniawski", month=10, name="Międzynarodowy Konkurs Skrzypcowy im. Henryka Wieniawskiego", place="Poznań",
        when="Co pięć lat, w październiku",
        dates=("2026-10-08", "2026-10-25"), note="W 2026 roku 17. edycja. Ostatni koncert laureatów, 25 października, odbywa się w Warszawie.",
        desc=["Międzynarodowy konkurs dla młodych skrzypków, organizowany przez Towarzystwo Muzyczne im. Henryka Wieniawskiego w Poznaniu. Uczestnicy z całego świata grają w kolejnych etapach przesłuchań, a konkurs kończy się finałem i koncertami laureatów. Bilety sprzedaje organizator."],
        link=("wieniawski.pl", "https://wieniawski.pl/xviimks.html"),
        sources=[("Towarzystwo Muzyczne im. H. Wieniawskiego: XVII Konkurs 8–25 X 2026", "https://wieniawski.pl/xviimks.html")],
    ),
    dict(
        id="pga", month=10, name="Poznań Game Arena", place="Międzynarodowe Targi Poznańskie",
        when="Co roku w październiku",
        dates=("2026-10-23", "2026-10-25"), note="W 2026 roku 20., jubileuszowa edycja.",
        desc=["Targi gier komputerowych i rozrywki multimedialnej, według organizatora największe w Europie Środkowo-Wschodniej. Wstęp jest biletowany."],
        link=("gamearena.pl", "https://gamearena.pl/pl/"),
        sources=[("Poznań Game Arena: jubileuszowa edycja już w październiku", "https://gamearena.pl/pl/aktualnosci/jubileuszowa-edycja-juz-w-pazdzierniku/")],
    ),
    dict(
        id="imieniny-sw-marcin", month=11, name="Imieniny Ulicy Święty Marcin", place="ul. Święty Marcin, przy Centrum Kultury Zamek",
        when="Co roku 11 listopada",
        dates=("2026-11-11", "2026-11-11"), note="Zawsze 11 listopada, w Narodowe Święto Niepodległości.",
        desc=["Największe święto miasta, obchodzone od 1994 roku i organizowane przez Centrum Kultury Zamek. Trwa od przedpołudnia do wieczora: kiermasz rogali świętomarcińskich, koncerty, spektakle i atrakcje dla rodzin. Prezydent Poznania przekazuje świętemu Marcinowi klucze do miasta.",
              "Od 2025 roku nie ma korowodu w dawnej formie. Na ulicy powstaje ogrodzone „imieninowe miasteczko” z czterema bramami i kontrolą przy wejściu. Wstęp jest bezpłatny. Walizki, duże torby i plecaki trzeba zostawić w bezpłatnym depozycie przy bramie."],
        link=("ckzamek.pl", "https://ckzamek.pl/podstrony/71-imieniny-ulicy-swiety-marcin/"),
        sources=[("CK Zamek: Imieniny Ulicy Święty Marcin 2025 – informacje praktyczne", "https://ckzamek.pl/artykuly/13267-informacje-praktyczne/"),
                 ("CK Zamek: plany na 2026 rok", "https://ckzamek.pl/artykuly/13944-sprawdz-co-planujemy-w-2026-roku/")],
    ),
    dict(
        id="jarmark-mtp", month=11, name="Jarmark Świąteczny na Targach", place="Międzynarodowe Targi Poznańskie",
        when="Co roku od połowy listopada do przedświątecznego tygodnia",
        dates=("2026-11-14", "2026-12-20"), note="",
        desc=["Jarmark bożonarodzeniowy na terenie Międzynarodowych Targów Poznańskich, kilka minut pieszo od dworca Poznań Główny."],
        link=("jarmark.poznan.pl", "https://jarmark.poznan.pl/pl/"),
        sources=[("Jarmark Świąteczny na Targach (organizator)", "https://jarmark.poznan.pl/pl/")],
    ),
    dict(
        id="betlejem", month=11, name="Betlejem Poznańskie na Placu Wolności i Starym Rynku", place="Plac Wolności i Stary Rynek",
        when="Co roku od drugiej połowy listopada do 6 stycznia",
        dates=("2026-11-20", "2027-01-06"), note="Plac Wolności: od 20 listopada 2026 do 6 stycznia 2027. Stary Rynek: od 21 listopada 2026 do 6 stycznia 2027.",
        desc=["Świąteczne jarmarki w ścisłym centrum: stoiska z ozdobami, rękodziełem i jedzeniem, występy artystów i warsztaty dla dzieci. To jedyny jarmark, który miasto dopuszcza na Starym Rynku."],
        link=("pik.poznan.pl", "https://pik.poznan.pl/jarmark-bozonarodzeniowy-betlejem-poznanskie/"),
        sources=[("Betlejem Poznańskie (organizator): terminy 2026/27", "https://betlejempoznanskie.pl/"),
                 ("PIK Poznań: Jarmark Bożonarodzeniowy – Betlejem Poznańskie", "https://pik.poznan.pl/jarmark-bozonarodzeniowy-betlejem-poznanskie/"),
                 ("ESKA Poznań: nie będzie Jarmarku Świętojańskiego 2025", "https://poznan.eska.pl/nie-bedzie-jarmarku-swietojanskiego-w-poznaniu-mamy-odpowiedz-jarmarki-nie-wpisuja-sie-w-obecne-cele-aa-9jCz-vvgX-b18q.html")],
    ),
    dict(
        id="ice-festival", month=12, name="Poznań Ice Festival", place="Stary Rynek",
        when="Co roku w grudniu",
        dates=("2026-12-11", "2026-12-13"), note="W 2026 roku 20., jubileuszowa edycja.",
        desc=["Festiwal rzeźby lodowej: rzeźbiarze z kilku krajów tworzą na oczach widzów kilkumetrowe rzeźby z brył lodu, piłami mechanicznymi i dłutami. W 2026 roku startuje 24 rzeźbiarzy."],
        link=("poznan.pl", "https://www.poznan.pl/mim/turystyka/news/poznan-ice-festival-wraca-na-stary-rynek,243196.html"),
        sources=[("Codzienny Poznań: Poznań Ice Festival wraca na Stary Rynek (18.09.2026)", "https://codziennypoznan.pl/artykul/2026-09-18/tony-lodu-i-mistrzowie-z-calego-swiata-poznan-ice-festival-wraca-na-stary-rynek-z-jubileuszowa-edycja/")],
    ),
    # ─── Uzupełnienia 01.10.2026 ───
    dict(
        id="targi-ksiazki", month=3, name="Poznańskie Targi Książki", place="Międzynarodowe Targi Poznańskie",
        when="Co roku w marcu",
        dates=("2027-03-12", "2027-03-14"), note="Termin edycji 2027 podał organizator.",
        desc=["Targi wydawców i spotkania z autorami z Polski i zagranicy: od kryminału i reportażu po literaturę dziecięcą. Organizator podaje, że w poprzedniej edycji odbyło się 466 spotkań autorskich. Wstęp jest biletowany."],
        link=("targiksiazki.pl", "https://targiksiazki.pl/"),
        sources=[("Poznańskie Targi Książki (organizator)", "https://targiksiazki.pl/")],
    ),
    dict(
        id="next-fest", month=4, name="NEXT FEST Music Showcase & Conference", place="Kluby i sceny w całym mieście",
        when="Co roku wiosną, zwykle w kwietniu",
        dates=("2027-04-15", "2027-04-17"), note="Termin edycji 2027 podał organizator.",
        desc=["Festiwal nowej muzyki: koncerty debiutantów i znanych wykonawców w kilkunastu klubach i na scenach plenerowych, do tego panele i warsztaty dla branży muzycznej."],
        link=("nextfest.pl", "https://nextfest.pl/"),
        sources=[("NEXT FEST (organizator)", "https://nextfest.pl/"),
                 ("poznan.pl: festiwale", "https://www.poznan.pl/mim/turystyka/festiwale,poi,4240/")],
    ),
    dict(
        id="motor-show", month=4, name="Poznań Motor Show", place="Międzynarodowe Targi Poznańskie",
        when="Co roku wiosną",
        dates=("2027-04-22", "2027-04-25"), note="Termin edycji 2027 podał organizator.",
        desc=["Targi motoryzacyjne: premiery samochodów i motocykli, wystawy i pokazy. Wstęp jest biletowany."],
        link=("motorshow.pl", "https://www.motorshow.pl/pl/"),
        sources=[("Poznań Motor Show (organizator)", "https://www.motorshow.pl/pl/")],
    ),
    dict(
        id="juwenalia", month=5, name="Juwenalia Poznań", place="Park Jana Pawła II (Łęgi Dębińskie)",
        when="Co roku pod koniec maja",
        dates=("2026-05-28", "2026-05-30"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Największe studenckie święto w regionie: trzy dni koncertów na dwóch scenach w parku na Łęgach Dębińskich. Wstęp jest biletowany."],
        link=("juwenalia.poznan.pl", "https://juwenalia.poznan.pl/"),
        sources=[("Juwenalia Poznań (organizator)", "https://juwenalia.poznan.pl/")],
    ),
    dict(
        id="scena-nad-rusalka", month=6, name="Scena nad Rusałką", place="Jezioro Rusałka",
        when="Latem, w czwartkowe wieczory (w 2026 roku od czerwca do końca sierpnia)",
        dates=("2026-06-04", "2026-08-27"), note="Program na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Cykl bezpłatnych koncertów plenerowych nad jeziorem Rusałka. W 2026 roku: trzydniowe otwarcie 4–6 czerwca, a potem koncerty w każdy czwartek od 11 czerwca do 27 sierpnia, razem 33 koncerty."],
        link=("rusalka.poznan.pl", "https://rusalka.poznan.pl/wydarzenia/"),
        sources=[("poznan.pl: koncerty nad Rusałką", "https://www.poznan.pl/mim/smartcity/infoteka,1042/koncerty-nad-rusalka,279900.html"),
                 ("PIK Poznań: Scena nad Rusałką", "https://pik.poznan.pl/scena-nad-rusalka/")],
    ),
    dict(
        id="animator", month=7, name="Międzynarodowy Festiwal Filmów Animowanych Animator", place="Poznań, miejsca festiwalowe w centrum",
        when="Co roku w lipcu",
        dates=("2027-07-03", "2027-07-11"), note="Termin 20. edycji (2027) podał organizator.",
        desc=["Największy festiwal filmu animowanego w Polsce: około 300 filmów z całego świata, retrospektywy i premiery. Od 2017 roku zwycięzca konkursu międzynarodowego może ubiegać się o nominację do Oscara. Organizuje go Estrada Poznańska."],
        link=("animator-festival.com", "https://animator-festival.com/"),
        sources=[("Animator (organizator)", "https://animator-festival.com/"),
                 ("poznan.pl: festiwale", "https://www.poznan.pl/mim/turystyka/festiwale,poi,4240/")],
    ),
    dict(
        id="blue-summer-jazz", month=7, name="Blue Summer Jazz Festival", place="Park Starego Browaru",
        when="Co roku w lipcu, przez dwa wieczory",
        dates=("2027-07-17", "2027-07-18"), note="Termin edycji 2027 podał organizator.",
        desc=["Plenerowa, wakacyjna odsłona klubu Blue Note: jazz, soul i funk na scenie w Parku Starego Browaru. Wstęp jest biletowany."],
        link=("bluesummerjazz.pl", "https://bluesummerjazz.pl/"),
        sources=[("Blue Summer Jazz Festival (organizator)", "https://bluesummerjazz.pl/")],
    ),
    dict(
        id="swieto-bamberskie", month=8, name="Festiwal Tradycji Poznańskich i Święto Bamberskie", place="Stary Rynek i okolice",
        when="Co roku w pierwszy weekend sierpnia",
        dates=("2026-07-29", "2026-08-02"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Święto upamiętnia przybycie Bambrów, osadników spod Bambergu. Najważniejszy jest korowód w strojach bamberskich: w 2026 roku przeszedł 2 sierpnia z ul. Mostowej na Stary Rynek, gdzie przed ratuszem odczytano historyczny kontrakt i udekorowano girlandą figurę Bamberki.",
              "Festiwalowi towarzyszą warsztaty, pokazy i koncerty."],
        link=("festiwaltradycjipoznanskich.eu", "https://festiwaltradycjipoznanskich.eu/"),
        sources=[("Festiwal Tradycji Poznańskich (organizator)", "https://festiwaltradycjipoznanskich.eu/"),
                 ("naszemiasto.pl: program 2026", "https://poznan.naszemiasto.pl/potancowka-korowod-i-darmowe-koncerty-rusza-festiwal-tradycji-poznanskich-i-31-swieto-bamberskie-sprawdz-program/ar/c1p2-29219423")],
    ),
    dict(
        id="festiwal-dobrego-smaku", month=8, name="Ogólnopolski Festiwal Dobrego Smaku", place="Plac Wolności",
        when="Co roku w sierpniu",
        dates=("2026-08-21", "2026-08-23"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Jedna z największych imprez kulinarnych w Polsce: Jarmark Dobrego Smaku z regionalnymi produktami, pokazy kulinarne, warsztaty i koncerty. W 2026 roku odbyła się 20. edycja, pierwszy raz na Placu Wolności. Wstęp jest wolny."],
        link=("ofds.pl", "https://ofds.pl/"),
        sources=[("Ogólnopolski Festiwal Dobrego Smaku (organizator)", "https://ofds.pl/")],
    ),
    dict(
        id="ale-kino", month=11, name="Ale Kino! – Międzynarodowy Festiwal Filmów dla Młodej Widowni", place="Centrum Kultury Zamek (Kino Pałacowe) i inne miejsca festiwalowe",
        when="Co roku pod koniec listopada, przez osiem dni",
        dates=("2026-11-22", "2026-11-29"), note="Termin 44. edycji podał organizator.",
        desc=["Festiwal filmów dla dzieci i młodzieży: animacje, fabuły i dokumenty z całego świata. Kontynuuje przegląd zapoczątkowany w 1963 roku. Seanse są biletowane."],
        link=("alekino.com", "https://alekino.com/"),
        sources=[("Ale Kino! (organizator)", "https://alekino.com/"),
                 ("poznan.pl: festiwale", "https://www.poznan.pl/mim/turystyka/festiwale,poi,4240/")],
    ),
    dict(
        id="rocznica-powstania", month=12, name="Rocznica wybuchu Powstania Wielkopolskiego", place="Centrum Poznania",
        when="Co roku 26 i 27 grudnia",
        dates=("2026-12-26", "2026-12-27"), note="Szczegółowy program na 2026 rok nie jest jeszcze ogłoszony.",
        desc=["27 grudnia to Narodowy Dzień Zwycięskiego Powstania Wielkopolskiego. W 2025 roku program wyglądał tak: 26 grudnia inscenizacja przyjazdu Ignacego Paderewskiego pociągiem na Dworzec Letni, a 27 grudnia msza w Farze, uroczystości pod pomnikiem, minuta ciszy o 16:40 (zatrzymują się tramwaje i autobusy, wyją syreny) i wieczorny marsz spod hotelu Bazar."],
        link=("poznan.pl", "https://www.poznan.pl/mim/info/news/107-rocznica-powstania-wielkopolskiego-w-poznaniu-bedzie-sie-dzialo,269074.html"),
        sources=[("poznan.pl: 107. rocznica Powstania Wielkopolskiego", "https://www.poznan.pl/mim/info/news/107-rocznica-powstania-wielkopolskiego-w-poznaniu-bedzie-sie-dzialo,269074.html"),
                 ("MPK Poznań: obchody 27 grudnia 2025", "https://www.mpk.poznan.pl/komunikaty/obchody-107-rocznicy-wybuchu-powstania-wielkopolskiego-27-grudnia-2025-r/")],
    ),
]
