# -*- coding: utf-8 -*-
"""Partie 5–6 (29.09.2026): forty, jeziora, parki, Okrąglak, linie turystyczne.
Źródła: portal miasta poznan.pl (kategorie Fortyfikacje, Jeziora, Parki,
Inne atrakcje), MPK Poznań, Wikipedia. Opisy streszczone własnymi słowami."""

P = "https://www.poznan.pl/mim/wortals/turystyka/"

FINAL = [
    dict(
        slug="twierdza-poznan", cat="zabytki", name="Twierdza Poznań",
        img="twierdza-poznan", img_alt="Kaponiera Kolejowa, fragment dawnej Twierdzy Poznań",
        short="Pruskie fortyfikacje z XIX wieku: Cytadela, pierścień 18 fortów i relikty w centrum miasta.",
        badge="Bezpłatnie",
        status=None,
        lead="W XIX wieku Prusacy zamienili Poznań w twierdzę. Najpierw, w latach 1828–1869, powstała twierdza poligonalna, a od lat 70. XIX wieku wokół miasta zbudowano pierścień fortów.",
        sections=[
            ("Twierdza poligonalna", [
                "Składała się z dużego fortu na Wzgórzu Winiarskim (dzisiejsza Cytadela), umocnień na prawym brzegu Warty (m.in. Ostrów Tumski, Śródka i Malta) oraz rdzenia na lewym brzegu. Wzdłuż dawnych umocnień biegną dziś ulice Kościuszki i Kazimierza Wielkiego.",
                "W 1902 roku zdecydowano o likwidacji rdzenia na lewym brzegu. Rozbiórki trwały też po odzyskaniu niepodległości i po II wojnie światowej, więc z tej części twierdzy zostały tylko fragmenty.",
            ]),
            ("Twierdza fortowa", [
                "W drugiej połowie XIX wieku twierdzę zmodernizowano. Zaplanowano dziewięć fortów głównych i dziewięć pośrednich. Forty główne zbudowano w latach 1873–1884 według standardowego pruskiego projektu gen. von Biehlera: na planie pięciokąta, z fosą i wałem artyleryjskim.",
            ]),
            ("Gdzie zobaczyć relikty", [
                "Cytadela z pozostałościami Fortu Winiary oraz Fort VII z Muzeum Martyrologii Wielkopolan.",
                "Fort III na terenie Nowego Zoo oraz Fort IVa i Fort Va, udostępniane w wybrane dni.",
                "Fragmenty Kaponiery Kolejowej pod Rondem Kaponiera, fragment arsenału przy ulicy Garbary i zachodni przyczółek Śluzy Katedralnej przy Bramie Poznania.",
            ]),
        ],
        address="Poznań (wiele lokalizacji) 61-001",
        hours=[("Relikty w mieście", "dostępne z zewnątrz"), ("Forty", "godziny na stronach poszczególnych fortów")],
        tickets=[("Oglądanie reliktów", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "fortyfikacje,poi,2575/dawna-twierdza-poznan,45909.html"),
        credit="twierdza-poznan",
        sources=[("poznan.pl: Dawna twierdza Poznań", P + "fortyfikacje,poi,2575/dawna-twierdza-poznan,45909.html")],
    ),
    dict(
        slug="fort-iva", cat="zabytki", name="Fort IVa",
        img="fort-iva", img_alt="Fort IVa w Poznaniu",
        short="Pruski fort z 1881 roku, dziś zimowisko nietoperzy. Zwiedzanie w pierwsze niedziele miesiąca.",
        badge="1. niedziela miesiąca",
        status=None,
        lead="Fort IVa na Wilczym Młynie zbudowała armia pruska w latach 1878–1881. To jeden z 18 fortów drugiego pierścienia Twierdzy Poznań i jeden z sześciu fortów pośrednich nowego typu.",
        sections=[
            ("Historia", [
                "W 1888 roku fort zmodernizowano i wzmocniono, m.in. dobudowując kaponiery rewersowe i mury chroniące przed podmuchem.",
                "W okresie międzywojennym Wojsko Polskie trzymało tu magazyny. W koszarach zachowały się podpisy żołnierzy.",
                "W czasie walk o Poznań w 1945 roku fort bronił się tylko dwie godziny. Ślady walk widać na ścianach w podziemiach. W latach 1952–1965 fort wysadzono i częściowo rozebrano.",
            ]),
            ("Dziś", [
                "W 1997 roku opiekę nad fortem przejęli harcerze, którzy razem z Polskim Towarzystwem Ochrony Przyrody „Salamandra” zabezpieczyli podziemia.",
                "Podziemia są zimowiskiem nietoperzy kilku gatunków, m.in. nocka dużego, nocka rudego, nocka Natterera i gacka brunatnego.",
            ]),
            ("Warto wiedzieć", [
                "Wizytę trzeba wcześniej zgłosić telefonicznie. Można też umówić inny termin.",
            ]),
        ],
        address="Wilczy Młyn, 61-602 Poznań",
        hours=[("Zwiedzanie", "1. niedziela miesiąca, 10:00–14:00"), ("Zgłoszenie", "wcześniej, telefonicznie")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone="+48 508 977 083", www=("poznan.pl", P + "fortyfikacje,poi,2575/fort-iva,54056.html"),
        credit="fort-iva",
        sources=[("poznan.pl: Fort IVa", P + "fortyfikacje,poi,2575/fort-iva,54056.html")],
    ),
    dict(
        slug="fort-va", cat="zabytki", name="Fort Va Bonin",
        img="fort-va", img_alt="Fort Va Bonin w Poznaniu",
        short="Pruski fort z przewodnikiem w historycznym mundurze. Od maja do września, w ostatnie soboty.",
        badge="Sezonowo",
        status=None,
        lead="Fort Va zbudowała armia pruska w latach 1887–1890 i nazwała Bonin. Należy do drugiego pierścienia Twierdzy Poznań. Trasa turystyczna prowadzi przez najważniejsze części fortu, nad ziemią i pod nią.",
        sections=[
            ("Zwiedzanie", [
                "Fort zwiedza się wyłącznie z przewodnikiem ubranym w historyczny mundur. Trasa trwa około godziny.",
                "Fortem opiekuje się i prowadzi trasę Stowarzyszenie Miłośników Fortyfikacji Kernwerk.",
                "Grupy zorganizowane (od 15 osób) mogą po wcześniejszym kontakcie zwiedzać fort w inne dni.",
            ]),
        ],
        address="ul. Lechicka 59, 61-695 Poznań",
        hours=[("Maj–wrzesień", "ostatnia sobota miesiąca"), ("Wejścia", "12:00 i 15:00")],
        tickets=[("Normalny", "15 zł"), ("Ulgowy", "10 zł")],
        phone="+48 506 737 222", www=("kernwerk.pl", "https://www.kernwerk.pl/"),
        credit="fort-va",
        sources=[("poznan.pl: Fort Va Bonin", P + "fortyfikacje,poi,2575/fort-va-bonin,52714.html")],
    ),
    dict(
        slug="jezioro-kierskie", cat="przyroda", name="Jezioro Kierskie",
        img="jezioro-kierskie", img_alt="Jezioro Kierskie",
        short="Największe jezioro Poznania: żeglarstwo, kąpieliska i 12 km brzegu do spacerów.",
        badge="Bezpłatnie",
        status=None,
        lead="Jezioro Kierskie to wydłużona rynna ciągnąca się od Krzyżownik do Kiekrza, długa na około 4,5 km i szeroka na kilkaset metrów. Ma 285 hektarów powierzchni i 37,6 metra głębokości.",
        sections=[
            ("Co tu robić", [
                "Żeglować. W 1933 roku w Kiekrzu powstał Jacht Klub Wielkopolski, a dziś przystanie ma tu kilkanaście klubów żeglarskich.",
                "Spacerować i jeździć na rowerze wzdłuż ponad 12 km linii brzegowej.",
                "Latem kąpać się na strzeżonych kąpieliskach w Krzyżownikach i Kiekrzu. Zimą na jeziorze pływają bojery.",
                "Łowić ryby, m.in. sielawę, węgorza, sandacza i szczupaka. Jezioro jest dostępne dla wędkarzy przez cały rok.",
            ]),
            ("Warto wiedzieć", [
                "Niedaleko, w Krzyżownikach, znajduje się Przeciwatomowy Schron i Galeria Plakatu.",
                "Źródła podają różne wymiary jeziora. Portal miasta pisze o długości 4,8 km i szerokości 2,1 km, a Wikipedia o około 4,3–4,5 km długości i szerokości do 0,8 km. Szerokość 2,1 km nie pasuje do powierzchni 285 ha, dlatego w opisie przyjęliśmy dane z Wikipedii.",
            ]),
        ],
        address="Jezioro Kierskie, Poznań-Kiekrz 60-480",
        hours=[("Teren wokół jeziora", "dostępny całą dobę"), ("Kąpieliska strzeżone", "w sezonie letnim")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "jeziora,poi,2574/jezioro-kierskie,41236.html"),
        credit="jezioro-kierskie",
        sources=[("poznan.pl: Jezioro Kierskie", P + "jeziora,poi,2574/jezioro-kierskie,41236.html"),
                 ("Wikipedia: Jezioro Kierskie", "https://pl.wikipedia.org/wiki/Jezioro_Kierskie")],
    ),
    dict(
        slug="jezioro-strzeszynskie", cat="przyroda", name="Jezioro Strzeszyńskie",
        img="jezioro-strzeszynskie", img_alt="Jezioro Strzeszyńskie wśród lasów",
        short="Najczystsze z dużych jezior Poznania, wśród lasów, z kąpieliskiem i campingiem.",
        badge="Bezpłatnie",
        status=None,
        lead="Jezioro Strzeszyńskie to naturalny zbiornik wśród lasów na północno-zachodnim krańcu Poznania, około 10 km od centrum. Jest najczystszym z dużych jezior w mieście.",
        sections=[
            ("O jeziorze", [
                "Ma 34,9 hektara powierzchni i 17,8 metra głębokości. Otaczają je lasy liściaste i sosnowe.",
                "Żyją tu m.in. sielawa, sieja, węgorz, szczupak i okoń.",
            ]),
            ("Warto wiedzieć", [
                "Nad jeziorem działa ośrodek z kąpieliskiem, noclegami, całoroczną restauracją, domkami i campingiem.",
            ]),
        ],
        address="Jezioro Strzeszyńskie, Poznań-Strzeszyn 60-479",
        hours=[("Teren wokół jeziora", "dostępny całą dobę")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "jeziora,poi,2574/jezioro-strzeszynskie,41239.html"),
        credit="jezioro-strzeszynskie",
        sources=[("poznan.pl: Jezioro Strzeszyńskie", P + "jeziora,poi,2574/jezioro-strzeszynskie,41239.html")],
    ),
    dict(
        slug="szachty", cat="przyroda", name="Szachty",
        img="szachty", img_alt="Wieża widokowa na Szachtach",
        short="Stawy w dawnych gliniankach, 25-metrowa wieża widokowa i ścieżka przyrodnicza. Wstęp wolny.",
        badge="Wstęp wolny",
        status=None,
        lead="Szachty to tereny dawnych glinianek, gdzie kiedyś działało centrum przemysłu ceglanego. Dziś to miejsce spacerów, wycieczek rowerowych i obserwacji przyrody.",
        sections=[
            ("Co zobaczyć", [
                "Wieżę widokową o wysokości 25 metrów, od strony ulicy Mieleszyńskiej. Po 120 stopniach widać panoramę Poznania: wieżowce, stadion i biurowce w centrum.",
                "Staw Edy z punktami widokowymi i Staw Rozlany z pomostem, z którego widać platformy lęgowe rybitw, kaczki i łabędzie.",
                "Dom Kindlera z około 1910 roku, zbudowany z cegły z tutejszej produkcji, przy wejściu od ulicy Leszczyńskiej.",
                "Tablice edukacyjne o roślinach i zwierzętach wzdłuż alejek.",
            ]),
            ("Warto wiedzieć", [
                "Przy wieży jest plac zabaw.",
                "Przy Stawie Edy można bezpłatnie skorzystać z miejsca na ognisko po wcześniejszym zgłoszeniu mailowym do Zarządu Zieleni Miejskiej.",
                "Dojazd autobusami do przystanków Kowalewicka n/ż lub Glinianki n/ż. Parkingi są przy ulicach Mieleszyńskiej i Witaszka.",
            ]),
        ],
        address="ul. Mieleszyńska / ul. Witaszka, 60-113 Poznań",
        hours=[("Teren i wieża", "ogólnodostępne")],
        tickets=[("Wstęp i wieża widokowa", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "parki,poi,3338/szachty,86752.html"),
        credit="szachty",
        sources=[("poznan.pl: Szachty", P + "parki,poi,3338/szachty,86752.html")],
        see_also=[("Punkty widokowe w Poznaniu: wszystkie wieże i tarasy", "punkty-widokowe")],
    ),
    dict(
        slug="legi-debinskie", cat="przyroda", name="Łęgi Dębińskie (Park Jana Pawła II)",
        img="legi-debinskie", img_alt="Pomnik Pyry w Parku Jana Pawła II",
        short="Trzeci co do wielkości park Poznania z Pomnikiem Pyry i miejscem papieskiej mszy z 1983 roku.",
        badge="Bezpłatnie",
        status=None,
        lead="Park Jana Pawła II, zwany Łęgami Dębińskimi, to trzeci co do wielkości park w Poznaniu, po Cytadeli i Parku Tysiąclecia. Ma nieco ponad 18,5 hektara.",
        sections=[
            ("Historia", [
                "Nazwa upamiętnia wizytę Jana Pawła II w Poznaniu. 20 czerwca 1983 roku papież odprawił tu mszę dla około miliona wiernych. Było to największe zgromadzenie w historii miasta, które upamiętnia Krzyż Papieski przy ulicy Ojca Mariana Żelazka.",
            ]),
            ("Co zobaczyć", [
                "Pomnik Pyry: pięciotonowy głaz narzutowy w kształcie ziemniaka, sprowadzony spod Stęszewa i odsłonięty we wrześniu 2007 roku w czasie Dni Pyrlandii.",
                "Rozległe łąki, alejki z ławkami, siłownię plenerową, street workout i ścieżkę zdrowia.",
            ]),
            ("Dla rodzin", [
                "Dwa place zabaw, w tym karuzelę integracyjną dla dzieci z niepełnosprawnością ruchową, oraz wybieg dla psów.",
                "Dojazd tramwajami 2, 9, 18 i 19 albo autobusem 176 (przystanek Żelazka n/ż).",
            ]),
        ],
        address="ul. Dolna Wilda / ul. Ojca Mariana Żelazka, 61-553 Poznań",
        hours=[("Park", "ogólnodostępny")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "parki,poi,3338/park-jana-pawla-ii-legi-debinskie,52018.html"),
        credit="legi-debinskie",
        sources=[("poznan.pl: Park Jana Pawła II (Łęgi Dębińskie)", P + "parki,poi,3338/park-jana-pawla-ii-legi-debinskie,52018.html")],
    ),
    dict(
        slug="park-wilsona", cat="przyroda", name="Park Wilsona",
        img="park-wilsona", img_alt="Pomnik Wilsona i kwiaty w Parku Wilsona",
        short="Dawny pierwszy ogród botaniczny Poznania, z pomnikiem Wilsona, muszlą koncertową i Palmiarnią.",
        badge="Bezpłatnie",
        status=None,
        lead="Park Wilsona na Łazarzu powstał jako pierwszy ogród botaniczny Poznania. Założono go w 1902 roku i ukończono w 1904 roku według projektu Hermanna Kube. Ma 7,2 hektara.",
        sections=[
            ("Historia", [
                "Już w 1834 roku Towarzystwo Upiększania Miasta założyło tu szkółkę drzew. Ogród botaniczny działał do 1925 roku.",
                "W latach 1951–1990 park nosił imię Marcina Kasprzaka. W 1990 roku wrócił do imienia prezydenta USA Woodrowa Wilsona, który przyczynił się do odzyskania przez Polskę niepodległości w 1918 roku.",
                "W 1931 roku odsłonięto tu pomnik Wilsona dłuta Gutzona Borgluma, twórcy rzeźb na Mount Rushmore.",
            ]),
            ("Co zobaczyć", [
                "Betonową muszlę koncertową z 1936 roku.",
                "Rzeźbę „Perseusz i Andromeda” z 1891 roku, przeniesioną do parku w 1956 roku.",
                "Palmiarnię Poznańską, obecnie zamkniętą z powodu przebudowy.",
            ]),
        ],
        address="ul. Śniadeckich 30, 61-001 Poznań",
        hours=[("Park", "codziennie 5:00–22:00")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("palmiarnia.poznan.pl", "https://palmiarnia.poznan.pl/park-wilsona/godziny-otwarcia/"),
        credit="park-wilsona",
        sources=[("Palmiarnia Poznańska: godziny otwarcia Parku Wilsona", "https://palmiarnia.poznan.pl/park-wilsona/godziny-otwarcia/"),
                 ("poznan.pl: Park Thomasa Woodrowa Wilsona", "https://www.poznan.pl/mim/turystyka/-,p,112,142.html"),
                 ("Wikipedia: Park Wilsona w Poznaniu", "https://pl.wikipedia.org/wiki/Park_Wilsona_w_Poznaniu")],
    ),
    dict(
        slug="park-chopina", cat="przyroda", name="Park Chopina",
        img="park-chopina", img_alt="Park Chopina w Poznaniu",
        short="Kameralny park za Kolegium Jezuickim, z popiersiem Chopina, dwa kroki od Starego Rynku.",
        badge="Bezpłatnie",
        status=None,
        lead="Park Chopina leży przy ulicy Podgórnej, na zapleczu dawnego Kolegium Jezuickiego, tuż obok Starego Rynku. Ma 1,8 hektara.",
        sections=[
            ("Historia", [
                "Na początku XVIII wieku jezuici urządzili tu ogród, który służył też jako ogród botaniczny do lekcji przyrody.",
                "Od 1815 roku ogród należał do rezydencji namiestnika Antoniego Radziwiłła, który zamienił go w park. W 1961 roku park otwarto dla publiczności i nazwano imieniem Chopina.",
            ]),
            ("Co zobaczyć", [
                "Marmurowe popiersie Fryderyka Chopina dłuta Marcina Rożka.",
                "Stare drzewa, m.in. lipę drobnolistną o obwodzie około 3 metrów, jawor, dąb i platan.",
            ]),
            ("Warto wiedzieć", [
                "Dojazd tramwajami 3, 5, 8, 13 i 16 do przystanku Wrocławska albo 6, 9, 12 i 19 do przystanku Pl. Wiosny Ludów.",
            ]),
        ],
        address="ul. Podgórna, 61-829 Poznań",
        hours=[("Park", "ogólnodostępny")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "parki,poi,3338/park-fryderyka-chopina,51944.html"),
        credit="park-chopina",
        sources=[("poznan.pl: Park Fryderyka Chopina", P + "parki,poi,3338/park-fryderyka-chopina,51944.html")],
    ),
    dict(
        slug="park-marcinkowskiego", cat="przyroda", name="Park Marcinkowskiego",
        img="park-marcinkowskiego", img_alt="Park Marcinkowskiego w Poznaniu",
        short="Park z 1906 roku przy dworcu, z popiersiem Słowackiego, które przetrwało wojnę zakopane w ziemi.",
        badge="Bezpłatnie",
        status=None,
        lead="Park Marcinkowskiego zaczęto budować w 1905 roku na dawnych terenach fortecznych, a otwarto w 1906 roku. Ma 9,5 hektara i leży niedaleko dworca Poznań Główny.",
        sections=[
            ("Historia", [
                "Park nosił początkowo imię Fryderyka Schillera. Obecną nazwę, na cześć lekarza i społecznika Karola Marcinkowskiego, dostał w 1919 roku.",
                "Po II wojnie światowej park powiększono o tereny dawnych cmentarzy. Na zlikwidowanym w 1959 roku cmentarzu parafii św. Marcina do 1923 roku był grób Karola Marcinkowskiego.",
            ]),
            ("Co zobaczyć", [
                "Popiersie Juliusza Słowackiego z białego marmuru dłuta Władysława Marcinkowskiego, odsłonięte w 1923 roku. W czasie okupacji zakopali je robotnicy ogrodów miejskich, a na miejsce wróciło w 1950 roku.",
                "Rzeźbę pawia z dziewczynką autorstwa Anny Krzymańskiej nad stawem.",
                "Leszczynę turecką o obwodzie pnia 200 cm, chronioną jako pomnik przyrody.",
            ]),
            ("Dla rodzin", [
                "Dwa place zabaw, boisko, siłownię plenerową i skatepark.",
                "Dojazd tramwajami 5, 6, 12 i 17 do przystanku Poznań Główny.",
            ]),
        ],
        address="al. Niepodległości / ul. Stanisława Matyi, 61-874 Poznań",
        hours=[("Park", "ogólnodostępny")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "parki,poi,3338/park-karola-marcinkowskiego,51950.html"),
        credit="park-marcinkowskiego",
        sources=[("poznan.pl: Park Karola Marcinkowskiego", P + "parki,poi,3338/park-karola-marcinkowskiego,51950.html")],
    ),
    dict(
        slug="park-mickiewicza", cat="przyroda", name="Park Mickiewicza",
        img="park-mickiewicza", img_alt="Park Mickiewicza z fontanną przed Teatrem Wielkim",
        short="Reprezentacyjny park przed Teatrem Wielkim, z fontanną i platanami, obok Poznańskich Krzyży.",
        badge="Bezpłatnie",
        status=None,
        lead="Park Mickiewicza powstał w latach 1907–1910 na terenie dawnych fortyfikacji, jako część Dzielnicy Cesarskiej zaprojektowanej przez Josepha Stübbena. Jego założenie jest ściśle związane z gmachem Teatru Wielkiego.",
        sections=[
            ("Co zobaczyć", [
                "Długi basen z wysoko tryskającą fontanną i reprezentacyjne schody przed Teatrem Wielkim im. Stanisława Moniuszki.",
                "Szpalery platanów, od 2023 roku chronione jako pomnik przyrody.",
                "Południową część parku, która przechodzi w plac Mickiewicza z pomnikiem Adama Mickiewicza i Pomnikiem Poznańskiego Czerwca 1956.",
            ]),
            ("Warto wiedzieć", [
                "Park leży naprzeciw Zamku Cesarskiego, więc łatwo połączyć go ze zwiedzaniem Dzielnicy Cesarskiej.",
                "Dojazd tramwajem do przystanków Fredry lub Zamek.",
            ]),
        ],
        address="ul. Wieniawskiego / al. Niepodległości, 61-712 Poznań",
        hours=[("Park", "ogólnodostępny")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "parki,poi,3338/park-adama-mickiewicza,51951.html"),
        credit="park-mickiewicza",
        sources=[("poznan.pl: Park Adama Mickiewicza", P + "parki,poi,3338/park-adama-mickiewicza,51951.html")],
    ),
    dict(
        slug="okraglak", cat="wspolczesny", name="Okrąglak",
        img="okraglak", img_alt="Dom Towarowy Okrąglak przy ulicy Mielżyńskiego",
        short="Cylindryczny dom towarowy z 1954 roku, symbol poznańskiego modernizmu.",
        badge="Bezpłatnie",
        status=None,
        lead="Dom Towarowy „Okrąglak”, zaprojektowany przez prof. Marka Leykama, to symbol poznańskiego modernizmu. Otwarto go 29 stycznia 1954 roku na rogu ulic 27 Grudnia i Mielżyńskiego, w miejscu przedwojennego Banku Cukrownictwa.",
        sections=[
            ("Co zobaczyć", [
                "Budynek w kształcie walca, rozpoznawalny z daleka.",
                "Wewnątrz środek budynku zajmuje cylindryczna, otwarta na całą wysokość przestrzeń z trzema skrzydłami krętych schodów prowadzących na każde piętro.",
            ]),
            ("Warto wiedzieć", [
                "Tuż obok jest Muzeum Biżuterii MoJA i Teatr Polski.",
            ]),
        ],
        address="ul. Mielżyńskiego 14, 61-725 Poznań",
        hours=[("Budynek z zewnątrz", "widoczny całą dobę")],
        tickets=[("Oglądanie budynku", "bezpłatnie")],
        phone=None, www=("poznan.pl", P + "inne-atrakcje,poi,3391/dom-towarowy-okraglak,51457.html"),
        credit="okraglak",
        sources=[("poznan.pl: Dom Towarowy „Okrąglak”", P + "inne-atrakcje,poi,3391/dom-towarowy-okraglak,51457.html")],
    ),
    dict(
        slug="linie-turystyczne", cat="rodzina", name="Zabytkowe tramwaje i autobusy (linie turystyczne)",
        img="linie-turystyczne", img_alt="Zabytkowy tramwaj Konstal 105N na linii turystycznej 0",
        short="Przejazd zabytkowym tramwajem albo „Ogórkiem”. Kursują w sezonie, w weekendy i święta.",
        badge="Sezonowo",
        status=("warning", "Linie turystyczne kursują w sezonie letnim, głównie w weekendy i święta. Przed wyjazdem sprawdź aktualny rozkład na stronie MPK Poznań."),
        lead="W sezonie letnim na ulice Poznania wyjeżdżają historyczne tramwaje i autobusy MPK. Tramwajowa linia turystyczna 0 kursuje od 1999 roku, a autobusowa od 2005 roku.",
        sections=[
            ("Linie w sezonie 2026", [
                "Tramwaj 0 (niedziele i wybrane święta): zabytkowe wagony między Biblioteką Uniwersytecką a przystankiem 27 Grudnia-Teatr Polski. Odjazdy o 12:30, 13:30, 14:30, 16:00 i 17:00.",
                "Tramwaj 20 (soboty): ta sama trasa, obsługiwana przez szybsze zabytkowe tramwaje, w tych samych godzinach.",
                "Autobus 100 (weekendy i święta): z dworca Poznań Główny do Nowego Zoo, co 40 minut w godzinach 9:40–17:40.",
                "Autobus 102 (soboty): z dworca Poznań Główny do Muzeum Broni Pancernej, odjazdy o 10:00 i 12:00.",
                "W wybrane dni kursują też historyczne linie H (tramwaj) i A (autobus). Terminy MPK ogłasza osobno.",
            ]),
            ("Bilety", [
                "Bilety sprzedaje konduktor w pojeździe. Można płacić gotówką lub kartą.",
            ]),
        ],
        address="przystanek Biblioteka Uniwersytecka (ul. Ratajczaka: 61-815) / dworzec Poznań Główny, 61-896 Poznań",
        hours=[("Sezon", "letni, weekendy i święta"), ("Rozkład", "na mpk.poznan.pl")],
        tickets=[("Jednorazowy", "7 zł, ulgowy 5 zł"), ("Dzienny", "12 zł, ulgowy 9 zł")],
        phone=None, www=("mpk.poznan.pl", "https://www.mpk.poznan.pl/strefa-pasazera/turystyka/linie-turystyczne/"),
        credit="linie-turystyczne",
        sources=[("MPK Poznań: linie turystyczne", "https://www.mpk.poznan.pl/strefa-pasazera/turystyka/linie-turystyczne/"),
                 ("poznan.pl: Sezonowe linie turystyczne", P + "inne-atrakcje,poi,3391/sezonowe-linie-turystyczne,74590.html")],
    ),
]
