"""Kalendarz corocznych wydarzeń (strona kalendarz.html i sekcja „Nadchodzące wydarzenia”).

Każde wydarzenie: id, month (miesiąc, w którym zwykle się zaczyna), name, place, when (kiedy zwykle),
dates (start, koniec) bieżącej edycji w formacie RRRR-MM-DD albo None, gdy termin nie jest ogłoszony,
note (o terminie), desc (akapity), link (etykieta, adres), sources.
Sprawdzono 30.09.2026. Pominięte celowo: Jarmark Świętojański (nie odbył się w 2024 ani 2025,
miasto nie zgadza się na jarmarki na Starym Rynku) i akcja „Poznań za pół ceny” (miasto zrezygnowało).
"""

CAL_CHECKED = "30.09.2026"

CALENDAR = [
    dict(
        id="jarmark-wielkanocny", month=3, name="Jarmark Wielkanocny", place="Plac Wolności",
        when="Przed Wielkanocą, termin zależy od daty świąt",
        dates=("2026-03-21", "2026-03-29"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Stoiska z regionalnymi przysmakami, rękodziełem i świątecznymi wypiekami oraz warsztaty dla dzieci. W 2026 roku jarmark odbył się na Placu Wolności zamiast na Starym Rynku."],
        link=("poznan.pl", "https://www.poznan.pl/mim/smartcity/news,9780/jarmark-wielkanocny-w-poznaniu,274279.html"),
        sources=[("poznan.pl: Jarmark Wielkanocny w Poznaniu (20.03.2026)", "https://www.poznan.pl/mim/smartcity/news,9780/jarmark-wielkanocny-w-poznaniu,274279.html")],
    ),
    dict(
        id="polmaraton", month=4, name="Poznań Półmaraton", place="Ulice Poznania",
        when="Co roku w kwietniu, w niedzielę",
        dates=("2026-04-19", "2026-04-19"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Bieg na 21,097 km ulicami miasta. W 2026 roku metę minęło 13 505 osób.",
              "W dniu biegu w centrum są duże utrudnienia w ruchu i zmiany tras komunikacji miejskiej."],
        link=("halfmarathon.poznan.pl", "https://halfmarathon.poznan.pl/"),
        sources=[("Poznań Półmaraton (organizator)", "https://halfmarathon.poznan.pl/")],
    ),
    dict(
        id="noc-muzeow", month=5, name="Noc Muzeów", place="Muzea i instytucje kultury w całym mieście",
        when="Co roku w maju, w sobotę",
        dates=("2026-05-16", "2026-05-16"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Jedna noc w roku, gdy muzea, galerie, teatry i inne instytucje kultury są otwarte do późna i przygotowują specjalny program."],
        link=("nocmuzeow.poznan.pl", "https://nocmuzeow.poznan.pl/"),
        sources=[("Noc Muzeów Poznań (organizator)", "https://nocmuzeow.poznan.pl/")],
    ),
    dict(
        id="enter-enea", month=5, name="Enter Enea Festival", place="Jezioro Strzeszyńskie",
        when="Co roku na przełomie maja i czerwca",
        dates=("2026-05-31", "2026-06-03"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Festiwal jazzu i muzyki improwizowanej nad Jeziorem Strzeszyńskim. Dyrektorem artystycznym jest pianista Leszek Możdżer. W 2026 roku odbyła się 16. edycja: 11 koncertów w cztery dni."],
        link=("media.enea.pl", "https://media.enea.pl/pr/870010/enter-enea-festival-swiatowy-jazz-w-poznaniu"),
        sources=[("Enea: Enter Enea Festival – światowy jazz w Poznaniu (16.05.2026)", "https://media.enea.pl/pr/870010/enter-enea-festival-swiatowy-jazz-w-poznaniu")],
    ),
    dict(
        id="ethno-port", month=6, name="Festiwal Ethno Port", place="Centrum Kultury Zamek, ul. Święty Marcin 80/82",
        when="Co roku w czerwcu",
        dates=("2026-06-11", "2026-06-14"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Festiwal muzyki świata: artyści z wielu krajów oraz polscy wykonawcy muzyki tradycyjnej. W 2026 roku odbyła się 19. edycja."],
        link=("ckzamek.pl", "https://ckzamek.pl/wydarzenia/13969-ethno-port-poznan-2026/"),
        sources=[("CK Zamek: Ethno Port Poznań 2026", "https://ckzamek.pl/wydarzenia/13969-ethno-port-poznan-2026/"),
                 ("CK Zamek: plany na 2026 rok", "https://ckzamek.pl/artykuly/13944-sprawdz-co-planujemy-w-2026-roku/")],
    ),
    dict(
        id="pyrkon", month=6, name="Pyrkon – Festiwal Fantastyki", place="Międzynarodowe Targi Poznańskie",
        when="Co roku, w 2026 roku w czerwcu",
        dates=("2026-06-19", "2026-06-21"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Festiwal fantastyki: gry, komiksy, cosplay, literatura, film i seriale. W 2026 roku obchodził 25-lecie i miał ponad 2000 punktów programu. Wstęp jest biletowany."],
        link=("pyrkon.pl", "https://pyrkon.pl/"),
        sources=[("Pyrkon: termin i miejsce", "https://pyrkon.pl/en/time-place/"),
                 ("MTP: Pyrkon 2026 – 25 lat i ponad 2000 punktów programu", "https://www.mtp.pl/pl/mtp-targi/pyrkon-2026-25-lat-i-ponad-2000-punktow-programu-sprawdz-szczegoly")],
    ),
    dict(
        id="malta", month=6, name="Malta Festival Poznań", place="Jezioro Maltańskie i miejsca w całym mieście",
        when="Co roku pod koniec czerwca",
        dates=("2026-06-21", "2026-06-28"), note="Termin na 2027 rok nie jest jeszcze ogłoszony.",
        desc=["Jeden z najważniejszych festiwali sztuki w Polsce: teatr, taniec, muzyka, sztuki wizualne i film. Wiele wydarzeń odbywa się na ulicach i placach. W 2026 roku festiwal otworzyło bezpłatne widowisko nad Jeziorem Maltańskim."],
        link=("malta-festival.pl", "https://malta-festival.pl/"),
        sources=[("Malta Festival: o festiwalu", "https://malta-festival.pl/festiwal/o-festiwalu/"),
                 ("poznan.pl: Malta Festival 2026 starts June 21", "https://www.poznan.pl/mim/wortals/en/wortal,2245/news,9560/malta-festival-2026-starts-june-21-at-lake-malta-free-opening-spectacle-for-love,278244.html")],
    ),
    dict(
        id="maraton", month=10, name="Poznań Maraton", place="Ulice Poznania",
        when="Co roku w październiku, w niedzielę",
        dates=("2026-10-04", "2026-10-04"), note="W 2026 roku 25., jubileuszowa edycja.",
        desc=["Bieg maratoński ulicami miasta, nazwany imieniem Macieja Frankiewicza, byłego zastępcy prezydenta Poznania.",
              "W dniu biegu w wielu częściach miasta są utrudnienia w ruchu i zmiany tras komunikacji miejskiej."],
        link=("marathon.poznan.pl", "https://marathon.poznan.pl/"),
        sources=[("Poznań Maraton (organizator)", "https://marathon.poznan.pl/")],
    ),
    dict(
        id="wieniawski", month=10, name="Międzynarodowy Konkurs Skrzypcowy im. Henryka Wieniawskiego", place="Poznań",
        when="Co pięć lat, w październiku",
        dates=("2026-10-08", "2026-10-24"), note="W 2026 roku 17. edycja. Ostatni koncert laureatów, 25 października, odbywa się w Warszawie.",
        desc=["Międzynarodowy konkurs dla młodych skrzypków, organizowany przez Towarzystwo Muzyczne im. Henryka Wieniawskiego w Poznaniu. Uczestnicy z całego świata grają w kolejnych etapach przesłuchań, a konkurs kończy się finałem i koncertami laureatów. Bilety sprzedaje organizator."],
        link=("wieniawski.pl", "https://wieniawski.pl/xviimks.html"),
        sources=[("Towarzystwo Muzyczne im. H. Wieniawskiego: XVII Konkurs 8–25 X 2026", "https://wieniawski.pl/xviimks.html")],
    ),
    dict(
        id="pga", month=10, name="Poznań Game Arena", place="Międzynarodowe Targi Poznańskie",
        when="Co roku w październiku",
        dates=("2026-10-23", "2026-10-25"), note="W 2026 roku 20., jubileuszowa edycja.",
        desc=["Targi gier komputerowych i rozrywki multimedialnej, według organizatora największe w Europie Środkowo-Wschodniej. Wstęp jest biletowany."],
        link=("gamearena.pl", "https://gamearena.pl/pl/"),
        sources=[("Poznań Game Arena: jubileuszowa edycja już w październiku", "https://gamearena.pl/pl/aktualnosci/jubileuszowa-edycja-juz-w-pazdzierniku/")],
    ),
    dict(
        id="imieniny-sw-marcin", month=11, name="Imieniny Ulicy Święty Marcin", place="ul. Święty Marcin, przy Centrum Kultury Zamek",
        when="Co roku 11 listopada",
        dates=("2026-11-11", "2026-11-11"), note="Zawsze 11 listopada, w Narodowe Święto Niepodległości.",
        desc=["Największe święto miasta, obchodzone od 1994 roku i organizowane przez Centrum Kultury Zamek. Trwa od przedpołudnia do wieczora: kiermasz rogali świętomarcińskich, koncerty, spektakle i atrakcje dla rodzin. Prezydent Poznania przekazuje świętemu Marcinowi klucze do miasta.",
              "Od 2025 roku nie ma korowodu w dawnej formie. Na ulicy powstaje ogrodzone „imieninowe miasteczko” z czterema bramami i kontrolą przy wejściu. Wstęp jest bezpłatny. Walizki, duże torby i plecaki trzeba zostawić w bezpłatnym depozycie przy bramie."],
        link=("ckzamek.pl", "https://ckzamek.pl/podstrony/71-imieniny-ulicy-swiety-marcin/"),
        sources=[("CK Zamek: Imieniny Ulicy Święty Marcin 2025 – informacje praktyczne", "https://ckzamek.pl/artykuly/13267-informacje-praktyczne/"),
                 ("CK Zamek: plany na 2026 rok", "https://ckzamek.pl/artykuly/13944-sprawdz-co-planujemy-w-2026-roku/")],
    ),
    dict(
        id="jarmark-mtp", month=11, name="Jarmark Świąteczny na Targach", place="Międzynarodowe Targi Poznańskie",
        when="Co roku od połowy listopada do przedświątecznego tygodnia",
        dates=("2026-11-14", "2026-12-20"), note="",
        desc=["Jarmark bożonarodzeniowy na terenie Międzynarodowych Targów Poznańskich, kilka minut pieszo od dworca Poznań Główny."],
        link=("jarmark.poznan.pl", "https://jarmark.poznan.pl/pl/"),
        sources=[("Jarmark Świąteczny na Targach (organizator)", "https://jarmark.poznan.pl/pl/")],
    ),
    dict(
        id="betlejem", month=11, name="Betlejem Poznańskie na Placu Wolności i Starym Rynku", place="Plac Wolności i Stary Rynek",
        when="Co roku od drugiej połowy listopada do 6 stycznia",
        dates=None, note="Termin na sezon 2026/27 nie jest jeszcze ogłoszony. W sezonie 2025/26 jarmark na Placu Wolności trwał od 21 listopada do 6 stycznia.",
        desc=["Świąteczne jarmarki w ścisłym centrum: stoiska z ozdobami, rękodziełem i jedzeniem, występy artystów i warsztaty dla dzieci. To jedyny jarmark, który miasto dopuszcza na Starym Rynku."],
        link=("pik.poznan.pl", "https://pik.poznan.pl/jarmark-bozonarodzeniowy-betlejem-poznanskie/"),
        sources=[("PIK Poznań: Jarmark Bożonarodzeniowy – Betlejem Poznańskie", "https://pik.poznan.pl/jarmark-bozonarodzeniowy-betlejem-poznanskie/"),
                 ("ESKA Poznań: nie będzie Jarmarku Świętojańskiego 2025", "https://poznan.eska.pl/nie-bedzie-jarmarku-swietojanskiego-w-poznaniu-mamy-odpowiedz-jarmarki-nie-wpisuja-sie-w-obecne-cele-aa-9jCz-vvgX-b18q.html")],
    ),
    dict(
        id="ice-festival", month=12, name="Poznań Ice Festival", place="Stary Rynek",
        when="Co roku w grudniu",
        dates=("2026-12-11", "2026-12-13"), note="W 2026 roku 20., jubileuszowa edycja.",
        desc=["Festiwal rzeźby lodowej: rzeźbiarze z kilku krajów tworzą na oczach widzów kilkumetrowe rzeźby z brył lodu, piłami mechanicznymi i dłutami. W 2026 roku startuje 24 rzeźbiarzy."],
        link=("poznan.pl", "https://www.poznan.pl/mim/turystyka/news/poznan-ice-festival-wraca-na-stary-rynek,243196.html"),
        sources=[("Codzienny Poznań: Poznań Ice Festival wraca na Stary Rynek (18.09.2026)", "https://codziennypoznan.pl/artykul/2026-09-18/tony-lodu-i-mistrzowie-z-calego-swiata-poznan-ice-festival-wraca-na-stary-rynek-z-jubileuszowa-edycja/")],
    ),
]
