# -*- coding: utf-8 -*-
"""Treść przewodnika. Wszystkie godziny i ceny sprawdzone 28.09.2026
w źródłach podanych w polu "sources" każdej atrakcji.
Po zmianie danych uruchom: python src/build.py
"""

CHECKED = "28.09.2026"

CATEGORIES = [
    ("zabytki", "Zabytki i historia", "Tysiąc lat historii: od grodu Mieszka I po zamek cesarza."),
    ("pomniki", "Pomniki i fontanny", "Od barokowej fontanny przed ratuszem po Starego Marycha z rowerem."),
    ("koscioly", "Kościoły", "Od romańskiego kościoła joannitów po międzywojenne rotundy."),
    ("muzea", "Muzea", "Sztuka, archeologia, historia Wielkopolski i rogale."),
    ("przyroda", "Parki i przyroda", "Jezioro, ogrody i zieleń w granicach miasta."),
    ("rodzina", "Dla rodzin i aktywnie", "Zoo, kolejka, baseny i stok przez cały rok."),
    ("wspolczesny", "Współczesny Poznań", "Street art i dawny browar zamieniony w centrum sztuki."),
    ("wycieczki", "Wycieczki za miasto", "Zamki, pałace i kolebka Polski w zasięgu jednodniowego wyjazdu."),
]

# status: None | ("closed", "tekst") | ("warning", "tekst")
ATTRACTIONS = [
    # ─── ZABYTKI ───
    dict(
        slug="stary-rynek", cat="zabytki", name="Stary Rynek i Ratusz",
        img="stare-miasto", img_alt="Kamienice przy Starym Rynku w Poznaniu",
        short="Serce miasta od XIII wieku. Renesansowy ratusz i koziołki trykające się w południe.",
        badge="Bezpłatnie",
        status=("warning", "Muzeum w Ratuszu (Ratusz – Muzeum Poznania) jest nieczynne od 1 lipca 2026 do 30 listopada 2027 z powodu remontu. Część budynku jest za rusztowaniami. Koziołki nadal się trykają, ale w trakcie prac zdarzały się przerwy w działaniu mechanizmu."),
        lead="Stary Rynek to plac wytyczony około 1253 roku przy lokacji miasta. Ma kształt kwadratu o boku 141 metrów, a w jego środku stoi ratusz, jeden z najcenniejszych renesansowych budynków w tej części Europy.",
        sections=[
            ("O miejscu", [
                "Rynek powstał jako centrum miasta lokacyjnego, założonego między zamkiem a Wartą. Wokół placu stoją kamienice, a środek zajmuje blok zabudowy o wymiarach około 74 na 76 metrów.",
                "Ratusz ma średniowieczne początki. W latach 1550–1560 przebudował go Giovanni Battista di Quadro, architekt z Ticino. Podwyższył budynek o jedno piętro i rozbudował go w kierunku zachodnim, nadając mu renesansowy wygląd.",
            ]),
            ("Co zobaczyć", [
                "Koziołki na wieży ratusza: codziennie o 12:00 wychodzą nad zegar i trykają się rogami. Mechanizm zamówiono w 1551 roku razem z zegarem. W południe pod ratuszem zbiera się tłum, więc warto przyjść kilka minut wcześniej.",
                "Blok śródrynkowy: poza ratuszem stoją tu Waga Miejska, klasycystyczny Odwach (dziś Muzeum Powstania Wielkopolskiego) oraz domki budnicze, dawne kramy kupieckie.",
                "Cztery fontanny w narożach rynku: Apollina, Neptuna, Marsa i Prozerpiny. Fontanna Prozerpiny pochodzi z XVIII wieku.",
            ]),
            ("Warto wiedzieć", [
                "Punkt Informacji Turystycznej działa w kamienicy Stary Rynek 59/60. Można tu dostać mapy i kupić Poznańską Kartę Turystyczną.",
                "W promieniu kilkuset metrów są: Rogalowe Muzeum Poznania, Fara Poznańska, Muzeum Archeologiczne i Muzeum Powstania Wielkopolskiego.",
            ]),
        ],
        address="Stary Rynek, 61-772 Poznań",
        hours=[("Plac", "dostępny całą dobę"), ("Koziołki", "codziennie o 12:00"), ("Muzeum w Ratuszu", "nieczynne do 30.11.2027")],
        tickets=[("Plac i koziołki", "bezpłatnie")],
        phone=None, www=("visitpoznan.pl", "https://visitpoznan.pl/"),
        credit="stare-miasto",
        sources=[("Wikipedia: Stary Rynek w Poznaniu", "https://pl.wikipedia.org/wiki/Stary_Rynek_w_Poznaniu"),
                 ("Wikipedia: Ratusz w Poznaniu", "https://pl.wikipedia.org/wiki/Ratusz_w_Poznaniu"),
                 ("kultura.poznan.pl: Ratusz – Muzeum Poznania (remont)", "https://kultura.poznan.pl/mim/kultura/object.html?id_klasy=202&lang=&id_cz=12&id_obiektu=40787"),
                 ("TVP Poznań: remont ratusza i koziołki", "https://poznan.tvp.pl/93014656/ratusz-poznan-remont-rusztowania-zamkniecie-koziolki-poznan-zamkniecie-kiedy-koniec-prac-muzeum-mieszkancow-stary-rynek")],
    ),
    dict(
        slug="ostrow-tumski", cat="zabytki", name="Ostrów Tumski i Archikatedra",
        img="ostrow-tumski", img_alt="Archikatedra na Ostrowie Tumskim",
        short="Najstarsza katedra w Polsce. Groby pierwszych władców i Złota Kaplica.",
        badge="Katedra bezpłatnie",
        status=None,
        lead="Ostrów Tumski to wyspa między Wartą a Cybiną, na której w X wieku stał gród pierwszych Piastów. Biskupstwo działa tu od 968 roku, a archikatedra świętych Piotra i Pawła jest najstarszą katedrą w Polsce.",
        sections=[
            ("O miejscu", [
                "Pierwszą katedrę wzniesiono w latach 80. X wieku. Obecna bryła jest gotycka, z XIV i XV wieku. Po zniszczeniach II wojny światowej świątynię częściowo odbudowano i przywrócono jej gotycki charakter.",
                "W katedrze pochowano pierwszych władców Polski, w tym Bolesława Chrobrego, Mieszka II i Kazimierza Odnowiciela.",
            ]),
            ("Co zobaczyć", [
                "Złota Kaplica (Kaplica Królów Polskich) z lat 1836–1837: ośmioboczne mauzoleum w stylu bizantyjskim, poświęcone Mieszkowi I i Bolesławowi Chrobremu. Stoi dokładnie w osi kościoła.",
                "Podziemia katedry: relikty dawnych budowli, groby władców z dynastii Piastów i misa chrzcielna z X wieku.",
                "Wieża widokowa, czynna sezonowo (w 2026 roku od 1 czerwca).",
            ]),
            ("Warto wiedzieć", [
                "Katedra jest czynnym kościołem. W czasie mszy, nabożeństw i koncertów nie można jej zwiedzać, obowiązuje też stosowny strój i cisza.",
                "Po drugiej stronie Cybiny, połączona kładką, stoi Brama Poznania. Oferuje ona bilet łączony na zwiedzanie Ostrowa Tumskiego.",
            ]),
        ],
        address="ul. Ostrów Tumski 17, 61-109 Poznań",
        hours=[("Zwiedzanie (1.03–15.11)", "dni powszednie 9:00–16:00"), ("Zwiedzanie (16.11–29.02)", "dni powszednie 9:00–16:00"), ("Wieża widokowa", "od 1.06.2026, sezonowo")],
        tickets=[("Wejście do katedry", "bezpłatnie"), ("Podziemia", "10 zł, ulgowy 8 zł, rodzinny 25 zł"), ("Wieża widokowa", "14 zł, ulgowy 12 zł, rodzinny 40 zł")],
        phone="+48 61 852 96 42", www=("katedra.archpoznan.pl", "https://www.katedra.archpoznan.pl/turysci-w-katedrze/"),
        credit="ostrow-tumski",
        sources=[("Katedra Poznańska: Turyści w katedrze", "https://www.katedra.archpoznan.pl/turysci-w-katedrze/"),
                 ("Wikipedia: Archikatedra w Poznaniu", "https://pl.wikipedia.org/wiki/Bazylika_archikatedralna_Świętych_Apostołów_Piotra_i_Pawła_w_Poznaniu")],
    ),
    dict(
        slug="brama-poznania", cat="zabytki", name="Brama Poznania ICHOT",
        img="brama-poznania", img_alt="Budynek Bramy Poznania nad Cybiną",
        short="Multimedialna opowieść o początkach państwa polskiego, naprzeciw katedry.",
        badge="Pn nieczynne",
        status=None,
        lead="Brama Poznania to centrum interpretacji dziedzictwa, otwarte 1 maja 2014 roku. Zamiast gablot z eksponatami są tu multimedialne sale, które opowiadają historię Ostrowa Tumskiego i narodzin państwa polskiego.",
        sections=[
            ("O miejscu", [
                "Budynek zaprojektowali Arkadiusz Emerla i Maciej Wojda z krakowskiej pracowni Ad Artis. Prosta betonowa bryła stoi na prawym brzegu Cybiny i celowo kieruje wzrok zwiedzających na drugą stronę rzeki, w stronę katedry.",
                "63-metrowa kładka nad Cybiną łączy główny budynek z odnowioną XIX-wieczną Śluzą Katedralną na Ostrowie Tumskim.",
            ]),
            ("Co zobaczyć", [
                "Ekspozycję podzielono na cztery strefy tematyczne: Gród (początki osady), Woda (chrzest i chrystianizacja), Złoto (rozwój od XVI do XIX wieku) i Witraż (czasy współczesne).",
            ]),
            ("Warto wiedzieć", [
                "W budynku działa punkt informacji turystycznej.",
                "Z Poznańską Kartą Turystyczną bilet kosztuje 21 zł (ulgowy 17 zł).",
            ]),
        ],
        address="ul. Gdańska 2, 61-123 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–piątek", "9:00–18:00"), ("Sobota–niedziela", "10:00–19:00")],
        tickets=[("Normalny", "35 zł"), ("Ulgowy", "29 zł"), ("Rodzinny (do 5 osób, max 2 dorosłych)", "75 zł"), ("Łączony Ostrów Tumski", "49 zł, ulgowy 36 zł, rodzinny 109 zł")],
        phone="+48 61 647 76 34", www=("bramapoznania.pl", "https://bramapoznania.pl/"),
        credit="brama-poznania",
        sources=[("Brama Poznania: cennik", "https://bramapoznania.pl/cennik"),
                 ("Brama Poznania: godziny otwarcia", "https://bramapoznania.pl/godziny-otwarcia"),
                 ("Wikipedia: Brama Poznania ICHOT", "https://pl.wikipedia.org/wiki/Brama_Poznania_ICHOT")],
    ),
    dict(
        slug="fara", cat="koscioly", name="Fara Poznańska",
        img="fara", img_alt="Barokowa fasada Fary Poznańskiej",
        short="Barokowa bazylika z organami Ladegasta. Koncerty w każdą sobotę o 12:15.",
        badge="Wstęp wolny",
        status=None,
        lead="Fara, czyli Bazylika Matki Bożej Nieustającej Pomocy i św. Marii Magdaleny, to jeden z najokazalszych kościołów barokowych w Polsce. Budowa zaczęła się w 1649 roku i trwała ponad 50 lat.",
        sections=[
            ("Co zobaczyć", [
                "Organy zbudowane w 1876 roku przez Friedricha Ladegasta, jednego z najsłynniejszych organmistrzów XIX wieku. Mają 2579 piszczałek, a największe mierzą 6 metrów.",
                "Po koncercie, około 12:45, można dołączyć do zwiedzania z przewodnikiem. Są trzy trasy: wnętrze kościoła (30–40 minut), miejsca ukryte (zakrystia i barokowy kapitularz) oraz podziemia.",
            ]),
            ("Koncerty organowe", [
                "W każdą sobotę o 12:15 od ponad dwudziestu lat odbywa się koncert na organach Ladegasta.",
                "Za 5 zł od osoby można też wejść z organistą na chór i obejrzeć instrument z bliska.",
            ]),
            ("Warto wiedzieć", [
                "Kościół jest otwarty codziennie, ale parafia prosi, by nie zwiedzać go w czasie mszy.",
            ]),
        ],
        address="ul. Gołębia 1, Poznań",
        hours=[("Kościół", "codziennie 6:00–19:30"), ("Koncert organowy", "soboty 12:15"), ("Zwiedzanie z przewodnikiem", "soboty ok. 12:45")],
        tickets=[("Wejście do kościoła", "bezpłatnie"), ("Trasy z przewodnikiem", "2–5 zł od osoby"), ("Wizyta u organisty", "5 zł od osoby")],
        phone="+48 61 852 69 50", www=("fara.archpoznan.pl", "https://fara.archpoznan.pl/"),
        credit="fara",
        sources=[("Fara Poznańska: zwiedzanie", "https://fara.archpoznan.pl/pl/zwiedzanie?view=article&id=24%3Agodziny-otwarcia&catid=2"),
                 ("Visit Poznań: Fara Poznańska", "https://visitpoznan.pl/fara-poznanska")],
    ),
    dict(
        slug="zamek-krolewski", cat="zabytki", name="Zamek Królewski",
        img="zamek-krolewski", img_alt="Wieża Zamku Królewskiego na Wzgórzu Przemysła",
        short="Zamek Przemysła II z Muzeum Sztuk Użytkowych i 43-metrową wieżą widokową.",
        badge="Wt wstęp wolny",
        status=None,
        lead="Zamek na Wzgórzu Przemysła wzniesiono prawdopodobnie w XIII wieku z inicjatywy Przemysła II. Budowę mógł zacząć już jego ojciec, Przemysł I. Po zniszczeniach 1945 roku zamek odbudowywano dwa razy, ostatnio w latach 2010–2013.",
        sections=[
            ("O miejscu", [
                "Obecny wygląd to efekt dwóch odbudów: z lat 1959–1964 i 2010–2013.",
                "Od 26 czerwca 2016 roku można wejść na wieżę widokową, z której rozciąga się widok na miasto.",
            ]),
            ("Co zobaczyć", [
                "Muzeum Sztuk Użytkowych (oddział Muzeum Narodowego) zajmuje prawie 1500 m². Pokazuje około 2000 przedmiotów od średniowiecza do współczesności: meble, ceramikę, szkło i biżuterię.",
                "Po obejrzeniu wystawy można wejść na 43-metrową wieżę z tarasem widokowym.",
            ]),
            ("Wieża widokowa", [
                "Wieża ma dwa tarasy: zadaszony na wysokości 30 metrów i otwarty na samym szczycie. Widać z nich panoramę Poznania i okolic.",
                "Na górę prowadzi blisko 200 stopni. Do tarasu zadaszonego można też wjechać windą.",
                "Na tarasie może jednocześnie przebywać do 25 osób. Przy złej pogodzie taras otwarty jest zamykany.",
            ]),
        ],
        address="Góra Przemysła 1, 61-768 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–środa", "10:00–16:00"), ("Czwartek", "10:00–18:00"), ("Piątek", "10:00–20:00"), ("Sobota–niedziela", "10:00–17:00")],
        tickets=[("Normalny", "20 zł"), ("Ulgowy", "13 zł"), ("Dzieci i młodzież 7–26 lat", "1 zł"), ("Wtorek", "wstęp wolny na wystawę stałą")],
        phone="+48 61 856 80 75", www=("mnp.art.pl", "https://mnp.art.pl/"),
        credit="zamek-krolewski",
        sources=[("kultura.poznan.pl: Muzeum Sztuk Użytkowych", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/muzeum-sztuk-uzytkowych-zamek-przemysla,15703.html"),
                 ("Wikipedia: Zamek Królewski w Poznaniu", "https://pl.wikipedia.org/wiki/Zamek_Królewski_w_Poznaniu"),
                 ("poznan.pl: Wieża widokowa – Wzgórze Przemysła", "https://www.poznan.pl/mim/wortals/wortal,2024/inne-atrakcje,poi,3391/wieza-widokowa-wzgorze-przemysla,61910.html")],
    ),
    dict(
        slug="zamek-cesarski", cat="zabytki", name="Zamek Cesarski",
        img="zamek-cesarski", img_alt="Wieża Zamku Cesarskiego w Poznaniu",
        short="Neoromańska rezydencja Wilhelma II z lat 1905–1910. Dziś Centrum Kultury Zamek.",
        badge="Codziennie",
        status=None,
        lead="Zamek zbudowano w latach 1905–1910 dla cesarza Wilhelma II. Zaprojektował go Franz Schwechten w stylu neoromańskim, który cesarz wybrał jako nawiązanie do średniowiecznego cesarstwa.",
        sections=[
            ("O miejscu", [
                "Cesarz osobiście wpływał na szczegóły projektu. Najokazalszym wnętrzem była Sala Tronowa, wzorowana na bazylikach bizantyjskich, z posągami ośmiu cesarzy niemieckich.",
                "W 1939 roku Franz Böhmer przebudował wnętrza na potrzeby Adolfa Hitlera i namiestnika Arthura Greisera. Gabinet Hitlera wzorowano na jego biurze w Berlinie, choć Hitler prawdopodobnie nigdy tu nie był.",
                "Dziś w zamku działa Centrum Kultury Zamek: kino, galerie, sceny koncertowe i teatralne.",
            ]),
            ("Co zobaczyć", [
                "Sala Tronowa, gabinet cesarza, kaplica w stylu bizantyjskim w wieży i ogród różany.",
                "Audioprzewodnik ma trasy po polsku, angielsku i ukraińsku, trasę dla dzieci (7–14 lat), trasę bez schodów oraz trasę z tłumaczem polskiego języka migowego (w aplikacji).",
            ]),
            ("Warto wiedzieć", [
                "11 listopada przed zamkiem odbywa się jarmark w czasie Imienin Ulicy Święty Marcin.",
            ]),
        ],
        address="ul. Święty Marcin 80/82, Poznań",
        hours=[("Zwiedzanie", "codziennie 12:00–19:00"), ("Sprzedaż biletów", "do 18:00")],
        tickets=[("Zwiedzanie zamku", "10 zł, ulgowy 7 zł"), ("Audioprzewodnik", "20 zł, ulgowy 15 zł")],
        phone=None, www=("ckzamek.pl", "https://ckzamek.pl/podstrony/6071-zwiedzanie-zamku/"),
        credit="zamek-cesarski",
        sources=[("CK Zamek: zwiedzanie i audioprzewodniki", "https://ckzamek.pl/podstrony/6071-zwiedzanie-zamku/"),
                 ("CK Zamek: cennik (aktualizacja 30.03.2026)", "https://ckzamek.bilety24.pl/wp-content/uploads/2026/04/CENNIK_CK_ZAMEK_aktualizacja_30.03.2026.pdf"),
                 ("Wikipedia: Zamek Cesarski w Poznaniu", "https://pl.wikipedia.org/wiki/Zamek_Cesarski_w_Poznaniu")],
    ),
    dict(
        slug="cytadela", cat="zabytki", name="Cytadela",
        img="cytadela", img_alt="Pomnik Bohaterów w Parku Cytadela",
        short="Park na miejscu pruskiego fortu. Cmentarze wojenne, Nierozpoznani i dwa muzea.",
        badge="Park bezpłatnie",
        status=None,
        lead="Park Cytadela zajmuje około 100 hektarów w miejscu Fortu Winiary, centralnego fortu dawnej Twierdzy Poznań. Od 2008 roku jest pomnikiem historii.",
        sections=[
            ("O miejscu", [
                "Fort zaczęto budować 23 czerwca 1828 roku według projektu Johanna Leopolda Ludwiga Brese. Prace trwały około 14 lat.",
                "W lutym 1945 roku Cytadela była ostatnim punktem oporu wojsk niemieckich w Poznaniu i padła 23 lutego. 21 lipca 1946 roku odbyła się tu ostatnia publiczna egzekucja w Polsce: powieszono Arthura Greisera, nazistowskiego namiestnika Kraju Warty.",
                "W latach 1963–1970 fort rozebrano i urządzono park. Odzyskaną cegłę wykorzystano przy odbudowie Warszawy i Poznania.",
            ]),
            ("Co zobaczyć", [
                "Nierozpoznani: instalacja Magdaleny Abakanowicz ze 112 żeliwnych postaci, powstała na 750-lecie Poznania.",
                "Cmentarze: Cmentarz Bohaterów Polskich, parafialny cmentarz św. Wojciecha, cmentarz garnizonowy, cmentarz żołnierzy radzieckich oraz Cmentarz Wojenny Wspólnoty Brytyjskiej, gdzie leży 48 uczestników Wielkiej Ucieczki.",
                "Dzwon Pokoju i Przyjaźni Między Narodami.",
                "Muzeum Uzbrojenia i Muzeum Armii „Poznań”, oddziały Wielkopolskiego Muzeum Niepodległości.",
            ]),
        ],
        address="al. Armii Poznań, 61-663 Poznań",
        hours=[("Park", "ogólnodostępny"), ("Muzeum Uzbrojenia (III–X)", "wt–sb 10:00–17:00, nd 10:00–16:00"), ("Muzeum Uzbrojenia (XI–II)", "wt–nd 10:00–16:00"), ("Poniedziałek", "muzea nieczynne")],
        tickets=[("Park", "bezpłatnie"), ("Muzeum Uzbrojenia", "15 zł, ulgowy 10 zł, dzieci do 7 lat bezpłatnie"), ("Muzeum Armii „Poznań”", "10 zł, ulgowy 6 zł"), ("Bilet łączony obu muzeów", "20 zł, ulgowy 12 zł"), ("Wtorek", "muzea bezpłatnie")],
        phone=None, www=("wmn.poznan.pl", "https://www.wmn.poznan.pl/oddzialy-4/muzeum-uzbrojenia/"),
        credit="cytadela",
        sources=[("Wikipedia: Park Cytadela", "https://pl.wikipedia.org/wiki/Park_Cytadela"),
                 ("Wikipedia: Cytadela w Poznaniu", "https://pl.wikipedia.org/wiki/Cytadela_w_Poznaniu"),
                 ("WMN: ceny biletów", "https://www.wmn.poznan.pl/ceny-biletow/"),
                 ("WMN: godziny otwarcia", "https://www.wmn.poznan.pl/godziny-otwarcia/")],
    ),

    # ─── MUZEA ───
    dict(
        slug="muzeum-narodowe", cat="muzea", name="Muzeum Narodowe",
        img="muzeum-narodowe", img_alt="Gmach Muzeum Narodowego w Poznaniu",
        short="Jedyny obraz Moneta w polskich zbiorach i duży zbiór obrazów Malczewskiego.",
        badge="Wt wstęp wolny",
        status=None,
        lead="Galeria Malarstwa i Rzeźby to główna siedziba Muzeum Narodowego w Poznaniu, jednego z najstarszych muzeów w Polsce, założonego w 1857 roku.",
        sections=[
            ("Co zobaczyć", [
                "Plaża w Pourville Claude'a Moneta, jedyny obraz tego impresjonisty w polskich zbiorach.",
                "Stary gmach: sztuka starożytna (w tym portrety rzymskich cesarzy), sztuka średniowieczna, sztuka polska XVI–XVIII wieku i malarstwo obce, m.in. hiszpańskie i włoskie.",
                "Nowy gmach: sztuka polska od oświecenia do dziś, w tym duży zbiór obrazów Jacka Malczewskiego.",
            ]),
            ("Warto wiedzieć", [
                "Dla rodzin z dziećmi muzeum wypożycza bezpłatny zestaw „Muzealny Poszukiwacz Skarbów”.",
                "Budynek ma windy i toalety dostępne dla osób z niepełnosprawnościami.",
                "Z Poznańską Kartą Turystyczną wstęp na wystawy stałe jest bezpłatny.",
            ]),
        ],
        address="al. Marcinkowskiego 9, 61-745 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–środa", "10:00–16:00"), ("Czwartek", "10:00–18:00"), ("Piątek", "10:00–20:00"), ("Sobota–niedziela", "10:00–17:00")],
        tickets=[("Normalny", "20 zł"), ("Ulgowy", "13 zł"), ("Dzieci i młodzież 7–26 lat", "1 zł"), ("Wtorek", "wstęp wolny na wystawy stałe")],
        phone="+48 61 856 80 00", www=("mnp.art.pl", "https://mnp.art.pl/"),
        credit="muzeum-narodowe",
        sources=[("kultura.poznan.pl: Muzeum Narodowe", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/muzeum-narodowe-w-poznaniu,15730.html"),
                 ("Visit Poznań: Galeria Malarstwa i Rzeźby", "https://visitpoznan.pl/galeria-malarstwa-i-rzezby-muzeum-narodowe-w-poznaniu")],
    ),
    dict(
        slug="rogalowe-muzeum", cat="muzea", name="Rogalowe Muzeum Poznania",
        img="rogalowe-muzeum", img_alt="Pokaz wypieku rogali w Rogalowym Muzeum",
        short="Pokaz o rogalach świętomarcińskich przy Starym Rynku. Bilety warto kupić wcześniej.",
        badge="Rezerwuj wcześniej",
        status=None,
        lead="Rogalowe Muzeum to interaktywny pokaz przy Starym Rynku. Pokaz ma interaktywny charakter: uczestnicy poznają historię rogala świętomarcińskiego i to, jak powstaje według tradycyjnej receptury.",
        sections=[
            ("O rogalu", [
                "Rogal świętomarciński od 31 sierpnia 2008 roku ma unijne Chronione Oznaczenie Geograficzne. Oryginalne rogale mogą wypiekać tylko cukiernie z Wielkopolski, które mają certyfikat Kapituły Poznańskiego Tradycyjnego Rogala Świętomarcińskiego.",
                "Poznaniacy jedzą rogale przede wszystkim 11 listopada, w dniu Imienin Ulicy Święty Marcin.",
            ]),
            ("Pokazy", [
                "Pokaz rogalowy trwa 55–60 minut, pokaz rogalowy z herbami 65 minut.",
                "Pokazy po angielsku są w soboty i niedziele o 14:00, a w lipcu i sierpniu codziennie o 14:00.",
                "Pokazy często się wyprzedają, więc bilet najlepiej kupić z wyprzedzeniem. Rezerwacja online jest możliwa do 30 minut przed pokazem.",
            ]),
        ],
        address="Stary Rynek 41/2 (wejście od ul. Klasztornej 23), 61-772 Poznań",
        hours=[("Pokazy codziennie", "11:00 (z herbami), 12:30, 14:00 (z herbami), 15:30"), ("Dodatkowo w soboty", "17:00"), ("Po angielsku", "sb–nd 14:00, w VII–VIII codziennie")],
        tickets=[("Pokaz rogalowy", "41 zł, ulgowy 37 zł"), ("Pokaz z herbami", "47 zł, ulgowy 43 zł"), ("Dzieci do 3 lat", "1 zł")],
        phone=None, www=("rogalowemuzeum.pl", "https://rogalowemuzeum.pl/indywidualni/"),
        credit="rogalowe-muzeum",
        sources=[("Rogalowe Muzeum: dla indywidualnych (cennik od 2.01.2026)", "https://rogalowemuzeum.pl/indywidualni/"),
                 ("Wikipedia: Rogal świętomarciński", "https://pl.wikipedia.org/wiki/Rogal_świętomarciński")],
    ),
    dict(
        slug="muzeum-powstania", cat="muzea", name="Muzeum Powstania Wielkopolskiego",
        img="muzeum-powstania", img_alt="Klasycystyczny Odwach na Starym Rynku",
        short="Historia zwycięskiego powstania 1918–1919 w klasycystycznym Odwachu na rynku.",
        badge="Wt wstęp wolny",
        status=None,
        lead="Muzeum Powstania Wielkopolskiego 1918–1919 mieści się w Odwachu, klasycystycznym budynku z lat 1783–1787 w środku Starego Rynku. Jest oddziałem Wielkopolskiego Muzeum Niepodległości.",
        sections=[
            ("Co zobaczyć", [
                "Wystawę o Powstaniu Wielkopolskim, jednym z nielicznych zwycięskich powstań w historii Polski, po którym Wielkopolska wróciła do odrodzonego państwa.",
            ]),
            ("Warto wiedzieć", [
                "Grupy mogą zamówić oprowadzanie po polsku (70 zł) lub po angielsku (90 zł).",
            ]),
        ],
        address="Stary Rynek 3, 61-772 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Marzec–październik", "wt–sb 10:00–17:00, nd 10:00–16:00"), ("Listopad–luty", "wt–nd 10:00–16:00")],
        tickets=[("Normalny", "15 zł"), ("Ulgowy", "10 zł"), ("Wtorek", "wstęp wolny")],
        phone=None, www=("wmn.poznan.pl", "https://www.wmn.poznan.pl/oddzialy-4/muzeum-powstania-wielkopolskiego-1918-1919/"),
        credit="muzeum-powstania",
        sources=[("WMN: ceny biletów", "https://www.wmn.poznan.pl/ceny-biletow/"),
                 ("WMN: godziny otwarcia", "https://www.wmn.poznan.pl/godziny-otwarcia/")],
    ),
    dict(
        slug="muzeum-archeologiczne", cat="muzea", name="Muzeum Archeologiczne",
        img="muzeum-archeologiczne", img_alt="Pałac Górków, siedziba Muzeum Archeologicznego",
        short="Pradzieje Wielkopolski i starożytny Egipt w renesansowym Pałacu Górków.",
        badge="Wt wstęp wolny",
        status=None,
        lead="Muzeum Archeologiczne działa od 1862 roku, a jego siedzibą jest Pałac Górków przy ulicy Wodnej, tuż przy Starym Rynku. Pałac, częściowo zniszczony w czasie wojny, odbudowywano do 1968 roku.",
        sections=[
            ("Co zobaczyć", [
                "Wystawę stałą o pradziejach Wielkopolski, od epoki kamienia po średniowiecze.",
                "Wystawę o starożytnym Egipcie, a także zbiory z archeologii Sudanu.",
            ]),
            ("Warto wiedzieć", [
                "Muzeum prowadzi też Rezerwat Archeologiczny Genius Loci na Ostrowie Tumskim, otwarty w 2012 roku. Są tam prezentacje multimedialne i rekonstrukcje średniowiecznych umocnień grodu. Na oba miejsca można kupić bilet łączony, szczegóły na stronach muzeum.",
                "Ostatnie wejście jest pół godziny przed zamknięciem.",
            ]),
        ],
        address="ul. Wodna 27, 61-781 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–czwartek", "9:00–16:00 (od 1.09 do 30.06)"), ("Piątek", "10:00–17:00"), ("Sobota", "11:00–18:00"), ("Niedziela", "12:00–16:00"), ("Lipiec–sierpień", "wt–pt 10:00–17:00")],
        tickets=[("Normalny", "20 zł"), ("Ulgowy", "15 zł"), ("Rodzinny (do 6 osób)", "50 zł"), ("Wtorek", "wstęp wolny")],
        phone="+48 61 852 82 51", www=("muzarp.poznan.pl", "https://nowa.muzarp.poznan.pl/"),
        credit="muzeum-archeologiczne",
        sources=[("Muzeum Archeologiczne: bilety", "https://nowa.muzarp.poznan.pl/pl/bilety"),
                 ("Muzeum Archeologiczne: godziny otwarcia", "https://nowa.muzarp.poznan.pl/pl/godziny-otwarcia"),
                 ("Wikipedia: Muzeum Archeologiczne w Poznaniu", "https://pl.wikipedia.org/wiki/Muzeum_Archeologiczne_w_Poznaniu")],
    ),

    # ─── PRZYRODA ───
    dict(
        slug="jezioro-maltanskie", cat="przyroda", name="Jezioro Maltańskie",
        img="jezioro-malta", img_alt="Rzeźba nad Jeziorem Maltańskim",
        short="Sztuczne jezioro z torem regatowym. Spacery, rowery i atrakcje przez cały rok.",
        badge="Bezpłatnie",
        status=None,
        lead="Jezioro Maltańskie to sztuczny zbiornik, oddany do użytku w 1952 roku. Ma 2,2 km długości i około 64 hektarów powierzchni. Wokół niego biegnie popularna trasa spacerowa i rowerowa.",
        sections=[
            ("Co zobaczyć", [
                "Tor regatowy z systemem Albano, zbudowany w latach 1987–1990, przystosowany do zawodów międzynarodowych.",
                "Nad jeziorem są też Termy Maltańskie, całoroczny stok Malta Ski, Kolejka Parkowa Maltanka i Nowe Zoo.",
            ]),
            ("Warto wiedzieć", [
                "W czerwcu nad jeziorem i w całym mieście odbywa się Malta Festival. W 2026 roku miał 108 wydarzeń w 27 miejscach.",
            ]),
        ],
        address="Jezioro Maltańskie, Poznań",
        hours=[("Teren wokół jeziora", "dostępny całą dobę")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("visitpoznan.pl", "https://visitpoznan.pl/"),
        credit="jezioro-malta",
        sources=[("Wikipedia: Jezioro Maltańskie", "https://pl.wikipedia.org/wiki/Jezioro_Maltańskie")],
    ),
    dict(
        slug="ogrod-botaniczny", cat="przyroda", name="Ogród Botaniczny UAM",
        img="ogrod-botaniczny", img_alt="Ogród Botaniczny UAM w Poznaniu",
        short="22 hektary roślin z całego świata i jedna z najbogatszych kolekcji kaktusów w Polsce.",
        badge="Wstęp wolny",
        status=None,
        lead="Ogród Botaniczny Uniwersytetu im. Adama Mickiewicza założono w 1925 roku. Zajmuje około 22 hektarów i ma ponad 2500 taksonów roślin.",
        sections=[
            ("Co zobaczyć", [
                "Kolekcję sukulentów i kaktusów, jedną z najbogatszych w Polsce (około 1150 gatunków z 228 rodzajów).",
                "Alpinarium z roślinami gór od strefy umiarkowanej po subarktyczną.",
                "Szklarnie z roślinami tropikalnymi i subtropikalnymi, w tym jedyną w Polsce kwitnącą welwiczję starszą niż 35 lat.",
            ]),
        ],
        address="ul. Dąbrowskiego 165, 60-594 Poznań",
        hours=[("Marzec", "9:00–17:00"), ("Kwiecień i wrzesień", "9:00–19:00"), ("Maj–sierpień", "9:00–20:00"), ("Październik", "9:00–18:00"), ("Listopad–luty", "9:00–15:00")],
        tickets=[("Wstęp do ogrodu", "bezpłatnie")],
        phone="+48 61 829 20 13", www=("ogrod.amu.edu.pl", "https://ogrod.amu.edu.pl/"),
        credit="ogrod-botaniczny",
        sources=[("Ogród Botaniczny UAM: godziny otwarcia", "https://ogrod.amu.edu.pl/en/en-godziny-otwarcia/"),
                 ("PIK Poznań: Ogród Botaniczny UAM", "https://pik.poznan.pl/miejsca/ogrod-botaniczny-uniwersytetu-im-adama-mickiewicza-w-poznaniu/"),
                 ("Wikipedia: Ogród Botaniczny UAM", "https://pl.wikipedia.org/wiki/Ogród_Botaniczny_Uniwersytetu_im._Adama_Mickiewicza_w_Poznaniu")],
    ),
    dict(
        slug="palmiarnia", cat="przyroda", name="Palmiarnia Poznańska",
        img="palmiarnia-hero", img_alt="Wnętrze Palmiarni Poznańskiej",
        short="Jedna z największych palmiarni w Europie. Obecnie zamknięta z powodu przebudowy.",
        badge="Zamknięte",
        status=("closed", "Palmiarnia jest czasowo zamknięta dla zwiedzających w związku z przebudową obiektu (komunikat z 31.08.2026). Data ponownego otwarcia nie została ogłoszona."),
        lead="Palmiarnia w Parku Wilsona działa od 1911 roku. Ma 4600 m² powierzchni i jest największą palmiarnią w Polsce oraz jedną z największych w Europie.",
        sections=[
            ("O miejscu", [
                "W 12 pawilonach rośnie około 1100 gatunków roślin. W akwariach żyje 170 gatunków ryb.",
                "Palmiarnię zamknięto już raz, w 1978 roku, z powodu złego stanu konstrukcji. Po przebudowie z lat 1983–1992 otwarto ją ponownie w październiku 1992 roku.",
            ]),
            ("Warto wiedzieć", [
                "Park Wilsona, w którym stoi Palmiarnia, jest dostępny normalnie.",
                "O terminie otwarcia palmiarnia poinformuje na swojej stronie internetowej.",
            ]),
        ],
        address="ul. Matejki 18, Poznań",
        hours=[("Obecnie", "zamknięte (przebudowa)")],
        tickets=[("Obecnie", "brak zwiedzania")],
        phone=None, www=("palmiarnia.poznan.pl", "https://palmiarnia.poznan.pl/"),
        credit="palmiarnia-hero",
        sources=[("Palmiarnia Poznańska: komunikat o zamknięciu", "https://palmiarnia.poznan.pl/"),
                 ("Wikipedia: Palmiarnia Poznańska", "https://pl.wikipedia.org/wiki/Palmiarnia_Poznańska")],
    ),

    # ─── RODZINA ───
    dict(
        slug="nowe-zoo", cat="rodzina", name="Nowe Zoo",
        img="zoo", img_alt="Słonie w Nowym Zoo w Poznaniu",
        short="120 hektarów lasu, słoniarnia, azyl dla niedźwiedzi i ptaki drapieżne.",
        badge="Codziennie",
        status=None,
        lead="Nowe Zoo otwarto 16 września 1974 roku na Białej Górze nad Maltą. Ma 120 hektarów powierzchni i jest drugim co do wielkości ogrodem zoologicznym w Polsce.",
        sections=[
            ("Co zobaczyć", [
                "Słoniarnię otwartą w 2008 roku, z wybiegiem o powierzchni 2,5 hektara.",
                "Trzyhektarowy azyl dla niedźwiedzi, stworzony razem z niemiecko-austriacką fundacją.",
                "Kolekcję ptaków drapieżnych i sów, jedną z najbogatszych w Europie.",
                "Pawilon nosorożców czarnych i pawilon zwierząt nocnych.",
                "Fort III z lat 1877–1881, fragment dawnej Twierdzy Poznań.",
            ]),
            ("Warto wiedzieć", [
                "Wygodnie dojechać tu Kolejką Parkową Maltanka, która kursuje wzdłuż jeziora do stacji Zwierzyniec przy wejściu do zoo.",
                "Biletu nie trzeba drukować, wystarczy kod w telefonie.",
                "Parking jest płatny od 1 kwietnia do 31 października.",
                "Kasy zamykają się godzinę przed zamknięciem zoo.",
            ]),
        ],
        address="ul. Krańcowa 81, Poznań",
        hours=[("Marzec i październik", "9:00–17:00"), ("Kwiecień–wrzesień", "9:00–19:00"), ("Listopad–luty", "9:00–16:00")],
        tickets=[("III–X, pn–pt", "45 zł, ulgowy 30 zł, rodzinny 80 zł"), ("III–X, sb–nd i święta", "55 zł, ulgowy 35 zł, rodzinny 115 zł"), ("XI–II", "20 zł, rodzinny 35 zł"), ("Dzieci do 3 lat", "bezpłatnie")],
        phone="+48 61 646 33 44", www=("zoo.poznan.pl", "https://zoo.poznan.pl/informacje-nowe-zoo/"),
        credit="zoo",
        sources=[("Zoo Poznań: ceny biletów", "https://zoo.poznan.pl/ceny-biletow-wstepu-do-ogrodu-zoologicznego/"),
                 ("Zoo Poznań: informacje – Nowe Zoo", "https://zoo.poznan.pl/informacje-nowe-zoo/"),
                 ("Wikipedia: Nowe Zoo w Poznaniu", "https://pl.wikipedia.org/wiki/Nowe_Zoo_w_Poznaniu")],
    ),
    dict(
        slug="stare-zoo", cat="rodzina", name="Stare Zoo",
        img="stare-zoo", img_alt="Grota w Starym Zoo w Poznaniu",
        short="Jedno z najstarszych zoo w Polsce, dziś bezpłatny park blisko dworca.",
        badge="Wstęp wolny",
        status=None,
        lead="Stare Zoo powstało w 1871 roku i jest drugim najstarszym ogrodem zoologicznym w Polsce. Od 2009 roku działa jako bezpłatny park z mniejszymi zwierzętami.",
        sections=[
            ("Co zobaczyć", [
                "Pawilon Zwierząt Zmiennocieplnych z 2012 roku z gadami, płazami i rybami, w tym waranami z Komodo.",
                "Zabytkową grotę z 1906 roku, pawilon naczelnych z 1927 roku i woliery dla ptaków brodzących z 1924 roku.",
                "Muzeum Historii Zoo w dawnej lwiarni, otwarte w 2022 roku, również bezpłatne.",
            ]),
            ("Warto wiedzieć", [
                "Zoo zajmuje 5,24 hektara na Jeżycach, niedaleko dworca Poznań Główny. To dobre miejsce na krótki spacer z dziećmi.",
            ]),
        ],
        address="ul. Zwierzyniecka 19, Poznań",
        hours=[("Marzec i październik", "9:00–17:00"), ("Kwiecień–wrzesień", "9:00–19:00"), ("Listopad–luty", "9:00–16:00")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone="+48 61 848 08 47", www=("zoo.poznan.pl", "https://zoo.poznan.pl/informacje-stare-zoo/"),
        credit="stare-zoo",
        sources=[("Zoo Poznań: informacje – Stare Zoo", "https://zoo.poznan.pl/informacje-stare-zoo/"),
                 ("Wikipedia: Stare Zoo w Poznaniu", "https://pl.wikipedia.org/wiki/Stare_Zoo_w_Poznaniu")],
    ),
    dict(
        slug="kolejka-maltanka", cat="rodzina", name="Kolejka Parkowa Maltanka",
        img="kolejka-maltanka", img_alt="Kolejka Parkowa Maltanka na mijance",
        short="Wąskotorowa kolejka wzdłuż Malty do Nowego Zoo. Kursuje sezonowo.",
        badge="Sezonowo",
        status=None,
        lead="Maltanka to wąskotorowa kolejka parkowa prowadzona przez MPK Poznań. Kursuje wzdłuż Jeziora Maltańskiego między stacjami Maltanka i Zwierzyniec, przy wejściu do Nowego Zoo.",
        sections=[
            ("Warto wiedzieć", [
                "Sezon 2026 zaczął się 12 kwietnia, a od 24 kwietnia kolejka kursuje codziennie.",
                "Od sezonu 2026 można kupić bilet tam i z powrotem. Bilety sprzedają obie stacje końcowe.",
                "Po drodze kolejka dojeżdża w pobliże Term Maltańskich.",
            ]),
        ],
        address="Kolejka Parkowa Maltanka, Poznań",
        hours=[("Dni robocze", "co godzinę, 9:30–18:30"), ("Weekendy i święta", "co 30 minut, 10:00–19:00")],
        tickets=[("W jedną stronę", "18 zł, ulgowy (do 16 lat) 12 zł, rodzinny 48 zł"), ("Tam i z powrotem", "24 zł, ulgowy 16 zł, rodzinny 64 zł")],
        phone=None, www=("mpk.poznan.pl", "https://www.mpk.poznan.pl/strefa-pasazera/turystyka/maltanka/"),
        credit="kolejka-maltanka",
        sources=[("MPK Poznań: bilety na Maltankę 2026", "https://www.mpk.poznan.pl/nowy-rodzaj-biletow-na-maltanke-w-sezonie-2026/"),
                 ("MPK Poznań: start sezonu 2026", "https://www.mpk.poznan.pl/kolejka-parkowa-maltanka-rozpoczyna-sezon-pierwszy-kurs-w-niedziele-12-kwietnia-2026/")],
    ),
    dict(
        slug="termy-maltanskie", cat="rodzina", name="Termy Maltańskie",
        img="termy-maltanskie", img_alt="Aquapark w Termach Maltańskich",
        short="Aquapark, baseny sportowe i strefa saun nad Maltą, czynne do 23:00.",
        badge="Codziennie",
        status=None,
        lead="Termy Maltańskie to kompleks basenów nad Jeziorem Maltańskim. Mają aquapark, baseny sportowe i strefę saun.",
        sections=[
            ("Warto wiedzieć", [
                "Kompleks jest zamknięty w Wielką Sobotę i Wielkanoc, 1 listopada, 24 i 25 grudnia oraz 31 grudnia.",
                "Osoby na wózkach wchodzą przez dolny hol, na poziomie terenu.",
                "Na miejscu można wypożyczyć ręczniki i szlafroki. Jest też pokój dla rodzin z przewijakiem.",
            ]),
        ],
        address="ul. Termalna 1, 61-028 Poznań",
        hours=[("Aquapark", "codziennie 9:00–23:00"), ("Baseny sportowe", "pn–sb 6:00–23:00, nd i święta 7:00–23:00"), ("Strefa saun", "pn–pt 14:30–23:00, sb–nd 11:30–23:00")],
        tickets=[("Aquapark, 1 godzina", "od ok. 46 zł"), ("Dzieci do 3 lat", "bezpłatnie"), ("Pełny cennik", "na stronie term")],
        phone="+48 459 595 590", www=("termymaltanskie.com.pl", "https://termymaltanskie.com.pl/"),
        credit="termy-maltanskie",
        sources=[("Termy Maltańskie: FAQ", "https://termymaltanskie.com.pl/faq/")],
    ),
    dict(
        slug="malta-ski", cat="rodzina", name="Malta Ski",
        img="malta-ski", img_alt="Stok Malta Ski zimą",
        short="Sztuczny stok, letni tor saneczkowy i kolejka górska nad jeziorem.",
        badge="Zależnie od pogody",
        status=None,
        lead="Malta Ski to całoroczny ośrodek nad Jeziorem Maltańskim. Zimą działa sztuczny stok narciarski, a latem letni tor saneczkowy i inne atrakcje.",
        sections=[
            ("Co tu jest", [
                "Sztuczny stok narciarski o długości około 150 metrów.",
                "Letni tor saneczkowy o długości 560 metrów.",
                "Całoroczną kolejkę górską Adrenaline, minigolf i plac zabaw.",
            ]),
            ("Warto wiedzieć", [
                "Godziny otwarcia zależą od pogody i zmieniają się w ciągu roku. Aktualne godziny i cennik podaje strona maltaski.pl.",
                "Kolejka górska i tor saneczkowy są partnerami Poznańskiej Karty Turystycznej.",
            ]),
        ],
        address="ul. Wiankowa 2, Poznań",
        hours=[("Godziny", "zależne od pogody, na maltaski.pl")],
        tickets=[("Cennik", "na maltaski.pl")],
        phone=None, www=("maltaski.pl", "https://maltaski.pl/"),
        credit="malta-ski",
        sources=[("Visit Poznań: Malta Ski", "https://visitpoznan.pl/centrum-sportowo-rekreacyjne-malta-ski"),
                 ("Malta Ski", "https://maltaski.pl/")],
    ),

    # ─── WSPÓŁCZESNY ───
    dict(
        slug="stary-browar", cat="wspolczesny", name="Stary Browar",
        img="stary-browar", img_alt="Ceglane budynki Starego Browaru",
        short="XIX-wieczny browar Huggerów przebudowany na centrum handlu i sztuki, z rzeźbami Mitoraja i nagradzaną architekturą.",
        badge="Bezpłatnie",
        status=None,
        lead="Stary Browar to nie tylko centrum handlowe. To XIX-wieczny ceglany browar Huggerów, zamieniony w 2003 roku w centrum handlu i sztuki według idei „50 50”: połowa to biznes, połowa to sztuka. Po korytarzach i dziedzińcach można chodzić jak po galerii z rzeźbami i instalacjami znanych artystów, a wstęp jest bezpłatny.",
        sections=[
            ("Historia", [
                "Ambrosius Hugger, piwowar ze Schwarzwaldu, otworzył pierwszy browar w Poznaniu w 1844 roku przy ulicy Wronieckiej. Jego synowie Julius i Alfons w 1876 roku kupili posesję na rogu Półwiejskiej i zbudowali tu Browary Huggerów. W 1918 roku zakład warzył prawie 72 tysiące hektolitrów piwa rocznie.",
                "W czasie walk o Poznań w 1945 roku browar został mocno zniszczony. Po wojnie go upaństwowiono, a w 1980 roku zamknięto. Budynki niszczały, a do 1997 roku działała w nich tylko mała wytwórnia wód gazowanych.",
                "W 1998 roku teren kupiła spółka Grażyny Kulczyk. Zanim ruszyła budowa, w ruinach wystawiano spektakle, w tym „Makbeta” Verdiego transmitowanego na żywo w TVP2. Pierwszą część centrum, Atrium, otwarto 5 listopada 2003 roku, Dziedziniec Sztuki 29 kwietnia 2004 roku, a drugie skrzydło, Pasaż, 11 marca 2007 roku. Od 2015 roku centrum ma innego właściciela, ale dzieła sztuki z kolekcji Grażyny Kulczyk zostały na swoich miejscach.",
            ]),
            ("Architektura", [
                "Najstarsze budynki, czyli Warzelnia, Słodownia i Suszarnia z charakterystycznym kominem, powstały około 1890 roku. Zbudowano je w stylu arkadowym (Rundbogenstil), typowym dla ówczesnych fabryk: z czerwonej cegły licówki, z półkoliście zamkniętymi oknami i ceglanymi ozdobami.",
                "Przebudowę zaprojektowało poznańskie Studio ADS (architekci Piotr Barełkowski i Przemysław Borkowicz). Stare mury połączono z nowoczesnymi konstrukcjami ze stali i szkła. Wystrój pasaży zaprojektował scenograf Ryszard Kaja, autor słynnych plakatów.",
                "Stary Browar znalazł się wśród 20 budynków wybranych na wystawę „Polska. Ikony architektury”, pokazującą najważniejszą polską architekturę po 1989 roku. Dostał też dwie nagrody im. Jana Baptysty Quadro dla najlepszego budynku roku w Poznaniu: za 2003 i za 2007 rok. Międzynarodowa Rada Centrów Handlowych (ICSC) uznała go za najlepsze centrum handlowe na świecie w 2005 roku, a w 2008 roku ponownie w kategorii rozbudów.",
                "Po zmroku warto obejrzeć zachodnią fasadę Pasażu. To wspólne dzieło Studia ADS i artysty Adama Garnka: szklaną bryłę dzielą poziome pasy, a instalacja świetlna w środku zamienia ją w migoczącą, półprzezroczystą ozdobę.",
            ]),
            ("Dzieła sztuki do zobaczenia", [
                "„Thsuki-no-hikari” (Blask Księżyca) Igora Mitoraja w Atrium: monumentalny fragment ludzkiej twarzy wzorowany na rzeźbie antycznej. Poznaniacy mówią na nią „Maska” albo po prostu „Mitoraj” i to jedno z najpopularniejszych miejsc spotkań w mieście.",
                "„Eros alato” (Eros skrzydlaty) i „Torso del lago” (Tors nad jeziorem), dwie mniejsze prace Mitoraja zawieszone na ceglanych ścianach. Pęknięcia i rysy na idealnych, klasycznych ciałach mówią o przemijaniu.",
                "„Opertus Lunula Umbra” (Ukryty Cień Księżyca) koreańskiego artysty U-Rama Choe: kinetyczna rzeźba zawieszona nad Szachownicą. O określonych godzinach porusza się jak oddychające zwierzę, dlatego poznaniacy nazywają ją „Krewetką”.",
                "„Konflikt między dobrem a złem” Piotra Kurki: czarno-biała marmurowa ławka, na której można usiąść. Na białej części siedzi kruk. Według lokalnej legendy kto go pogłaszcze, łatwiej rozwiąże życiowe problemy.",
                "„Citta Gentile” (Wrażliwe Miasto) Alessandra Mendiniego, słynnego włoskiego designera: rzeźby w kształcie liter wymyślonego przez niego alfabetu, przygotowane specjalnie dla Starego Browaru.",
                "„Henyo-Penyo Myomyonmyo” japońskiego artysty Mr., ucznia Takashiego Murakamiego. Bywalcy nazywają tę postać chłopca w dżinsach „Heńkiem”. Rzeźba należy do cyklu nawiązującego do ataku na Hiroszimę.",
                "Instalacja Leona Tarasewicza: zielono-żółte pasy, które w 2003 roku, na 750-lecie Poznania, zdobiły kolumny Teatru Wielkiego. Dziś są w Atrium, na jednej z najbardziej ruchliwych tras w budynku.",
                "Kufel z brązu Wojciecha Kujawskiego, ozdobiony sześcioma postaciami, odsłonięty w 2007 roku na otwarcie Pasażu. Przy odsłonięciu ustanowiono dwa rekordy Guinnessa: największego kufla do piwa na świecie i największej ilości piwa wypitej z jednego naczynia.",
            ]),
            ("Wystawy i zwiedzanie", [
                "Na Dziedzińcu działa Pop Culture Gallery, prowadzona przez Stary Browar. Pokazuje wystawy łączące modę, sztukę, design i technologię. Były tu już m.in. wystawy Andy'ego Warhola, Björk, Davida LaChapelle'a, Gianniego Versace i Ryszarda Kai. Aktualną wystawę sprawdzisz na stronie centrum.",
                "Stary Browar organizuje zwiedzanie z przewodnikiem po architekturze, historii i kolekcji dzieł sztuki. Termin trzeba uzgodnić z punktem informacyjnym co najmniej dwa tygodnie wcześniej (informacja@starybrowar.com, tel. 61 859 60 50).",
                "W kompleksie działa pięciogwiazdkowy hotel Blow Up Hall (wejście od ul. Kościuszki 42), który po kilkuletniej przerwie znów przyjmuje gości. W hotelu, restauracji arte i pasażu są rzeźby, instalacje i sztuka użytkowa z kolekcji właścicieli, tworzona we współpracy z polskimi artystami. Restauracja arte jest czynna codziennie 12:00–22:00, a b.bar 16:00–24:00 (rezerwacja stolika: tel. 61 629 94 02).",
                "Przy centrum jest zabytkowy park, dobre miejsce na odpoczynek po zwiedzaniu.",
            ]),
        ],
        address="ul. Półwiejska 42, 61-888 Poznań",
        hours=[("Poniedziałek–sobota", "9:00–21:00"), ("Niedziele handlowe", "10:00–20:00"), ("Pozostałe niedziele", "czynne tylko wybrane lokale"), ("Pop Culture Gallery", "12:00–20:00")],
        tickets=[("Wstęp i oglądanie dzieł sztuki", "bezpłatnie"), ("Wystawy w Pop Culture Gallery", "zależnie od wystawy")],
        phone="+48 61 859 60 50", www=("starybrowar5050.com", "https://starybrowar5050.com/o-centrum/"),
        credit="stary-browar",
        sources=[("Stary Browar: o centrum, historia i dzieła sztuki", "https://starybrowar5050.com/o-centrum/"),
                 ("Stary Browar: Pop Culture Gallery", "https://starybrowar5050.com/sklepy/pop-culture-gallery-stary-browar/"),
                 ("Wikipedia: Stary Browar (Poznań)", "https://pl.wikipedia.org/wiki/Stary_Browar_(Pozna%C5%84)"),
                 ("Wikipedia: Browar Huggerów", "https://pl.wikipedia.org/wiki/Browar_Hugger%C3%B3w"),
                 ("Poznański Prestiż: wywiad z zarządem Starego Browaru (2023)", "https://poznanskiprestiz.pl/pp-x-stary-browar/stary-browar-od-20-lat-w-sercu-poznania/"),
                 ("Hotel Blow Up Hall: sztuka i książki", "https://blowuphall.com/sztuka-i-ksiazki/"),
                 ("Hotel Blow Up Hall: restauracja", "https://blowuphall.com/restauracja/"),
                 ("poznan.pl: Stary Browar", "https://www.poznan.pl/mim/turystyka/inne-atrakcje,poi,3391/stary-browar,46255.html")],
    ),
    dict(
        slug="srodka", cat="wspolczesny", name="Śródka i mural 3D",
        img="srodka", img_alt="Trójwymiarowy mural na Śródce",
        short="Trójwymiarowy mural z trębaczem na dachu, tuż obok Bramy Poznania.",
        badge="Bezpłatnie",
        status=None,
        lead="Śródka to dzielnica po wschodniej stronie Cybiny, naprzeciw Ostrowa Tumskiego. Jej najbardziej znany punkt to trójwymiarowy mural „Opowieść śródecka z trębaczem na dachu i kotem w tle”.",
        sections=[
            ("O muralu", [
                "Mural odsłonięto 1 października 2015 roku. Koncepcję przygotował Radosław Barek, a pomysłodawcą był radny osiedlowy Gerard Cofta.",
                "Malowidło powstało na podstawie fotografii Śródki z lat 20. XX wieku i zajmuje ścianę kamienicy przy Rynku Śródeckim.",
            ]),
            ("Warto wiedzieć", [
                "Śródkę łatwo połączyć z wizytą w Bramie Poznania i na Ostrowie Tumskim. Wszystkie trzy miejsca leżą blisko siebie.",
            ]),
        ],
        address="ul. Śródka 3, Poznań",
        hours=[("Mural", "widoczny całą dobę")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("visitpoznan.pl", "https://visitpoznan.pl/"),
        credit="srodka",
        sources=[("poznan.pl: Trójwymiarowy mural na Śródce", "https://www.poznan.pl/mim/info/news/trojwymiarowy-mural-na-srodce,85708.html"),
                 ("Wikipedia: Opowieść śródecka", "https://pl.wikipedia.org/wiki/Opowieść_śródecka_z_trębaczem_na_dachu_i_kotem_w_tle")],
    ),
]

# Atrakcje dodane 28.09.2026 (druga tura). Po scaleniu lista jest sortowana według kategorii.
MORE = [
    dict(
        slug="pomnik-czerwca-1956", cat="pomniki", name="Pomnik Poznańskiego Czerwca 1956",
        img="pomnik-czerwca-1956", img_alt="Dwa połączone krzyże Pomnika Poznańskiego Czerwca 1956",
        short="Poznańskie Krzyże upamiętniające pierwszy masowy protest przeciw władzy komunistycznej.",
        badge="Bezpłatnie",
        status=None,
        lead="Pomnik na placu Mickiewicza, nazywany Poznańskimi Krzyżami, upamiętnia bunt robotników z 28 czerwca 1956 roku, pierwszy masowy protest przeciw władzy komunistycznej w Polsce.",
        sections=[
            ("O pomniku", [
                "Pomnik odsłonięto 28 czerwca 1981 roku, w 25. rocznicę wydarzeń. Zaprojektowali go rzeźbiarz Adam Graczyk i architekt Włodzimierz Wojciechowski.",
                "Tworzą go dwa połączone stalowe krzyże o wysokości 19,5 i 21 metrów. U ich podstawy stoi rzeźba orła.",
                "Na lewym krzyżu widnieje data 1956. Na prawym umieszczono daty kolejnych protestów w PRL: 1968, 1970, 1976, 1980 i 1981. Napis nawiązuje do haseł robotników: „Za wolność, prawo i chleb”.",
            ]),
            ("Warto wiedzieć", [
                "Pomnik stoi w Dzielnicy Cesarskiej, naprzeciw Zamku Cesarskiego. W zamku działa Muzeum Powstania Poznańskiego – Czerwiec 1956.",
            ]),
        ],
        address="pl. Adama Mickiewicza, Poznań",
        hours=[("Pomnik", "dostępny całą dobę")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("visitpoznan.pl", "https://visitpoznan.pl/"),
        credit="pomnik-czerwca-1956",
        sources=[("Wikipedia: Pomnik Ofiar Czerwca 1956", "https://pl.wikipedia.org/wiki/Pomnik_Ofiar_Czerwca_1956"),
                 ("Visit Poznań: Muzeum Powstania Poznańskiego – Czerwiec 1956", "https://visitpoznan.pl/muzeum-powstania-poznanskiego-czerwiec-1956")],
    ),
    dict(
        slug="genius-loci", cat="zabytki", name="Rezerwat Archeologiczny Genius Loci",
        img="genius-loci", img_alt="Zachowany wał obronny grodu w rezerwacie Genius Loci",
        short="Oryginalny wał obronny grodu z X wieku na Ostrowie Tumskim.",
        badge="Nd wstęp wolny",
        status=None,
        lead="Rezerwat Genius Loci na Ostrowie Tumskim pokazuje doskonale zachowane konstrukcje wału obronnego grodu poznańskiego z X wieku. Prowadzi go Muzeum Archeologiczne, a otwarto go w 2012 roku.",
        sections=[
            ("Co zobaczyć", [
                "Drewniane konstrukcje wału obronnego grodu z czasów pierwszych Piastów, zachowane w ziemi przez ponad tysiąc lat.",
                "Wystawy i prezentacje multimedialne, które pokazują, jak budowano umocnienia we wczesnym średniowieczu.",
            ]),
            ("Warto wiedzieć", [
                "Dojazd: tramwaje 4, 8 i 17 albo autobusy 67 i 83 do przystanku Katedra.",
                "Obiekt jest przystosowany dla osób z niepełnosprawnościami.",
                "Jest bilet na trzy miejsca na Ostrowie Tumskim (Brama Poznania, Genius Loci i Akademia Lubrańskiego) w cenie 49 zł.",
                "Ostatnie wejście jest pół godziny przed zamknięciem.",
            ]),
        ],
        address="ul. Ks. I. Posadzego 3, 61-108 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–czwartek", "10:00–16:00"), ("Piątek–sobota", "10:00–18:00"), ("Niedziela", "10:00–15:00")],
        tickets=[("Normalny", "15 zł"), ("Ulgowy", "10 zł"), ("Rodzinny (2 dorosłych + 4 dzieci)", "40 zł"), ("Niedziela", "wstęp wolny na ekspozycje")],
        phone="+48 61 852 21 67", www=("rezerwat.muzarp.poznan.pl", "https://rezerwat.muzarp.poznan.pl/"),
        credit="genius-loci",
        sources=[("Genius Loci: bilety", "https://rezerwat.muzarp.poznan.pl/pl/bilety"),
                 ("Genius Loci: godziny otwarcia", "https://rezerwat.muzarp.poznan.pl/pl/godziny-otwarcia"),
                 ("Genius Loci: dla zwiedzających", "https://rezerwat.muzarp.poznan.pl/pl/dla-zwiedzajacych")],
    ),
    dict(
        slug="wzgorze-sw-wojciecha", cat="zabytki", name="Wzgórze św. Wojciecha",
        img="wzgorze-sw-wojciecha", img_alt="Kościół św. Wojciecha w Poznaniu",
        short="Krypta Zasłużonych Wielkopolan: grób Józefa Wybickiego i serce gen. Dąbrowskiego.",
        badge="Po umówieniu",
        status=None,
        lead="Przy kościele św. Wojciecha znajduje się Krypta Zasłużonych Wielkopolan, założona w 1923 roku z inicjatywy proboszcza ks. Bogusława Kościelskiego. Wzorowano ją na krakowskiej Skałce.",
        sections=[
            ("Kto tu spoczywa", [
                "Józef Wybicki, autor słów „Mazurka Dąbrowskiego”, oraz Antoni Kosiński, współtwórca Legionów Dąbrowskiego.",
                "Heliodor Święcicki, założyciel i pierwszy rektor Uniwersytetu Poznańskiego.",
                "Kompozytorzy Feliks Nowowiejski, twórca melodii „Roty”, i Tadeusz Szeligowski.",
                "W krypcie złożono też serce gen. Jana Henryka Dąbrowskiego i szczątki gen. Ignacego Prądzyńskiego. W nawie południowej kościoła spoczywa Karol Marcinkowski, lekarz i społecznik.",
            ]),
            ("Warto wiedzieć", [
                "W 1997 roku otwarto nową część krypty przy nawie południowej kościoła.",
                "Kryptę zwiedza się tylko po wcześniejszym umówieniu telefonicznym z parafią. W czasie mszy i uroczystości jest nieczynna.",
            ]),
        ],
        address="ul. Święty Wojciech 1, 61-746 Poznań",
        hours=[("Krypta", "po uzgodnieniu telefonicznym"), ("W czasie mszy", "nieczynna")],
        tickets=[("Zwiedzanie", "po uzgodnieniu z parafią")],
        phone="+48 793 842 860", www=("kultura.poznan.pl", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/krypta-zasluzonych-wielkopolan,35331.html"),
        credit="wzgorze-sw-wojciecha",
        sources=[("kultura.poznan.pl: Krypta Zasłużonych Wielkopolan", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202,12/krypta-zasluzonych-wielkopolan,35331.html")],
    ),
    dict(
        slug="muzeum-instrumentow", cat="muzea", name="Muzeum Instrumentów Muzycznych",
        img="muzeum-instrumentow", img_alt="Kamienica Muzeum Instrumentów Muzycznych przy Starym Rynku",
        short="Skrzypce Wieniawskiego i klawesyn, na którym grał młody Mozart.",
        badge="Pn nieczynne",
        status=None,
        lead="Muzeum Instrumentów Muzycznych, oddział Muzeum Narodowego, mieści się w kamienicy przy Starym Rynku. Wystawa stała „Nowe brzmienie” zajmuje 16 sal i opowiada o muzyce europejskiej od późnego średniowiecza po XX wiek.",
        sections=[
            ("Co zobaczyć", [
                "Skrzypce Henryka Wieniawskiego.",
                "Klawesyn, na którym grali młody Wolfgang Amadeusz Mozart i Wilhelm Friedemann Bach.",
                "Instrumenty pokazane w kontekście epoki, zespołu, miejsca i tradycji. Na tabletach z przewodnikiem multimedialnym można posłuchać, jak brzmią.",
            ]),
            ("Warto wiedzieć", [
                "Od 1946 roku działa tu jedyna w Polsce pracownia konserwacji instrumentów muzycznych.",
                "Z Poznańską Kartą Turystyczną wstęp jest bezpłatny.",
                "Budynek jest tylko częściowo dostępny dla osób z niepełnosprawnościami.",
            ]),
        ],
        address="Stary Rynek 45, 61-772 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–środa", "10:00–16:00"), ("Czwartek", "10:00–18:00"), ("Piątek", "10:00–20:00"), ("Sobota–niedziela", "10:00–17:00")],
        tickets=[("Ceny biletów", "na mnp.art.pl"), ("Z Poznańską Kartą Turystyczną", "bezpłatnie")],
        phone=None, www=("mnp.art.pl", "https://mnp.art.pl/"),
        credit="muzeum-instrumentow",
        sources=[("kultura.poznan.pl: Muzeum Instrumentów Muzycznych", "https://kultura.poznan.pl/mim/kultura/muzea-w-poznaniu,poi,202/muzeum-instrumentow-muzycznych-oddzial-muzeum-narodowego,15707.html"),
                 ("Visit Poznań: Muzeum Instrumentów Muzycznych", "https://visitpoznan.pl/muzeum-instrumentow-muzycznych")],
    ),
    dict(
        slug="muzeum-czerwca-1956", cat="muzea", name="Muzeum Poznańskiego Czerwca 1956",
        img="muzeum-czerwca-1956", img_alt="Ekspozycja Muzeum Powstania Poznańskiego – Czerwiec 1956",
        short="Historia buntu robotników z 28 czerwca 1956 roku, w Zamku Cesarskim.",
        badge="Nd wstęp wolny",
        status=None,
        lead="Muzeum Powstania Poznańskiego – Czerwiec 1956 opowiada o buncie robotniczym z 28 czerwca 1956 roku, pierwszym masowym proteście przeciw władzy komunistycznej w Polsce. Mieści się w Zamku Cesarskim.",
        sections=[
            ("Co zobaczyć", [
                "Reprodukcje fotografii z czerwca 1956 roku, pamiątki po ofiarach i makiety projektów Pomnika Poznańskiego Czerwca.",
                "Materiały multimedialne o historii Polski od 1945 roku do końca PRL.",
            ]),
            ("Warto wiedzieć", [
                "Od 1 stycznia 2026 roku muzeum jest samodzielną instytucją kultury. Po przerwie otworzyło się ponownie 1 lutego 2026 roku.",
                "Dzień bezpłatnego wstępu przeniesiono z wtorku na niedzielę.",
                "Z Poznańską Kartą Turystyczną wstęp jest bezpłatny.",
                "Oprowadzanie z przewodnikiem: 100 zł dla grupy do 25 osób, 40 zł dla maksymalnie 5 osób.",
            ]),
        ],
        address="ul. Święty Marcin 80/82 (Zamek Cesarski), Poznań",
        hours=[("Godziny otwarcia", "potwierdź telefonicznie przed wizytą")],
        tickets=[("Normalny", "15 zł"), ("Ulgowy", "10 zł"), ("Niedziela", "wstęp wolny")],
        phone="+48 61 852 94 64", www=("wmn.poznan.pl", "https://www.wmn.poznan.pl/lokalizacja_wystaw/muzeum-powstania-poznanskiego/"),
        credit="muzeum-czerwca-1956",
        sources=[("WMN: ponowne otwarcie muzeum (1.02.2026)", "https://www.wmn.poznan.pl/moje-aktualnosci/muzeum-powstania-poznanskiego-czerwiec-1956-w-poznaniu-ponownie-otwiera-sie-dla-zwiedzajacych/"),
                 ("WMN: Muzeum Powstania Poznańskiego – Czerwiec 1956", "https://www.wmn.poznan.pl/lokalizacja_wystaw/muzeum-powstania-poznanskiego/"),
                 ("Visit Poznań: Muzeum Powstania Poznańskiego", "https://visitpoznan.pl/muzeum-powstania-poznanskiego-czerwiec-1956")],
    ),
    dict(
        slug="muzeum-kultur-swiata", cat="muzea", name="Muzeum Kultur Świata",
        img="muzeum-kultur-swiata", img_alt="Klasycystyczny budynek Muzeum Kultur Świata przy ul. Grobla",
        short="Dawne Muzeum Etnograficzne w klasycystycznej siedzibie loży masońskiej.",
        badge="Pn nieczynne",
        status=None,
        lead="Muzeum Kultur Świata to dawne Muzeum Etnograficzne, oddział Muzeum Narodowego. Nową nazwę dostało w 2025 roku. Mieści się w późnoklasycystycznym budynku z lat 1817–1819, dawnej siedzibie loży masońskiej.",
        sections=[
            ("Co zobaczyć", [
                "Zbiory kultury polskiej i wielkopolskiej oraz kultur z odległych regionów świata, pokazywane na wystawach czasowych.",
            ]),
            ("Warto wiedzieć", [
                "Wejście do muzeum jest od ul. Mostowej 7, przez park.",
                "Muzeum organizuje oprowadzania, lekcje, warsztaty, koncerty i spotkania weekendowe.",
            ]),
        ],
        address="ul. Grobla 25 (wejście od ul. Mostowej 7), 61-858 Poznań",
        hours=[("Poniedziałek", "nieczynne"), ("Wtorek–środa", "10:00–16:00"), ("Czwartek", "10:00–18:00"), ("Piątek", "10:00–20:00"), ("Sobota–niedziela", "10:00–17:00")],
        tickets=[("Ceny biletów", "na mnp.art.pl")],
        phone="+48 61 852 30 06", www=("mnp.art.pl", "https://mnp.art.pl/"),
        credit="muzeum-kultur-swiata",
        sources=[("poznan.pl: Muzeum Kultur Świata", "https://www.poznan.pl/mim/turystyka/muzea-w-poznaniu,poi,202,12/muzeum-etnograficzne-oddzial-muzeum-narodowego,15728.html"),
                 ("PIK Poznań: Muzeum Kultur Świata", "https://pik.poznan.pl/miejsca/muzeum-etnograficzne-w-poznaniu/")],
    ),
    dict(
        slug="muzeum-sienkiewicza", cat="muzea", name="Muzeum Literackie Henryka Sienkiewicza",
        img="muzeum-sienkiewicza", img_alt="Kamienica przy Starym Rynku 84",
        short="Pamiątki po nobliście w XVI-wiecznej kamienicy na rynku. W soboty wstęp wolny.",
        badge="Sb wstęp wolny",
        status=None,
        lead="Muzeum Literackie Henryka Sienkiewicza to oddział Biblioteki Raczyńskich w XVI-wiecznej kamienicy przy Starym Rynku 84. Jest najmłodszym muzeum poświęconym pisarzowi w Polsce.",
        sections=[
            ("O muzeum", [
                "Zbiory zgromadził Ignacy Moś, kolekcjoner, który całe życie zbierał pamiątki po nobliście i przekazał je Bibliotece Raczyńskich.",
                "Sienkiewicz był w Poznaniu tylko kilka razy i nigdy nie mieszkał w tej kamienicy.",
            ]),
            ("Co zobaczyć", [
                "Replikę medalu Nagrody Nobla z 1905 roku.",
                "Kolekcję rzeźbiarza Franciszka Ksawerego Blacka z odlewem prawej dłoni pisarza i jego maską pośmiertną.",
                "Fragment rękopisu „Potopu” i ponad 4000 książek w wielu językach, m.in. chińskim, hebrajskim, arabskim, wietnamskim i esperanto.",
                "Projekty scenografii do filmu „W pustyni i w puszczy” z 1973 roku.",
            ]),
        ],
        address="Stary Rynek 84, 61-772 Poznań",
        hours=[("Wtorek, piątek, sobota", "9:00–16:00"), ("Środa, czwartek", "12:00–19:00"), ("Poniedziałek, niedziela, święta", "nieczynne")],
        tickets=[("Normalny", "10 zł"), ("Ulgowy", "5 zł"), ("Sobota", "wstęp wolny")],
        phone="+48 61 852 89 71", www=("bracz.edu.pl", "https://bracz.edu.pl/muzeum-sienkiewicza/"),
        credit="muzeum-sienkiewicza",
        sources=[("Biblioteka Raczyńskich: Muzeum Sienkiewicza", "https://bracz.edu.pl/muzeum-sienkiewicza/"),
                 ("Visit Poznań: Muzeum Literackie Henryka Sienkiewicza", "https://visitpoznan.pl/muzeum-literackie-henryka-sienkiewicza")],
    ),
    dict(
        slug="muzeum-bambrow", cat="muzea", name="Muzeum Bambrów Poznańskich",
        img="muzeum-bambrow", img_alt="Studzienka z figurą Bamberki w Poznaniu",
        short="Historia osadników spod Bambergu, którzy w XVIII wieku zasiedlili podpoznańskie wsie.",
        badge="Pt–sb",
        status=None,
        lead="Muzeum prowadzi Towarzystwo Bambrów Poznańskich. Opowiada o osadnikach spod Bambergu we Frankonii, którzy w latach 1719–1753 przybyli do wsi wokół Poznania, zniszczonych przez wojnę północną i zarazę.",
        sections=[
            ("Kim byli Bambrzy", [
                "Pierwsi osadnicy przybyli do Lubonia w 1719 roku. Kolejni osiedlali się na Dębcu i Boninie (1730), na Ratajach i Wildzie (1746–1747) oraz na Jeżycach i Górczynie (1750–1753).",
                "Byli rolnikami i zaopatrywali miasto w żywność. Dostali korzystne warunki: dzierżawę ziemi, materiały budowlane, ziarno siewne i kilka lat zwolnienia z podatków.",
                "W XIX wieku ukształtował się charakterystyczny strój kobiecy z kwiatowym kornetem, który ważył nawet 3 kg. Pod koniec XIX wieku Bambrzy w większości się spolszczyli.",
            ]),
            ("Warto wiedzieć", [
                "Oprowadzanie po muzeum jest bezpłatne. Grupy zorganizowane powinny wcześniej zgłosić wizytę.",
                "Muzeum jest dostępne dla osób z niepełnosprawnościami.",
            ]),
        ],
        address="ul. Mostowa 7/9, 61-854 Poznań",
        hours=[("Piątek i sobota", "10:00–14:00")],
        tickets=[("Oprowadzanie", "bezpłatne, po umówieniu")],
        phone="+48 602 658 961", www=("bambrzy.poznan.pl", "https://www.bambrzy.poznan.pl/"),
        credit="muzeum-bambrow",
        sources=[("Towarzystwo Bambrów Poznańskich: informacje dla zwiedzających", "https://www.bambrzy.poznan.pl/node/7"),
                 ("Wikipedia: Bambrzy", "https://pl.wikipedia.org/wiki/Bambrzy")],
    ),
    dict(
        slug="rusalka", cat="przyroda", name="Jezioro Rusałka",
        img="rusalka", img_alt="Jezioro Rusałka w Poznaniu",
        short="Leśne jezioro z plażą i strzeżonym kąpieliskiem w zachodniej części miasta.",
        badge="Bezpłatnie",
        status=None,
        lead="Rusałka to jezioro o powierzchni 36,7 hektara w klinie zieleni Golęcin, w zachodniej części Poznania. Latem działa tu piaszczysta plaża z kąpieliskiem miejskim.",
        sections=[
            ("Kąpielisko", [
                "Kąpielisko ma 96 metrów linii brzegowej. W sezonie pilnują go ratownicy.",
                "Są dwie strefy: dla nieumiejących pływać, o głębokości do 1,2 metra (czerwone boje), i dla pływających, do 4 metrów (żółte boje).",
                "W 2026 roku sezon kąpielowy trwał od 20 czerwca do 6 września.",
            ]),
            ("Co jeszcze jest nad jeziorem", [
                "Plac zabaw, siłownia plenerowa, boiska do siatkówki plażowej i boccii, ścieżka rowerowa, park rozrywki Frajda oraz punkty gastronomiczne.",
                "Na kąpielisku jest wózek plażowy typu amfibia dla osób z niepełnosprawnościami. O dostępność pytaj ratowników.",
            ]),
        ],
        address="ul. Golęcińska 27, Poznań",
        hours=[("Teren wokół jeziora", "dostępny całą dobę"), ("Kąpielisko strzeżone", "w sezonie letnim")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("posir.poznan.pl", "https://posir.poznan.pl/obiekty/rusalka/kapielisko"),
        credit="rusalka",
        sources=[("POSiR: kąpielisko Rusałka", "https://posir.poznan.pl/obiekty/rusalka/kapielisko"),
                 ("Poznańskie Klimaty: sezon kąpielowy 2026", "https://www.poznanskieklimaty.pl/sezon-kapielowy-w-poznaniu-2026-kiedy-otwieraja-sie-plaze-nad-jeziorami/")],
    ),
    dict(
        slug="wielkopolski-park-narodowy", cat="przyroda", name="Wielkopolski Park Narodowy",
        img="wielkopolski-park-narodowy", img_alt="Jezioro Góreckie w Wielkopolskim Parku Narodowym",
        short="Lasy i jeziora polodowcowe tuż za miastem. Dojedziesz pociągiem.",
        badge="Wycieczka za miasto",
        status=None,
        lead="Wielkopolski Park Narodowy utworzono 16 kwietnia 1957 roku. Zajmuje prawie 7585 hektarów na południe od Poznania, między Luboniem, Stęszewem i Mosiną. Co roku odwiedza go około 1,2 miliona osób.",
        sections=[
            ("Co zobaczyć", [
                "Jeziora polodowcowe, a wśród nich Jezioro Góreckie z Wyspą Zamkową.",
                "Muzeum Przyrodnicze w Jeziorach, przy siedzibie parku.",
                "18 obszarów ochrony ścisłej o łącznej powierzchni 260 hektarów, z formami polodowcowymi i naturalnymi zbiorowiskami roślin.",
            ]),
            ("Jak dojechać", [
                "Najwygodniej pociągiem. Ze stacji Puszczykowo na linii Poznań–Wrocław zaczynają się szlaki czerwony i żółty, a ze stacji Stęszew szlaki zielony i niebieski. Przez stację Mosina prowadzi szlak niebieski.",
                "Najbliżej siedziby parku w Jeziorach jest stacja Puszczykówko. Stamtąd idzie się ulicą Dworcową w kierunku Jezior.",
            ]),
            ("Warto wiedzieć", [
                "Wstęp na teren parku i na szlaki jest bezpłatny. Płaci się za wejście do Muzeum Przyrodniczego i za parkingi parku.",
            ]),
        ],
        address="Jeziory, 62-050 Mosina",
        hours=[("Szlaki", "dostępne przez cały rok"), ("Biuro parku", "pn–pt 7:00–15:00")],
        tickets=[("Wstęp na szlaki", "bezpłatnie"), ("Muzeum Przyrodnicze", "płatne")],
        phone="+48 61 898 23 00", www=("wpn.gov.pl", "https://wpn.gov.pl/"),
        credit="wielkopolski-park-narodowy",
        sources=[("WPN: dojazd", "https://wpn.gov.pl/dojazd"),
                 ("Wikipedia: Wielkopolski Park Narodowy", "https://pl.wikipedia.org/wiki/Wielkopolski_Park_Narodowy"),
                 ("ekologia.pl: przewodnik po WPN", "https://www.ekologia.pl/srodowisko/przewodnik-po-wielkopolskim-parku-narodowym-praktyczne-wskazowki-i-ekoturystyka/")],
    ),
    dict(
        slug="stadion", cat="wspolczesny", name="Enea Stadion i Muzeum Lecha",
        img="stadion", img_alt="Parowóz przed stadionem miejskim w Poznaniu",
        short="Zwiedzanie stadionu Euro 2012: szatnia, tunel, ławka rezerwowych i muzeum klubu.",
        badge="Pn–sb",
        status=None,
        lead="Stadion Miejski przy ulicy Bułgarskiej to dom Lecha Poznań. Przebudowany obiekt otwarto 20 września 2010 roku, a w 2012 roku rozegrano tu trzy mecze fazy grupowej Euro 2012. Mieści ponad 42 tysiące widzów.",
        sections=[
            ("Zwiedzanie", [
                "Zwiedzanie z przewodnikiem trwa około godziny. Obejmuje szatnię gości, tunel, którym piłkarze wychodzą na boisko, ławki rezerwowych i multimedialne Muzeum Lecha Poznań.",
                "Godziny zwiedzania mogą się zmieniać z powodu meczów i imprez na stadionie. Warto sprawdzić je przed wizytą.",
            ]),
            ("Warto wiedzieć", [
                "Ulgowy bilet przysługuje osobom do 18 lat, studentom do 26 lat, seniorom powyżej 65 lat i osobom z niepełnosprawnościami. Dzieci do 4 lat wchodzą bezpłatnie.",
                "Rodziny dostają zniżkę: 10% dla 2 dorosłych i 1 dziecka, 15% dla 2 dorosłych i 2 dzieci, 20% dla 2 dorosłych i 3 lub więcej dzieci.",
            ]),
        ],
        address="ul. Bułgarska 17, 60-320 Poznań",
        hours=[("V–IX, pn–pt", "12:00, 14:00, 16:00, 17:30"), ("X–IV, pn–pt", "12:00, 14:00, 16:00"), ("Sobota (cały rok)", "10:00, 11:30, 12:45, 14:00")],
        tickets=[("Normalny", "35 zł"), ("Ulgowy", "25 zł"), ("Dzieci do 4 lat", "bezpłatnie")],
        phone="+48 660 423 851", www=("bilety.lechpoznan.pl", "https://bilety.lechpoznan.pl/CMS?page=zwiedzanie"),
        credit="stadion",
        sources=[("Lech Poznań: zwiedzanie stadionu i muzeum", "https://bilety.lechpoznan.pl/CMS?page=zwiedzanie"),
                 ("Wikipedia: Stadion Miejski w Poznaniu", "https://pl.wikipedia.org/wiki/Stadion_Miejski_w_Poznaniu")],
    ),
    dict(
        slug="jezyce", cat="wspolczesny", name="Jeżyce",
        img="jezyce", img_alt="Kamienice przy Rynku Jeżyckim",
        short="Secesyjne kamienice, targ na Rynku Jeżyckim i szlak Jeżycjady Małgorzaty Musierowicz.",
        badge="Bezpłatnie",
        status=None,
        lead="Jeżyce to jedna z najbardziej lubianych dzielnic Poznania. Dawna wieś, wspomniana już w 1253 roku, w 1900 roku została włączona do miasta i szybko zabudowała się kamienicami, wiele z nich z secesyjnymi zdobieniami.",
        sections=[
            ("O dzielnicy", [
                "Pierwsza pisemna wzmianka o Jeżycach pojawia się w przywileju lokacyjnym Poznania z 1253 roku. Przez wieki była to wieś rolnicza. W XVIII wieku osiedlili się tu Bambrzy, osadnicy spod Bambergu.",
                "W 1848 roku na Jeżycach otwarto pierwszy dworzec kolejowy w Poznaniu. Po włączeniu do miasta w 1900 roku wiejską zabudowę zastąpiły wielopiętrowe kamienice czynszowe. Dawny wiejski układ przetrwał w owalnym kształcie ulicy Kościelnej.",
            ]),
            ("Co zobaczyć", [
                "Rynek Jeżycki, serce dzielnicy. Działa na nim jedno z najstarszych targowisk w Poznaniu: warzywa, owoce, kwiaty, pieczywo, sery, miód i używane książki.",
                "Secesyjne kamienice przy ulicach Dąbrowskiego, Mickiewicza, Słowackiego i Prusa, a także wille przy ulicach Roosevelta i Zacisze.",
                "Teatr Nowy przy ulicy Dąbrowskiego i kościół Najświętszego Serca Pana Jezusa i św. Floriana z 1906 roku.",
            ]),
            ("Szlak Jeżycjady", [
                "Na Jeżycach toczy się akcja „Jeżycjady”, cyklu powieści Małgorzaty Musierowicz. Poznańska Lokalna Organizacja Turystyczna przygotowała razem z autorką Poznański Szlak Jeżycjady: około 7 km (skrócony wariant 3 km) przez Jeżyce i Dzielnicę Cesarską, z cytatami i nagraniami czytanymi przez pisarkę.",
            ]),
            ("Warto wiedzieć", [
                "Na Jeżycach są też Stare Zoo i Ogród Botaniczny UAM. Oba miejsca opisujemy na osobnych stronach.",
            ]),
        ],
        address="Rynek Jeżycki, Poznań",
        hours=[("Dzielnica", "dostępna całą dobę"), ("Targowisko na Rynku Jeżyckim", "pn–sb 6:00–20:00, nd nieczynne")],
        tickets=[("Spacer", "bezpłatnie")],
        phone=None, www=("visitpoznan.pl", "https://visitpoznan.pl/rynek-jezycki-poznanski-szlak-jezycjady"),
        credit="jezyce",
        sources=[("poznan.pl: Jeżyce – historia", "https://www.poznan.pl/mim/rewitalizacja/-,p,38552,38561,42846.html"),
                 ("Wikipedia: Jeżyce", "https://pl.wikipedia.org/wiki/Jeżyce"),
                 ("Visit Poznań: Rynek Jeżycki (Poznański Szlak Jeżycjady)", "https://visitpoznan.pl/rynek-jezycki-poznanski-szlak-jezycjady"),
                 ("Targowiska: Rynek Jeżycki", "https://www.targowiska.com.pl/lokalizacje/rynek-jezycki/")],
    ),
    dict(
        slug="bulwary-warta", cat="przyroda", name="Bulwary nad Wartą",
        img="bulwary-warta", img_alt="Plaża miejska nad Wartą na Szelągu",
        short="Wartostrada: 13,6 km ścieżek pieszych i rowerowych wzdłuż rzeki, latem plaże miejskie.",
        badge="Bezpłatnie",
        status=None,
        lead="Wartostrada to system ścieżek pieszych i rowerowych wzdłuż Warty. Dwie trasy po obu brzegach rzeki mają łącznie 13,6 km i prowadzą od Mostu Przemysła I na południu do Mostu Lecha na północy.",
        sections=[
            ("O trasie", [
                "Budowa Wartostrady zaczęła się w 2011 roku, a trasę rozbudowywano w latach 2015–2020 i 2020–2022. Ścieżki są przeznaczone dla pieszych i rowerzystów na każdym poziomie.",
                "Trasa łączy m.in. Most Królowej Jadwigi, Most św. Rocha i Most Bolesława Chrobrego. Prowadzi obok Bramy Poznania i przez parki: Park Szelągowski i Park nad Wartą.",
                "Na trasie są punkty widokowe, stacje naprawy rowerów i parkingi Bike&Ride.",
            ]),
            ("Plaże miejskie", [
                "Latem nad Wartą działają plaże miejskie, m.in. na Chwaliszewie i Szelągu. Terminy sezonu i atrakcje miasto ogłasza co roku.",
            ]),
            ("Warto wiedzieć", [
                "Z Wartostrady łatwo dojść do Ostrowa Tumskiego, Bramy Poznania i Śródki, więc spacer nad rzeką można połączyć z ich zwiedzaniem.",
            ]),
        ],
        address="Wartostrada, Poznań",
        hours=[("Ścieżki", "dostępne całą dobę"), ("Plaże miejskie", "w sezonie letnim")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", "https://www.poznan.pl/"),
        credit="bulwary-warta",
        sources=[("Wikipedia: Wartostrada", "https://pl.wikipedia.org/wiki/Wartostrada"),
                 ("poznan.pl: plaże miejskie", "https://www.poznan.pl/mim/main/-,p,1182,25430,25431.html")],
    ),
    dict(
        slug="park-solacki", cat="przyroda", name="Park Sołacki",
        img="park-solacki", img_alt="Staw w Parku Sołackim",
        short="Stuletni park krajobrazowy ze stawami na Bogdance, wśród willi Sołacza.",
        badge="Bezpłatnie",
        status=None,
        lead="Park Sołacki urządzono w latach 1908–1911 według projektu Hermanna Kube, ówczesnego dyrektora Ogrodów Miejskich w Poznaniu. Ma prawie 15 hektarów i powstał na podmokłych terenach doliny Bogdanki.",
        sections=[
            ("O parku", [
                "To park w stylu angielskim. Rośnie tu około 3000 drzew i 12 000 krzewów, obok gatunków rodzimych także egzotyczne, m.in. jodła kanadyjska, cyprysik i daglezja.",
                "Spiętrzona Bogdanka tworzy Stawy Sołackie o nieregularnych brzegach. Większy, wschodni staw ma 3,22 hektara.",
                "Od 1983 roku park jest wpisany do rejestru zabytków razem z willową dzielnicą Sołacz.",
            ]),
            ("Co zobaczyć", [
                "Stawy, mostki i wodospad na Bogdance.",
                "Zieloną wiatę tramwajową przy ulicy Małopolskiej z 1913 roku, kiedy do Sołacza dojechał tramwaj.",
                "Rzeźbę „Dwie kobiety” Sylwestra Ambroziaka z 2008 roku.",
                "Budynek z 1912 roku, w którym po remoncie w 2022 roku działa hotel z restauracją Port Sołacz.",
            ]),
            ("Warto wiedzieć", [
                "W parku są place zabaw i alejki spacerowe. Można tu spotkać m.in. mandarynki i dzięcioły.",
            ]),
        ],
        address="Park Sołacki, Poznań",
        hours=[("Park", "ogólnodostępny")],
        tickets=[("Wstęp", "bezpłatnie")],
        phone=None, www=("poznan.pl", "https://www.poznan.pl/mim/smartcity/infoteka,1016/park-solacki-zielen-z-ponad-100-letnia-historia,265390.html"),
        credit="park-solacki",
        sources=[("poznan.pl: Park Sołacki – zieleń z ponad 100-letnią historią", "https://www.poznan.pl/mim/smartcity/infoteka,1016/park-solacki-zielen-z-ponad-100-letnia-historia,265390.html"),
                 ("Wikipedia: Park Sołacki", "https://pl.wikipedia.org/wiki/Park_Sołacki")],
    ),
    dict(
        slug="trakt-krolewsko-cesarski", cat="zabytki", name="Trakt Królewsko-Cesarski",
        img="trakt-krolewsko-cesarski", img_alt="Oznakowanie Traktu Królewsko-Cesarskiego z koroną przy Bramie Poznania",
        short="Główny szlak turystyczny Poznania: od Bramy Poznania przez Ostrów Tumski i Stary Rynek do Zamku.",
        badge="Bezpłatnie",
        status=None,
        lead="Trakt Królewsko-Cesarski to główny szlak turystyczno-kulturowy Poznania. Łączy najciekawsze części miasta i opowiada historię Poznania oraz czterdziestu pokoleń jego mieszkańców.",
        sections=[
            ("Przebieg", [
                "Główna oś ma około 3 km i prowadzi na zachód od Bramy Poznania przez Ostrów Tumski z katedrą, Stary Rynek z ratuszem i Stare Miasto po Śródmieście z muzeami i teatrami oraz Zamek Cesarski.",
                "Pierwotnie szlak wyznaczono od kościoła św. Jana Jerozolimskiego za Murami do kościoła Najświętszego Serca Pana Jezusa i św. Floriana na Jeżycach. Wokół głównej osi biegną szlaki dodatkowe.",
                "Na trasie są m.in. katedra, Zamek Królewski, ratusz, dawne Kolegium Jezuickie, Biblioteka Raczyńskich i Zamek Cesarski.",
            ]),
            ("Jak zwiedzać", [
                "Trasę oznaczają bordowe tabliczki z wyciętą koroną, logo traktu, umieszczone na elementach miejskiej infrastruktury.",
                "Szlak można przejść pieszo albo przejechać rowerem i komunikacją miejską. Zwiedzanie jest bezpłatne, a na stronie traktu są darmowe foldery i mapa.",
                "Co roku odbywają się bezpłatne spacery z przewodnikiem.",
            ]),
            ("O szlaku", [
                "Trakt powstał w latach 2006–2013 według koncepcji z 2004 roku, a w 2015 roku przebieg zmodyfikowano. Zarządza nim Poznańskie Centrum Dziedzictwa, miejska instytucja kultury.",
            ]),
        ],
        address="Brama Poznania, ul. Gdańska 2, Poznań",
        hours=[("Szlak", "dostępny całą dobę")],
        tickets=[("Zwiedzanie", "bezpłatnie")],
        phone=None, www=("trakt.poznan.pl", "https://trakt.poznan.pl/"),
        credit="trakt-krolewsko-cesarski",
        sources=[("trakt.poznan.pl: Poznaj Trakt Królewsko-Cesarski", "https://trakt.poznan.pl/poznaj-trakt-krolewsko-cesarski"),
                 ("Wikipedia: Trakt Królewsko-Cesarski w Poznaniu", "https://pl.wikipedia.org/wiki/Trakt_Królewsko-Cesarski_w_Poznaniu")],
    ),
]

_ORDER = {k: i for i, (k, _, _) in enumerate(CATEGORIES)}
from data_extra import EXTRA  # noqa: E402  (atrakcje z rozbudowy od 29.09.2026)
from data_churches import CHURCHES  # noqa: E402  (zabytkowe kościoły, partia 4)
from data_final import FINAL  # noqa: E402  (forty, jeziora, parki, Okrąglak, linie turystyczne)
from data_parks import PARKS  # noqa: E402  (etap 7: duże i zabytkowe parki, Morasko, Lasek Marceliński)
from data_monuments import MONUMENTS  # noqa: E402  (etap 7: pomniki i fontanny z POI poznan.pl)
from data_theatres import THEATRE_ATTR  # noqa: E402  (Teatr Wielki, 30.09.2026)
from data_trips import TRIPS  # noqa: E402  (wycieczki za miasto, 30.09.2026)
# Data sprawdzenia godzin i cen każdej atrakcji (pole checked). Domyślnie według partii danych;
# przy ponownej weryfikacji jednej atrakcji wpisz jej własne checked="DD.MM.RRRR".
_CHECKED_BY_BATCH = [
    (ATTRACTIONS + MORE, "28.09.2026"),
    (EXTRA + CHURCHES + FINAL + PARKS + MONUMENTS, "29.09.2026"),
    (TRIPS + THEATRE_ATTR, "30.09.2026"),
]
_CHECKED_SLUGS = {"park-solacki": "29.09.2026", "trakt-krolewsko-cesarski": "29.09.2026",  # czwarta tura
                  "stary-browar": "30.09.2026"}  # rozbudowa opisu, nowy adres i godziny
for _batch, _date in _CHECKED_BY_BATCH:
    for _a in _batch:
        _a.setdefault("checked", _CHECKED_SLUGS.get(_a["slug"], _date))
ATTRACTIONS = sorted(ATTRACTIONS + MORE + EXTRA + CHURCHES + FINAL + PARKS + MONUMENTS + TRIPS + THEATRE_ATTR, key=lambda a: _ORDER[a["cat"]])

